/* Generated by VDGG */

package com.azoft.nusuth.util;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class HttpConstants {

    public final static char[] CONNECTION = {'C', 'o', 'n', 'n', 'e', 'c', 't', 'i', 'o', 'n'};
    public final static char[] KEEP_ALIVE = {'K', 'e', 'e', 'p', '-', 'A', 'l', 'i', 'v', 'e'};
    public final static char[] CLOSE = {'c', 'l', 'o', 's', 'e'};
    public final static char[] CONTENT_TYPE = {'C', 'o', 'n', 't', 'e', 'n', 't', '-', 't', 'y', 'p', 'e'};
    public final static char[] CONTENT_LENGTH = {'C', 'o', 'n', 't', 'e', 'n', 't', '-', 'l', 'e', 'n', 'g', 't', 'h'};
    public final static char[] WWW_FORM = {'a', 'p', 'p', 'l', 'i', 'c', 'a', 't', 'i', 'o', 'n',
                                           '/', 'x', '-', 'w', 'w', 'w', '-', 'f', 'o', 'r', 'm',
                                           '-', 'u', 'r', 'l', 'e', 'n', 'c', 'o', 'd', 'e', 'd'};
    public final static char[] TRANSFER_ENCODING = {'T', 'r', 'a', 'n', 's', 'f', 'e', 'r', '-', 'E', 'n', 'c', 'o', 'd', 'i', 'n', 'g'};
    public final static char[] CHUNKED = {'c', 'h', 'u', 'n', 'k', 'e', 'd'};
    public final static char[] SERVER_NAME = {'S', 'e', 'r', 'v', 'e', 'r'};
    public final static char[] SERVER_VALUE = {'N', 'u', 's', 'u', 't', 'h', '/', '1', '.', '0', 'b'};
    public final static char[] DATE = {'D', 'a', 't', 'e'};
    public final static char[] METHOD_GET = {'G', 'E', 'T'};
    public final static char[] METHOD_POST = {'P', 'O', 'S', 'T'};
    public final static char[] METHOD_PUT = {'P', 'U', 'T'};
    public final static char[] METHOD_DELETE = {'D', 'E', 'L', 'E', 'T', 'E'};
    public final static char[] METHOD_HEAD = {'H', 'E', 'A', 'D'};
    public final static char[] METHOD_OPTIONS = {'O', 'P', 'T', 'I', 'O', 'N', 'S'};
    public final static char[] METHOD_TRACE = {'T', 'R', 'A', 'C', 'E'};
    public final static char[] COOKIE = {'C', 'o', 'o', 'k', 'i', 'e'};
    public final static char[] HOST = {'H', 'o', 's', 't'};
    public final static char[] IF_MODIFIED_SINCE = "If-Modified-Since".toCharArray();
    public final static char[] LAST_MODIFIED = "Last-Modified".toCharArray();
    public final static String CLIENT_CERTIFICATE_HEADER_NAME_STRING = "NUSUTH_Distributor_Porduced_Client_Certificate";
    public final static char[] CLIENT_CERTIFICATE_HEADER_NAME = CLIENT_CERTIFICATE_HEADER_NAME_STRING.toCharArray();
}
