/* Generated by VDGG */

package com.azoft.nusuth.util;

import java.util.TimeZone;
import java.util.Calendar;

public class HttpDate {

    private final static char[][] daysOfWeek = {{'S', 'u', 'n', ',', ' '},
                                                {'M', 'o', 'n', ',', ' '},
                                                {'T', 'u', 'e', ',', ' '},
                                                {'W', 'e', 'd', ',', ' '},
                                                {'T', 'h', 'u', ',', ' '},
                                                {'F', 'r', 'i', ',', ' '},
                                                {'S', 'a', 't', ',', ' '}
    };

    private final static char[][] months = {{' ', 'J', 'a', 'n', ' '},
                                            {' ', 'F', 'e', 'b', ' '},
                                            {' ', 'M', 'a', 'r', ' '},
                                            {' ', 'A', 'p', 'r', ' '},
                                            {' ', 'M', 'a', 'y', ' '},
                                            {' ', 'J', 'u', 'n', ' '},
                                            {' ', 'J', 'u', 'l', ' '},
                                            {' ', 'A', 'u', 'g', ' '},
                                            {' ', 'S', 'e', 'p', ' '},
                                            {' ', 'O', 'c', 't', ' '},
                                            {' ', 'N', 'o', 'v', ' '},
                                            {' ', 'D', 'e', 'c', ' '}
    };

    private final static char[] numbers = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};
    private final static int[] daysInMonth = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    private final static long f29f = 790;
    private final static long f29delta = 1461;
    private final static long msInDay = 24 * 60 * 60 * 1000;
    private final static long msInHour = 60 * 60 * 1000;
    private final static long msInMinute = 60 * 1000;
    private final static long daysInYear = 365;
    private final static long startYear = 1970;
    private final static char[] GMT = {' ', 'G', 'M', 'T'};
    private static char[] GMTZONE = new char[5];
    private static char[] DEFAULT_GMTZONE = {'+', '0', '0', '0', '0'};

    private static byte[] currentDateHeader = new byte[37];
    private static char[] date4log = new char[28];
    private static long lastCheck = -1;
    private static long lastLogCheck = -1;
    private static HttpDate httpDate = new HttpDate();
    private static long timeZoneOffset = 0;

    static {
        int count = 0;
        String str = Calendar.getInstance().getTimeZone().getDisplayName();
        timeZoneOffset = Calendar.getInstance().getTimeZone().getRawOffset();
        if (str.startsWith("GMT+") && str.length() == 9) {
            for (int i = 3; i < str.length(); i++) {
                if (str.charAt(i) != ':') {
                    GMTZONE[count++] = str.charAt(i);
                }
            }
        } else {
            GMTZONE = DEFAULT_GMTZONE;
        }
    }

    private char[] buf = new char[32];
    private int curPos = 0;

    public HttpDate() {
    }

    public void convert(long date, NusuthHeader header) {
        header.addValueChars(convert(date), 0, curPos);
    }

    public final void convertForLog(long date) {
        date += timeZoneOffset;
        long daysFromStart = date / msInDay;
        long f29passed;
        if (daysFromStart > f29f) {
            f29passed = (daysFromStart - f29f) / f29delta + 1;
        } else {
            f29passed = 0;
        }
        int year = (int) (startYear + (daysFromStart - f29passed) / daysInYear);
        int dayOfYear = (int) (daysFromStart - daysInYear * (year - startYear) - f29passed + 1);
        int day = 0;
        int month = 0;
        if ((daysFromStart - f29f) % f29delta == 0) {
            day = 29;
            month = 1;
        } else {
            for (int i = 0; i < daysInMonth.length; i++) {
                if (dayOfYear <= daysInMonth[i]) {
                    day = dayOfYear;
                    month = i;
                    break;
                } else {
                    dayOfYear -= daysInMonth[i];
                }
            }
        }
        long msFromDayStart = date % msInDay;
        int hour = (int) (msFromDayStart / msInHour);
        int minute = (int) ((msFromDayStart / msInMinute) % 60);
        int second = (int) ((msFromDayStart / 1000) % 60);
        curPos = 0;
        date4log[curPos++] = '[';
        date4log[curPos++] = numbers[day / 10];
        date4log[curPos++] = numbers[day % 10];
        date4log[curPos++] = '/';
        for (int i = 1; i < months[month].length - 1; i++) {
            date4log[curPos++] = months[month][i];
        }
        date4log[curPos++] = '/';
        date4log[curPos++] = numbers[year / 1000];
        date4log[curPos++] = numbers[(year % 1000) / 100];
        date4log[curPos++] = numbers[(year % 100) / 10];
        date4log[curPos++] = numbers[year % 10];
        date4log[curPos++] = ':';
        date4log[curPos++] = numbers[hour / 10];
        date4log[curPos++] = numbers[hour % 10];
        date4log[curPos++] = ':';
        date4log[curPos++] = numbers[minute / 10];
        date4log[curPos++] = numbers[minute % 10];
        date4log[curPos++] = ':';
        date4log[curPos++] = numbers[second / 10];
        date4log[curPos++] = numbers[second % 10];
        date4log[curPos++] = ' ';
        for (int i = 0; i < GMTZONE.length; i++) {
            date4log[curPos++] = GMTZONE[i];
        }
        date4log[curPos++] = ']';
    }

    public char[] convert(long date) {
        long daysFromStart = date / msInDay;
        long f29passed;
        if (daysFromStart > f29f) {
            f29passed = (daysFromStart - f29f) / f29delta + 1;
        } else {
            f29passed = 0;
        }
        int year = (int) (startYear + (daysFromStart - f29passed) / daysInYear);
        int dayOfYear = (int) (daysFromStart - daysInYear * (year - startYear) - f29passed + 1);
        int day = 0;
        int month = 0;
        if ((daysFromStart - f29f) % f29delta == 0) {
            day = 29;
            month = 1;
        } else {
            for (int i = 0; i < daysInMonth.length; i++) {
                if (dayOfYear <= daysInMonth[i]) {
                    day = dayOfYear;
                    month = i;
                    break;
                } else {
                    dayOfYear -= daysInMonth[i];
                }
            }
        }
        long msFromDayStart = date % msInDay;
        int hour = (int) (msFromDayStart / msInHour);
        int minute = (int) ((msFromDayStart / msInMinute) % 60);
        int second = (int) ((msFromDayStart / 1000) % 60);
        int dayOfWeek = (int) ((daysFromStart % 7) + 4) % 7;
        curPos = 0;
        for (int i = 0; i < daysOfWeek[dayOfWeek].length; i++) {
            buf[curPos++] = daysOfWeek[dayOfWeek][i];
        }
        buf[curPos++] = numbers[day / 10];
        buf[curPos++] = numbers[day % 10];
        for (int i = 0; i < months[month].length; i++) {
            buf[curPos++] = months[month][i];
        }
        buf[curPos++] = numbers[year / 1000];
        buf[curPos++] = numbers[(year % 1000) / 100];
        buf[curPos++] = numbers[(year % 100) / 10];
        buf[curPos++] = numbers[year % 10];
        buf[curPos++] = ' ';
        buf[curPos++] = numbers[hour / 10];
        buf[curPos++] = numbers[hour % 10];
        buf[curPos++] = ':';
        buf[curPos++] = numbers[minute / 10];
        buf[curPos++] = numbers[minute % 10];
        buf[curPos++] = ':';
        buf[curPos++] = numbers[second / 10];
        buf[curPos++] = numbers[second % 10];
        for (int i = 0; i < GMT.length; i++) {
            buf[curPos++] = GMT[i];
        }
        return buf;
    }

    public static byte[] getCurrentDateHeader() {
        if (lastCheck == -1) {
            synchronized (currentDateHeader) {
                System.arraycopy("Date: ".getBytes(), 0, currentDateHeader, 0, 6);
                System.arraycopy("\r\n".getBytes(), 0, currentDateHeader, 35, 2);
                char[] dateChars = httpDate.convert(System.currentTimeMillis());
                for (int i = 0; i < 29; i++) {
                    currentDateHeader[6 + i] = (byte) dateChars[i];
                }
                lastCheck = System.currentTimeMillis();
            }
        }
        if (System.currentTimeMillis() - lastCheck > 1000) {
            synchronized (currentDateHeader) {
                if (System.currentTimeMillis() - lastCheck > 1000) {
                    char[] dateChars = httpDate.convert(System.currentTimeMillis());
                    for (int i = 0; i < 29; i++) {
                        currentDateHeader[6 + i] = (byte) dateChars[i];
                    }
                    lastCheck = System.currentTimeMillis();
                }
            }
        }
        return currentDateHeader;
    }


    public static char[] getCurrentDate4log() {
        if (lastLogCheck == -1) {
            synchronized (date4log) {
                httpDate.convertForLog(System.currentTimeMillis());
                lastLogCheck = System.currentTimeMillis();
            }
        }
        if (System.currentTimeMillis() - lastLogCheck > 1000) {
            synchronized (date4log) {
                if (System.currentTimeMillis() - lastLogCheck > 1000) {
                    httpDate.convertForLog(System.currentTimeMillis());
                    lastLogCheck = System.currentTimeMillis();
                }
            }
        }
        return date4log;
    }

}
