/* Generated by VDGG */

package com.azoft.nusuth.util;

import java.io.InputStream;
import java.io.IOException;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NullInputStream extends InputStream {
    public NullInputStream() {
        super();
    }

    public int read() throws IOException {
        return -1;
    }
}

