/* Generated by VDGG */

package com.azoft.nusuth.util;

import java.util.*;
import java.text.*;

import com.azoft.nusuth.core.HttpNusuthServletInputStream;

import java.io.*;
import javax.servlet.http.Cookie;

/**This class is used to store header names and associated values, to manage them,
 * to read them from the HttpNusuthServletInputStream class type objects(and to store inside),
 * to write them to the OutputStream class type objects.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthHeaders {
    private final static int HEADERS_LIMIT = 64;
    private final static int TYPE_STR = 0;
    private final static int TYPE_INT = 1;
    private final static int TYPE_DATE = 2;
    // format for RFC 1123 date string -- "Sun, 06 Nov 1994 08:49:37 GMT"
    private final static String rfc1123Pattern = "EEE, dd MMM yyyyy HH:mm:ss z";
    // format for RFC 1036 date string -- "Sunday, 06-Nov-94 08:49:37 GMT"
    private final static String rfc1036Pattern = "EEEEEEEEE, dd-MMM-yy HH:mm:ss z";
    // format for C asctime() date string -- "Sun Nov  6 08:49:37 1994"
    private final static String asctimePattern = "EEE MMM d HH:mm:ss yyyyy";
    private final static SimpleDateFormat rfc1123Format = new SimpleDateFormat(rfc1123Pattern, Locale.US);
    private final static SimpleDateFormat rfc1036Format = new SimpleDateFormat(rfc1036Pattern, Locale.US);
    private final static SimpleDateFormat asctimeFormat = new SimpleDateFormat(asctimePattern, Locale.US);
    private NusuthHeader[] headers;
    private int capacity;
    private int count = 0;
    private HttpDate httpDate = new HttpDate();
    private final static byte[] crlf = "\r\n".getBytes();
    private NusuthHeader tmp;

    static {
        rfc1123Format.setTimeZone(TimeZone.getTimeZone("GMT"));
        rfc1036Format.setTimeZone(TimeZone.getTimeZone("GMT"));
        asctimeFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
    }

    /**Constructor.
     */
    public NusuthHeaders() {
        capacity = 4;
        headers = new NusuthHeader[capacity];
        for (int i = 0; i < capacity; i++) {
            headers[i] = new NusuthHeader();
        }
    }

    /** This method allocates new resources for the inner variables of this class.
     *   Clears them.
     */
    public void clear() {
        for (int i = 0; i < count; i++) {
            headers[i].clear();
        }
        count = 0;
    }

    //This method expands the inner buffers of header names and header values, to allow to put there more elements.
    private void expandHeaders() {
        capacity *= 2;
        NusuthHeader[] newHeaders = new NusuthHeader[capacity];
        for (int i = 0; i < count; i++) {
            newHeaders[i] = headers[i];
        }
        for (int i = count; i < capacity; i++) {
            newHeaders[i] = new NusuthHeader();
        }
        headers = newHeaders;
    }

    /**This method adds new header with the given name and value.
     * @param name header name.
     * @param value header value.
     */
    public void addHeader(String name, String value) {
        if (count >= capacity) {
            expandHeaders();
        }
        headers[count].setName(name);
        headers[count++].setValue(value);
//    Logger.log("Added "+headers[count-1], 1);
    }

    public void addHeader(char[] nameChars, char[] valueChars) {
        if (count >= capacity) {
            expandHeaders();
        }
        headers[count].addNameChars(nameChars, 0, nameChars.length);
        headers[count++].addValueChars(valueChars, 0, valueChars.length);
    }

    /**This method adds new header with the given name and integer value.
     * @param name header name.
     * @param intValue header value.
     */
    public void addIntHeader(String name, int intValue) {
        if (count >= capacity) {
            expandHeaders();
        }
        headers[count].setName(name);
        headers[count++].setValue(String.valueOf(intValue));
    }

    /**This method adds new header with the given name and date value.
     * Here date is the value of long type.
     * @param name header name.
     * @param dateValue header value.
     */
    public void addDateHeader(String name, long dateValue) {
        if (count >= capacity) {
            expandHeaders();
        }
        headers[count].setName(name);
        httpDate.convert(dateValue, headers[count++]);
    }

    public void addDateHeader(char[] nameChars, long dateValue) {
        if (count >= capacity) {
            expandHeaders();
        }
        headers[count].addNameChars(nameChars, 0, nameChars.length);
        httpDate.convert(dateValue, headers[count++]);
    }

    /**This method removes headers with the given name from the inner buffer.
     * @param name header name.
     */
    public void clearHeader(String name) {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(name)) {
                tmp = headers[i];
                headers[i] = headers[count - 1];
                headers[count - 1] = tmp;
                tmp.clear();
                count--;
                i--;
            }
        }
    }

    public void clearHeader(char[] nameChars) {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(nameChars)) {
                tmp = headers[i];
                headers[i] = headers[count - 1];
                headers[count - 1] = tmp;
                tmp.clear();
                count--;
                i--;
            }
        }
    }

    /**This method puts the new header with String type value to this class.
     * It means that if headers with the given names exist then this method removes them
     * and then adds header with the given name and value. If there are no headers with
     * the given name then this method simply adds new header with the given name and value.
     * @param name header name.
     * @param value header value.
     */
    public void putHeader(String name, String value) {
        clearHeader(name);
        addHeader(name, value);
    }

    public void putHeader(char[] nameChars, char[] valueChars) {
        clearHeader(nameChars);
        addHeader(nameChars, valueChars);
    }

    /**This method puts the new header with the int type value to this class.
     * It means that if headers with the given names exist then this method removes tham
     * and then adds header with the given name and int type value. If there are no headers with
     * the given name then this method simply adds new header with the given name and value.
     * @param name header name.
     * @param intValue header value
     */
    public void putIntHeader(String name, int intValue) {
        clearHeader(name);
        addIntHeader(name, intValue);
    }

    /**This method puts the new header with the date value to this class.
     * It means that if headers with the given names exist then this method removes tham
     * and then adds header with the given name and long type value. If there are no headers with
     * the given name then this method simply adds new header with the given name and value.
     * @param name header name.
     * @param dateValue header value
     */
    public void putDateHeader(String name, long dateValue) {
        clearHeader(name);
        addDateHeader(name, dateValue);
    }

    public void putDateHeader(char[] nameChars, long dateValue) {
        clearHeader(nameChars);
        addDateHeader(nameChars, dateValue);
    }

    /**This method returnes the value of the given header or null if this header doesn't exist.
     * @param name header name.
     * @return header value.
     */
    public String getHeader(String name) {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(name)) {
                return headers[i].getValue();
            }
        }
        return null;
    }

    public void appendHeaderValue(char headerName[], StrBuffer dest) {
        for (int i = 0; i < headers.length; i++) {
            if (headers[i].nameEquals(headerName)) {
                headers[i].appendHeaderValue(dest);
                return;
            }
        }
    }

    /**This method returnes the value of the given header that contains the int type value.
     * It returnes -1 if this header doesn't exist or any error occures.
     * @param name header name.
     * @return header value.
     */
    public int getIntHeader(String name) {
        String strVal = getHeader(name);
        if (strVal == null) {
            return -1;
        }
        return Integer.parseInt(strVal);
    }

    /**This method returnes the value of the header with the given name (it is supposed that this header contains date).
     * It returnes -1 if this header doesn't exist or any error occures.
     * @param name header name.
     * @return header value.
     */
    public long getDateHeader(String name) {
        String value = getHeader(name);
        if (value == null) {
            return -1;
        }
        try {
            return (rfc1123Format.parse(value)).getTime();
        } catch (Exception e) {
        }
        try {
            return (rfc1036Format.parse(value)).getTime();
        } catch (Exception e) {
        }
        try {
            return (asctimeFormat.parse(value)).getTime();
        } catch (Exception pe) {
        }
        return -1;
    }

    /**This method returnes the set of values of the headers with the given names(not case sensitive).
     * @param name header name.
     * @return Enumeration of String type values - values of headers with the given names.
     */
    public Enumeration getHeaders(String name) {
        List list = new ArrayList();
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(name)) {
                list.add(headers[i].getValue());
            }
        }
        return Collections.enumeration(list);
    }

    /**This method returnes Enumeration which contains the header names, each name in this Enumeration is unique.
     * @return Enumeration of String type values - header names of the headers this class contains.
     */
    public Enumeration getHeaderNames() {
        List list = new ArrayList();
        String tmp;
        for (int i = 0; i < count; i++) {
            tmp = headers[i].getName();
            if (!list.contains(tmp)) {
                list.add(tmp);
            }
        }
        return Collections.enumeration(list);
    }

    /**
     * @param name header name
     * @return True if this class contains header with the given name, otherwise False.
     */
    public boolean containsHeader(String name) {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(name)) {
                return true;
            }
        }
        return false;
    }

    public boolean containsHeader(char[] nameChars) {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(nameChars)) {
                return true;
            }
        }
        return false;
    }

    public boolean containsHeader(String name, String value) {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(name) && headers[i].valueEquals(value)) {
                return true;
            }
        }
        return false;
    }

    public boolean containsHeader(char[] nameChars, char[] valueChars) {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(nameChars) && headers[i].valueEquals(valueChars)) {
                return true;
            }
        }
        return false;
    }

    /**This method reads headers and their values and keeps them.
     * @param stream the @see HttpNusuthServletInputStream class from which this method reads headers and their values.
     * @exception IOException if a bad header value was met.
     */
    public void read(HttpNusuthServletInputStream stream) throws IOException {
        if (count >= capacity) {
            expandHeaders();
        }
        while (stream.readHeader(headers[count])) {
            count++;
            if (count > HEADERS_LIMIT) throw new IOException("Too many headers");
            if (count >= capacity) {
                expandHeaders();
            }
        }
    }

    /**This method writes headers and their values to the given output stream.
     * @param os the output stream.
     * @exception IOException if any error occures while writing to the output stream.
     */
    public void write(OutputStream os) throws IOException {
        for (int i = 0; i < count; i++) {
            headers[i].write(os);
        }
        os.write(crlf);
    }

    public Cookie[] processCookies() {
        for (int i = 0; i < count; i++) {
            if (headers[i].nameEquals(HttpConstants.COOKIE)) {
                return headers[i].processCookies();
            }
        }
        return null;
    }

    public int length() {
        return count;
    }

}

