log4j.appender.A1=org.apache.log4j.RollingFileAppender
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.MaxFileSize=20000000
log4j.appender.A1.MaxBackupIndex=10
log4j.appender.A1.Append=true
log4j.appender.A1.layout.ConversionPattern=[%-5p] [%d{ISO8601}] [%c] [%t] %m%n

log4j.category.com.azoft.nusuth=INFO, A1
log4j.category.com.azoft.nusuth.core
log4j.category.com.azoft.nusuth.deployment
log4j.category.com.azoft.nusuth.distributor
log4j.category.com.azoft.nusuth.distributor.cache
log4j.category.com.azoft.nusuth.gui
log4j.category.com.azoft.nusuth.jndi
log4j.category.com.azoft.nusuth.jsp
log4j.category.com.azoft.nusuth.management
log4j.category.com.azoft.nusuth.server
log4j.category.com.azoft.nusuth.session
log4j.category.com.azoft.nusuth.util
log4j.category.com.azoft.nusuth.container
log4j.category.com.azoft.nusuth.container.http
log4j.category.com.azoft.nusuth.webappsecurity

log4j.category.ru.novosoft=INFO, A1
