/* Generated by VDGG */

package com.azoft.nusuth.util;

import java.io.*;
import javax.servlet.http.Cookie;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthHeader {

    private final static int NAME_LENGTH = 16;
    private final static int VALUE_LENGTH = 32;
    private final static int BYTE_LENGTH = 64;

    private final static byte[] delim = ": ".getBytes();
    private final static byte[] crlf = "\r\n".getBytes();

    private char[] name = new char[NAME_LENGTH];
    private char[] value = new char[VALUE_LENGTH];
    private byte[] toStream;
    private int namePos = 0;
    private int valuePos = 0;

    public NusuthHeader() {
    }

    public String getName() {
        return new String(name, 0, namePos);
    }

    public void setName(String nameString) {
        int strLength = nameString.length();
        while (strLength > name.length) {
            expandName();
        }
        nameString.getChars(0, strLength, name, 0);
        namePos = strLength;
    }

    public void addNameChars(char[] nameEnd, int offset, int length) {
        while (name.length - namePos < length) {
            expandName();
        }
        System.arraycopy(nameEnd, offset, name, namePos, length);
        namePos += length;
    }

    public String getValue() {
        return new String(value, 0, valuePos);
    }

    public void setValue(String valueString) {
        int strLength = valueString.length();
        while (strLength > value.length) {
            expandValue();
        }
        valueString.getChars(0, strLength, value, 0);
        valuePos = strLength;
    }

    public void addValueChars(char[] valueEnd, int offset, int length) {
        while (value.length - valuePos < length) {
            expandValue();
        }
        System.arraycopy(valueEnd, offset, value, valuePos, length);
        valuePos += length;
    }

    public boolean nameEquals(String nameString) {
        if (nameString.length() != namePos) {
            return false;
        }
        for (int i = 0; i < namePos; i++) {
            if (name[i] != nameString.charAt(i) &&
                    ((name[i] >= 'A' && name[i] <= 'Z' && name[i] + 'a' - 'A' != nameString.charAt(i)) ||
                    (name[i] >= 'a' && name[i] <= 'z' && name[i] + 'A' - 'a' != nameString.charAt(i)) ||
                    !((name[i] >= 'A' && name[i] <= 'Z') || (name[i] >= 'a' && name[i] <= 'z')))) {
                return false;
            }
        }
        return true;
    }

    public boolean nameEquals(char[] nameChars) {
        if (nameChars.length != namePos) {
            return false;
        }
        for (int i = 0; i < namePos; i++) {
            if (name[i] != nameChars[i] &&
                    ((name[i] >= 'A' && name[i] <= 'Z' && name[i] + 'a' - 'A' != nameChars[i]) ||
                    (name[i] >= 'a' && name[i] <= 'z' && name[i] + 'A' - 'a' != nameChars[i]) ||
                    !((name[i] >= 'A' && name[i] <= 'Z') || (name[i] >= 'a' && name[i] <= 'z')))) {
                return false;
            }
        }
        return true;
    }

    public boolean valueEquals(String valueString) {
        if (valueString.length() != valuePos) {
            return false;
        }
        for (int i = 0; i < valuePos; i++) {
            if (value[i] != valueString.charAt(i) && value[i] >= 'A' && value[i] <= 'Z' && value[i] + 'a' - 'A' != valueString.charAt(i)) {
                return false;
            }
        }
        return true;
    }

    public boolean valueEquals(char[] valueChars) {
        if (valueChars.length != valuePos) {
            return false;
        }
        for (int i = 0; i < valuePos; i++) {
            if (value[i] != valueChars[i] && value[i] >= 'A' && value[i] <= 'Z' && value[i] + 'a' - 'A' != valueChars[i]) {
                return false;
            }
        }
        return true;
    }

    public void write(OutputStream stream) throws IOException {
        if (toStream == null) {
            toStream = new byte[BYTE_LENGTH];
        }
        while (namePos + valuePos + 4 > toStream.length) {
            expandBytes();
        }
        for (int i = 0; i < namePos; i++) {
            toStream[i] = (byte) name[i];
        }
        toStream[namePos] = delim[0];
        toStream[namePos + 1] = delim[1];
        for (int i = 0; i < valuePos; i++) {
            toStream[namePos + 2 + i] = (byte) value[i];
        }
        toStream[namePos + valuePos + 2] = crlf[0];
        toStream[namePos + valuePos + 3] = crlf[1];
        stream.write(toStream, 0, namePos + valuePos + 4);
    }

    public void clear() {
        namePos = 0;
        valuePos = 0;
        if (name.length != NAME_LENGTH) {
            name = new char[NAME_LENGTH];
        }
        if (value.length != VALUE_LENGTH) {
            value = new char[VALUE_LENGTH];
        }
        if (toStream != null && toStream.length != BYTE_LENGTH) {
            toStream = new byte[BYTE_LENGTH];
        }
    }

    private void expandName() {
        char[] tmp = new char[name.length * 2];
        System.arraycopy(name, 0, tmp, 0, namePos);
        name = tmp;
    }

    private void expandValue() {
        char[] tmp = new char[value.length * 2];
        System.arraycopy(value, 0, tmp, 0, valuePos);
        value = tmp;
    }

    private void expandBytes() {
        toStream = new byte[toStream.length * 2];
    }

    public String toString() {
        return (new String(name, 0, namePos)) + ": " + (new String(value, 0, valuePos));
    }

    Cookie[] processCookies() {
        int cookieNum = 1;
        for (int i = 0; i < valuePos; i++) {
            if (value[i] == ';') {
                cookieNum++;
            }
        }
        Cookie[] cookies = new Cookie[cookieNum];
        int currentCookie = 0;
        int curPos = 0;
        int nameStart = 0;
        int nameEnd = 0;
        int valueStart = 0;
        int valueEnd;
        boolean isName = true;
        while (curPos < valuePos) {
            switch (value[curPos]) {
                case '=':
                    if (isName) {
                        nameEnd = curPos - 1;
                        valueStart = curPos + 1;
                        isName = false;
                    }
                    break;
                case ';':
                    if (!isName) {
                        valueEnd = curPos - 1;
                        while (value[valueStart] == ' ') {
                            valueStart++;
                        }
                        if (value[valueStart] == '"') {
                            valueStart++;
                        }
                        while (value[valueEnd] == ' ') {
                            valueEnd--;
                        }
                        if (value[valueEnd] == '"') {
                            valueEnd--;
                        }
                        while (value[nameStart] == ' ') {
                            nameStart++;
                        }
                        while (value[nameEnd] == ' ') {
                            nameEnd--;
                        }
                        cookies[currentCookie++] = new Cookie(nameStart > nameEnd ? "" : new String(value, nameStart, nameEnd - nameStart + 1),
                                valueStart > valueEnd ? "" : new String(value, valueStart, valueEnd - valueStart + 1));
                        isName = true;
                        nameStart = curPos + 1;
                    } else {
                        nameEnd = curPos - 1;
                        while (value[nameStart] == ' ') {
                            nameStart++;
                        }
                        while (value[nameEnd] == ' ') {
                            nameEnd--;
                        }
                        cookies[currentCookie++] = new Cookie(nameStart > nameEnd ? "" : new String(value, nameStart, nameEnd - nameStart + 1), "");
                        nameStart = curPos + 1;
                    }
                    break;
                default:
                    break;
            }
            curPos++;
        }
        if (!isName) {
            valueEnd = curPos - 1;
            while (value[valueStart] == ' ') {
                valueStart++;
            }
            if (value[valueStart] == '"') {
                valueStart++;
            }
            while (value[valueEnd] == ' ') {
                valueEnd--;
            }
            if (value[valueEnd] == '"') {
                valueEnd--;
            }
            if (nameStart < value.length) {
                while (value[nameStart] == ' ') {
                    nameStart++;
                }
            }
            while (value[nameEnd] == ' ') {
                nameEnd--;
            }
            cookies[currentCookie++] = new Cookie(nameStart > nameEnd ? "" : new String(value, nameStart, nameEnd - nameStart + 1),
                    valueStart > valueEnd ? "" : new String(value, valueStart, valueEnd - valueStart + 1));
            isName = true;
            nameStart = curPos + 1;
        } else {
            nameEnd = curPos - 1;
            if (nameStart < value.length) {
                while (value[nameStart] == ' ') {
                    nameStart++;
                }
            }
            while (value[nameEnd] == ' ') {
                nameEnd--;
            }
            cookies[currentCookie++] = new Cookie(nameStart >= nameEnd ? "" : new String(value, nameStart, nameEnd - nameStart + 1), "");
        }
        return cookies;
    }

    public void appendHeaderValue(StrBuffer destination) {
        destination.append(value, 0, valuePos);
    }

}
