/* Generated by VDGG */

package com.azoft.nusuth.util;

import java.io.IOException;
import java.io.OutputStream;
import java.io.Serializable;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class StrBuffer implements Serializable {

    public final static int INITIAL_CAPACITY = 16;
    char[] buffer;
    private int initialCapacity;
    int curPos = 0;
    private static char[] integers = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};
    char[] tmp = new char[16];

    private int byteBufferCapacity = 0;
    private byte[] byteBuffer = null;

    public StrBuffer() {
        this(INITIAL_CAPACITY);
    }

    public StrBuffer(int capacity) {
        buffer = new char[capacity];
        initialCapacity = capacity;
    }

    public char charAt(int index) {
        if (index > curPos)
            throw new IllegalArgumentException();
        return buffer[index];
    }

    public int indexOf(char c) {
        for (int i = 0; i < length(); i++) {
            if (buffer[i] == c)
                return i;
        }
        return -1;
    }

    public int lastIndexOf(char c) {
        for (int i = length() - 1; i >= 0; i--) {
            if (buffer[i] == c)
                return i;
        }
        return -1;
    }

    public String substring(int index) {
        if (index > curPos)
            throw new IllegalArgumentException();
        return new String(buffer, index, curPos - index);
    }

    public String substring(int startIndex, int endIndex) {
        if (endIndex > curPos || (startIndex - endIndex > 0))
            throw new IllegalArgumentException();
        return new String(buffer, startIndex, endIndex - startIndex);
    }

    public StrBuffer subbufer(int index) {
        if (index > curPos)
            throw new IllegalArgumentException();
        StrBuffer result = new StrBuffer();
        result.append(buffer, index, curPos - index);
        return result;
    }

    public StrBuffer subbuffer(int startIndex, int endIndex) {
        if (endIndex > curPos || (startIndex - endIndex > 0))
            throw new IllegalArgumentException();
        StrBuffer result = new StrBuffer();
        result.append(buffer, startIndex, endIndex - startIndex);
        return result;
    }

    public void clear() {
        curPos = 0;
        if (buffer.length != initialCapacity) {
            buffer = new char[initialCapacity];
        }
    }

    public void append(char c) {
        if (curPos >= buffer.length) {
            expandCapacity();
        }
        buffer[curPos++] = c;
    }

    public void append(char[] c) {
        append(c, 0, c.length);
    }

    public void append(char[] c, int off, int len) {
        while (curPos + len > buffer.length) {
            expandCapacity();
        }
        System.arraycopy(c, off, buffer, curPos, len);
        curPos += len;
    }

    public void append(StrBuffer str) {
        append(str.buffer, 0, str.curPos);
    }

    public void append(String s) {
        int len = s.length();
        while (curPos + len > buffer.length) {
            expandCapacity();
        }
        s.getChars(0, len, buffer, curPos);
        curPos += len;
    }

    public boolean equals(String s) {
        if (curPos != s.length()) {
            return false;
        }
        for (int i = 0; i < curPos; i++) {
            if (s.charAt(i) != buffer[i]) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(char[] c) {
        if (curPos != c.length) {
            return false;
        }
        for (int i = 0; i < curPos; i++) {
            if (c[i] != buffer[i]) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(StrBuffer str) {
        if (curPos != str.curPos) {
            return false;
        }
        for (int i = 0; i < curPos; i++) {
            if (str.buffer[i] != buffer[i]) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object o) {
        if (!(o instanceof StrBuffer)) {
            return false;
        }
        StrBuffer str = (StrBuffer) o;
        if (curPos != str.curPos) {
            return false;
        }
        for (int i = 0; i < curPos; i++) {
            if (str.buffer[i] != buffer[i]) {
                return false;
            }
        }
        return true;
    }

    public boolean startsWith(String s) {
        int len = s.length();
        if (len > curPos) {
            return false;
        }
        for (int i = 0; i < len; i++) {
            if (s.charAt(i) != buffer[i]) {
                return false;
            }
        }
        return true;
    }

    public boolean startsWith(char[] c) {
        if (c.length > curPos) {
            return false;
        }
        for (int i = 0; i < c.length; i++) {
            if (c[i] != buffer[i]) {
                return false;
            }
        }
        return true;
    }

    public boolean startsWith(StrBuffer s) {
        if (s.buffer.length > curPos) {
            return false;
        }
        for (int i = 0; i < s.curPos; i++) {
            if (s.buffer[i] != buffer[i]) {
                return false;
            }
        }
        return true;
    }

    public String toString() {
        return new String(buffer, 0, curPos);
    }

    private void expandCapacity() {
        char[] tmp = new char[buffer.length * 2];
        System.arraycopy(buffer, 0, tmp, 0, curPos);
        buffer = tmp;
    }

    public int hashCode() {
        int h = 1;
        for (int i = 0; i < curPos; i++) {
            h = 31 * h + buffer[i++];
        }
        return h;
    }

    public StrBuffer cloneBuf() {
        StrBuffer clone = new StrBuffer(initialCapacity);
        clone.append(this);
        return clone;
    }

    public int length() {
        return curPos;
    }

    public void cutToChar(char c, boolean cutAll) {
        int index = (cutAll) ? 0 : curPos;
        for (int i = (curPos - 1); i > 0; i--) {
            if (buffer[i] == c) {
                index = i;
                break;
            }
        }
        curPos = index;
    }

    public boolean containsChar(char c) {
        for (int i = 0; i < curPos; i++) {
            if (buffer[i] == c)
                return true;
        }
        return false;
    }

    public void cutToFirstChar(char c, boolean cutAll) {
        int index = (cutAll) ? 0 : curPos;
        for (int i = 0; i < curPos; i++) {
            if (buffer[i] == c) {
                index = i;
                break;
            }
        }
        curPos = index;
    }

    public String cutToEnd(char[] start, boolean include) {
        if (start.length > curPos) {
            return null;
        }
        int checkEnd = curPos - start.length + 1;
        int startPos = 0;
        boolean found = false;
        while (true) {
            for (int i = startPos; i < checkEnd; i++) {
                if (buffer[i] == start[0]) {
                    startPos = i;
                    found = true;
                    break;
                }
            }
            if (found) {
                for (int i = 0; i < start.length; i++) {
                    if (buffer[i + startPos] != start[i]) {
                        found = false;
                        startPos++;
                        break;
                    }
                }
                if (found) {
                    String result = new String(buffer, include ? startPos : startPos + start.length, include ? curPos - startPos : curPos - startPos - start.length);
                    curPos = startPos;
                    return result;
                }
            } else {
                break;
            }
        }
        return null;
    }

    final void copy2Bytes(byte[] to, int startPos) {
        if (curPos > to.length - startPos) {
            throw new IllegalArgumentException("StrBuffer too long");
        }
        for (int i = 0; i < curPos; i++) {
            to[startPos + i] = (byte) buffer[i];
        }
    }

    public final void appendInt(int intValue) {
        int ost = intValue;
        int counter = 15;
        while (ost > 0) {
            tmp[counter] = integers[ost % 10];
            ost /= 10;
            counter--;
            if (ost > 0 && counter < 0) {
                char[] tmp1 = new char[tmp.length * 2];
                for (int i = tmp.length - 1; i >= 0; i--) {
                    tmp1[tmp.length + i] = tmp[i];
                }
                counter = tmp.length - 1;
                tmp = tmp1;
            }
        }
        append(tmp, counter + 1, tmp.length - counter - 1);
        if (tmp.length > 16) {
            tmp = new char[16];
        }
    }

    public void writeToOutputStream(OutputStream ostream) throws IOException {
        if (curPos > byteBufferCapacity) {
            byteBuffer = new byte[curPos];
            byteBufferCapacity = curPos;
        }

        for (int i = 0; i < curPos; i++) {
            byteBuffer[i] = (byte) buffer[i];
        }

        ostream.write(byteBuffer, 0, curPos);
    }
}
