/* Generated by VDGG */

package com.azoft.nusuth.container;

import java.util.*;

import com.azoft.nusuth.util.*;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class InvocationCache {

    private Hashtable cache = new Hashtable();
    private org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.container");
    private LogCategoryProxy catProxy = LogCategoryProxy.getInstance("com.azoft.nusuth.container");
    private long size = 0;
    private long availSize = 0;

    public InvocationCache() {
        (new InvocationCacheCleaner(60000, 120000)).start();
    }

    public InvocationCache(long checkInterval) {
        (new InvocationCacheCleaner(checkInterval, 120000)).start();
    }

    public void clear() {
        cache.clear();
        availSize = size;
    }

    public long getSize() {
        return size;
    }

    public long getAvailableSize() {
        return availSize;
    }

    public void setSize(long size) {
        this.size = size;
    }

    public void setAvailableSize(long availSize) {
        this.availSize = availSize;
    }

    public void add(StrBuffer url, InvocationCacheElement element) {
        element.lastAccess = System.currentTimeMillis();
        synchronized (cache) {
            cache.put(url, element);
        }
    }

    public void remove(StrBuffer url) {
        InvocationCacheElement elem = find(url);
        synchronized (cache) {
            if (elem instanceof com.azoft.nusuth.core.FileInvocationCacheElement) {
                availSize = availSize + ((com.azoft.nusuth.core.FileInvocationCacheElement) elem).fileContent.length;
            }
            cache.remove(url);
        }
    }

    public InvocationCacheElement find(StrBuffer url) {
        InvocationCacheElement res = null;
        synchronized (cache) {
            res = (InvocationCacheElement) cache.get(url);
        }
        if (res != null) {
            res.lastAccess = System.currentTimeMillis();
//      System.out.println("Found context "+res.contextPath+" for url "+url);
        }
        return res;
    }

    class InvocationCacheCleaner extends Thread {

        private long checkInterval;
        private long timeout;

        InvocationCacheCleaner(long checkInterval, long timeout) {
            this.checkInterval = checkInterval;
            this.timeout = timeout;
        }

        public void run() {
            Enumeration enum;
            InvocationCacheElement element;
            StrBuffer url;
            long currentTime;
            while (true) {
                //Logger.log("Invocation cache cleaner started...", 0);
                cat.debug("Invocation cache cleaner started...");
                currentTime = System.currentTimeMillis();
                synchronized (cache) {
                    enum = cache.keys();
                    while (enum.hasMoreElements()) {
                        url = (StrBuffer) enum.nextElement();
                        element = (InvocationCacheElement) cache.get(url);
                        if (element == null) continue;
                        if (currentTime - element.lastAccess > timeout) {
                            //Logger.log("[Invocation cache] removing "+url, 0);
                            cat.debug("Removing from invocation cache ");
                            if (cache.get(url) instanceof com.azoft.nusuth.core.FileInvocationCacheElement) {
                                availSize = availSize + ((com.azoft.nusuth.core.FileInvocationCacheElement) cache.get(url)).fileContent.length;
                            }
                            cache.remove(url);
                        }
                    }
                }
                //Logger.log("Invocation cache cleaner stopped...", 0);
                cat.debug("Invocation cache cleaner stopped...");
                try {
                    sleep(checkInterval);
                } catch (InterruptedException iex) {
                    if (catProxy.isDebugEnabled()) cat.debug("Cache cleaner interrupted");
                }
            }
        }
    }
}
