/* Generated by VDGG */

package com.azoft.nusuth.container;

import com.azoft.nusuth.management.*;

import java.io.*;
import java.util.Properties;

/**This class creates and holds the @see JBirdContainer class instance.
 * It uses the command line arguments as the parameters for the @see JBirdContainer class constructor.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthContainerStarter {

    /**This method creates the instance of the @see JBirdContainer class.
     * @param args the set of parameters for the @see JBirdContainer class constructor.
     */
    public static void main(String[] args) {
        try {
            ContainerManager container = new ContainerManagerImpl(args.length > 0 ? args[args.length - 1] : null);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}

