/* Generated by VDGG */

package com.azoft.nusuth.container;

import java.io.*;
import java.net.*;

import com.azoft.nusuth.deployment.*;

import java.util.Enumeration;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthContainerStopper {

    private String configPath;

    public NusuthContainerStopper(String configPath) throws Exception {
        if (System.getProperty("nusuth.home") == null) {
            throw new Exception("System property nusuth.home not specified");
        }
        File jbirdHome = new File(System.getProperty("nusuth.home"));
        if (!jbirdHome.exists() || !jbirdHome.isDirectory()) {
            throw new Exception("Cannot find directory " + System.getProperty("nusuth.home"));
        }
        if (configPath == null) {
            File confFile = new File(jbirdHome, "admin" + File.separator + "container.xml");
            if (!confFile.exists()) {
                throw new Exception("Cannot find config");
            }
            this.configPath = confFile.getPath();
        } else {
            this.configPath = configPath;
        }

        ContainerEntityResolver resolver = new ContainerEntityResolver();
        NusuthAppConfigFactory.addEntityResolver("container", resolver);
        CompositeNusuthWebAppElement conf = NusuthAppConfigFactory.createConfig("container", this.configPath);
        CompositeNusuthWebAppElement tcpServer = (CompositeNusuthWebAppElement) conf.getCompositeChild("tcp-server").nextElement();
        String portStr = ((SimpleNusuthWebAppElement) tcpServer.getSimpleChild("port").nextElement()).getContent();
        int port = Integer.parseInt(portStr);


        //parses the xml container configuration file.
        //    JBirdContainerConfig config = new JBirdContainerConfig(this.configPath);
        //gets log location.
        CompositeNusuthWebAppElement logger = ((CompositeNusuthWebAppElement) conf.getCompositeChild("logger").nextElement());
        Enumeration enum = logger.getSimpleChild("location");
        String logLocation = enum.hasMoreElements() ? ((SimpleNusuthWebAppElement) enum.nextElement()).getContent() : System.getProperty("nusuth.home") + File.separator + "logs";
        //This part of code is responsible for opening the log file.
        // And for setting logger object parameters.
        File logdir = null;
        String key = null;
        try {
            logdir = logLocation == null ? new File(jbirdHome, "logs") : new File(logLocation);
            if (logdir.exists() && logdir.isDirectory()) {
                File keyFile = new File(logdir, "nusuth.key");
                if (!keyFile.exists()) {
                    throw new Exception("Cannot find Nusuth shutdown key");
                }
                FileInputStream kfos = new FileInputStream(keyFile);
                char[] c = new char[64];
                int readed = 0;
                int b;
                while ((b = kfos.read()) != -1) {
                    c[readed++] = (char) b;
                }
                kfos.close();
                key = new String(c, 0, readed);
            } else {
                System.out.println("{Nusuth} Directory " + logLocation +
                        " doesn't exist or is not directory");
                System.exit(1);
            }
        } catch (IOException ioex) {
            System.out.println("{Nusuth} Can't read Nusuth shutdown key, nested: " + ioex);
            System.exit(1);
        }
        Socket client = null;
        try {
            System.out.print("Shutting down...");
            client = new Socket("localhost", port);
            OutputStream stream = client.getOutputStream();
            stream.write(("GET /" + key + " HTTP/1.1\r\nHost: localhost:" + port + "\r\n\r\n").getBytes());
            stream.flush();
            InputStream is = client.getInputStream();
            StringBuffer in = new StringBuffer();
            try {
                int b;
                while ((b = is.read()) != -1) {
                    in.append((char) b);
                }
            } catch (Exception ex) {
            }
            if (in.toString().startsWith("HTTP/1.1 200")) {
                System.out.println(" successful.");
            } else {
                System.out.println(" error, server return bad response: " + in.toString());
            }
        } catch (Exception ex) {
            System.out.println("Cannot shutdown container, nested: " + ex);
        } finally {
            if (client != null) {
                try {
                    client.close();
                } catch (Exception ex) {
                }
            }
        }
    }

    public static void main(String[] args) {
        try {
            NusuthContainerStopper stopper = new NusuthContainerStopper(args.length > 0 ? args[args.length - 1] : null);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
