/* Generated by VDGG */

package com.azoft.nusuth.container;

import com.azoft.nusuth.core.*;
import com.azoft.nusuth.util.StrBuffer;

import java.net.Socket;
import javax.servlet.FilterChain;

import com.azoft.nusuth.webappsecurity.ResourceSecurityRecord;

/**This abstract class represents methods and variables common to different adapters.
 * Extended by @see HttpProtocolAdapter and @see AJP11ProtocolAdapter classes.
 * @author vdgg, skilz
 * @version 1.18
 * @since Nusuth1.0
 */
public abstract class ProtocolAdapter {

    public static final int ERROR_SERVLET_NOT_FOUND = 0;
    public static final int ERROR_CANNOT_INIT_SERVLET = 1;
    public static final int ERROR_SERVLET_REPORTED = 2;
    public static final int ERROR_HANDLER_INTERNAL = 3;
    public static final int ERROR_OK = 4;
    public static final int ERROR_UNAUTHORIZED = 5;
    public static final int ERROR_FORBIDDEN = 6;
    public static final int ERROR_AUTHENTICATION_FAILED = 7;

    private static boolean standAlone = false;

    protected boolean keepAliveAllowed = false;
    protected boolean good = true;
    protected boolean keepAlive = false;
    protected boolean isSecure;
    protected Socket socket;
    protected static String containerID;
    protected String servletName;
    private static String serverAddress;
    private static int serverPort = -1;
    private static int sslPort = -1;

    /**
     * @return request object.
     */
    public abstract NusuthRequest getRequest();

    /**
     * @return response object.
     */
    public abstract NusuthResponse getResponse();

    /**
     * @return the request URI.
     */
    public abstract StrBuffer getSecretKeyCandidate();

    public abstract StrBuffer getHostWithUri();

    /**
     * This method return requested host.
     * @return Requested host or "*" if request not contains Host header.
     */
    public abstract String getHost();

    /**
     * @param socket socket picked out for this connection.
     */
    protected void setSocket(Socket socket) {
        this.socket = socket;
    }

    /**
     * @return False if any error occures during parsing request data or creating request object.
     */
    public boolean isGood() {
        return good;
    }

    public void setSecure(boolean isSecure) {
        this.isSecure = isSecure;
    }

    /**This method should send response with the error message which depends on the error code.
     * @param error code number.
     */
    public abstract void processError(int error);

    public abstract void processError(int error, Exception ex);

    /**
     * @return True if the keep alive connection is used, otherwise False.
     */
    public boolean isKeepAlive() {
        return keepAlive;
    }

    /**This method sets context and context path.
     * @param context web application context.
     * @param contextPath path to the corresponding web application context.
     */
    public abstract ContainerInvocationCacheElement setContext(NusuthContext context, String contextPath);

    /**This method sets context and context path.
     * @param context web application context.
     * @param contextPath path to the corresponding web application context.
     */
    public abstract void setContext(ContainerInvocationCacheElement cacheElement);

    /**
     * @param cID container ID
     */
    public static void setContainerID(String cID) {
        containerID = cID;
        NusuthResponse.setContainerID(cID);
    }

    public static String getContainerID() {
        return containerID;
    }

    /**
     * @return servlet name.
     */
    public String getServletName() {
        return servletName;
    }

    public abstract ResourceChain getResourceChain();

    /**
     * @param newStandAlone True, then no distributor running over container, False, then requests come from distributor.
     */
    public final static void setStandAlone(boolean newStandAlone) {
        standAlone = newStandAlone;
    }

    /**Should finish the adapters work.
     * Closes input output streams of the socket.
     */
    protected abstract void close();

    /**
     * @return  True, then no distributor running over container, False, then requests come from distributor.
     */
    public final static boolean isStandAlone() {
        return standAlone;
    }

    /**This method sets new server parameters.
     * @param newServerAddress new server address.
     * @param newServerPort new server poth.
     */
    public static void setServerParameters(String newServerAddress, int newServerPort) {
        serverAddress = newServerAddress;
        serverPort = newServerPort;
    }

    public static void setSSLPort(int port) {
        sslPort = port;
    }

    public static int getSSLPort() {
        return sslPort;
    }

    public static int getPort() {
        return serverPort;
    }


    /**
     * @return the server address.
     */
    public String getServerHost() {
        return serverAddress;
    }

    /**
     * @return the server port number.
     */
    public int getServerPort() {
        if (isSecure) {
            return sslPort;
        } else {
            return serverPort;
        }
    }

    /**This method is used to start parsing of the request.
     */
    public abstract void parse();

    public abstract void partialCleanup();

    public void cleanup() {
        good = true;
        keepAlive = false;
        servletName = null;
        socket = null;
    }

    protected void allowKeepAlive() {
        keepAliveAllowed = true;
    }

    protected boolean isKeepAliveAllowed() {
        return keepAliveAllowed;
    }

    public abstract void sendRedirect(String scheme, int port);

    public abstract void writeDeny();

    public abstract void processUnavailable(int seconds, String message);

    // added by igork

    public abstract ResourceSecurityRecord getResourceSecurityRecord();

    public abstract void saveRequest();

    public abstract void restoreRequest();
}

