package com.azoft.nusuth.management;

/*****************************************************************************
 *                                                                           *
 *                      (c) 2000-2001 Thruport Technologies                  *
 *                                                                           *
 *****************************************************************************/
/* Generated by VDGG */

public class ContainerCountInfo extends CountInfo {

    private String container = "<undefined>";


    /**
     * Insert the method's description here.
     * Creation date: (11.01.01 15:15:53)
     * @return java.lang.String
     */
    public String getContainer() {
        return container;
    }


    /**
     * Insert the method's description here.
     * Creation date: (11.01.01 15:15:53)
     * @param newContainer java.lang.String
     */
    public void setContainer(String newContainer) {
        container = newContainer;
    }
}