package com.azoft.nusuth.management;/* Generated by VDGG */

import java.io.Serializable;

public class ContainerInfo implements Serializable {

    public String containerId;
    public String host;
    public int port;
    public String[] applicationsBound;


    public ContainerInfo(String containerId, String host, int port) {
        this.containerId = containerId;
        this.host = host;
        this.port = port;
        applicationsBound = new String[0];
    }


    public ContainerInfo(String containerId, String host, int port, String[] applicationsBound) {
        this.containerId = containerId;
        this.host = host;
        this.port = port;
        this.applicationsBound = applicationsBound;
    }
}