package com.azoft.nusuth.management;/* Generated by VDGG */

import java.io.Serializable;

public class CountInfo implements Serializable {

    private int count = 0;
    private String subject = "<undefined>";


    /**
     * Insert the method's description here.
     * Creation date: (11.01.01 15:14:29)
     * @return long
     */
    public int getCount() {
        return count;
    }


    /**
     * Insert the method's description here.
     * Creation date: (11.01.01 15:14:29)
     * @return java.lang.String
     */
    public String getSubject() {
        return subject;
    }


    /**
     * Insert the method's description here.
     * Creation date: (11.01.01 15:14:29)
     * @param newCount long
     */
    public void setCount(int newCount) {
        count = newCount;
    }


    /**
     * Insert the method's description here.
     * Creation date: (11.01.01 15:14:29)
     * @param newSubject java.lang.String
     */
    public void setSubject(String newSubject) {
        subject = newSubject;
    }
}