package com.azoft.nusuth.management;

/*****************************************************************************
 *                                                                           *
 *                      (c) 2000-2001 Thruport Technologies                  *
 *                                                                           *
 *****************************************************************************/
/* Generated by Together */

public class DistributorState extends ServerState {

    private ContainerCountInfo[] requestCount;


    public int getApplicationRequestCount(String appUrl) {

        for (int i = 0; i < requestCount.length; i++) {
            if (requestCount[i].getSubject().equals(appUrl)) {
                return requestCount[i].getCount();
            }
        }

        return 0;
    }


    public int getContainerRequestCount(String containerId) {

        for (int i = 0; i < requestCount.length; i++) {
            if (requestCount[i].getContainer().equals(containerId)) {
                return requestCount[i].getCount();
            }
        }

        return 0;
    }


    /**
     * Insert the method's description here.
     * Creation date: (08.01.01 19:46:49)
     * @return ContainerCountInfo[]
     */
    public ContainerCountInfo[] getRequestCount() {
        return requestCount;
    }

    public int getTotalRequestCount() {
        int result = 0;

        for (int i = 0; i < requestCount.length; i++) {
            result += requestCount[i].getCount();
        }

        return result;
    }


    /**
     * Insert the method's description here.
     * Creation date: (08.01.01 19:46:49)
     * @param newRequestCount ContainerCountInfo[]
     */
    void setRequestCount(ContainerCountInfo[] newRequestCount) {
        requestCount = newRequestCount;
    }
}