package com.azoft.nusuth.management;/* Generated by Together */

import java.io.Serializable;

public class ServerState implements Serializable {

    private int activeHandlers;
    private int totalHandlers;
    private int activeKeepAlives;


    /** Method returns number of handlers processing requests */
    public int getActiveHandlers() {
        return activeHandlers;
    }


    public int getActiveKeepAlives() {
        return activeKeepAlives;
    }


    /**
     * Method returns total number of handlers running in system. Note that number of waiting handlers is number of total
     * handlers minus number of active handlers
     */
    public int getTotalHandlers() {
        return totalHandlers;
    }


    void setActiveHandlers(int activeHandlers) {
        this.activeHandlers = activeHandlers;
    }


    void setActiveKeepAlives(int activeKeepAlives) {
        this.activeKeepAlives = activeKeepAlives;
    }


    void setTotalHandlers(int totalHandlers) {
        this.totalHandlers = totalHandlers;
    }
}