/* Generated by VDGG */

package com.azoft.nusuth.container.http;

import com.azoft.nusuth.container.*;
import com.azoft.nusuth.core.*;
import com.azoft.nusuth.session.NusuthSession;
import com.azoft.nusuth.util.*;
import com.azoft.nusuth.webappsecurity.ResourceSecurityRecord;
import com.azoft.nusuth.webappsecurity.AuthenticationData;

import java.io.*;
import java.net.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;

import org.apache.log4j.Category;

/**This class is responsible for parsing request data, creating and holding
 * the request and response objects.
 * it's also responsible for filling request object attributes.
 * @version 1.61
 * @since Nusuth1.0
 * @author vdgg, skilz
 */
public class HttpProtocolAdapter extends ProtocolAdapter {
    public final static String REMOTE_ADDR_HEADER_NAME = "Remote-Addr";
    private final static char[] star = {'*'};
    private final static char[] httpStart = {'h', 't', 't', 'p', ':', '/', '/'};
    private final static char[] http11 = {'H', 'T', 'T', 'P', '/', '1', '.', '1'};
    private final static char[] sessionChars
            = {';', 'j', 's', 'e', 's', 's', 'i', 'o', 'n', 'i', 'd', '='};
    private static char[] HOST_HEADER_NAME = {'H', 'o', 's', 't'};
    private static char[] REFERER_HEADER_NAME
            = {'R', 'e', 'f', 'e', 'r', 'e', 'r'};
    private static char[] AGENT_HEADER_NAME
            = {'U', 's', 'e', 'r', '-', 'A', 'g', 'e', 'n', 't'};
    private static char[][] chars4log
            = {{' ', '-', ' ', '-', ' '}, {' ', '\"'}, {'\"', ' '}, {' ', '-'}};
    private static char[] systemCRLF;
    private static HashSet allHosts = new HashSet();
    private final static String METHOD_GET = "GET";
    private final static String METHOD_POST = "POST";
    private final static Hashtable catPool = new Hashtable();
    private final static char[] slash = {'/'};
    private String host = null;
    private StrBuffer hostHeader = new StrBuffer();
    private StrBuffer hostWithUri = new StrBuffer();
    private StrBuffer hostId = new StrBuffer();
    private HttpNusuthServletInputStream inputStream
            = new HttpNusuthServletInputStream(null);
    private OutputStream outputStream = null;
    private int errorCode = HttpServletResponse.SC_OK;
    private HttpNusuthRequest request = null;
    private HttpNusuthResponse response = new HttpNusuthResponse(null);
    private NusuthHeaders headers = new NusuthHeaders();
    private String scPath;
    private int contentLength = -1;
    private NusuthServletOutputStream servletOutput
            = new NusuthServletOutputStream(null);
    private NusuthServletInputStream nullServletInput
            = new NusuthServletInputStream(new NullInputStream());
    private FixedLengthServletInputStream fixedServletInput
            = new FixedLengthServletInputStream(null);
    private ChunkedServletInputStream chunkedServletInput
            = new ChunkedServletInputStream(null);
    private Hashtable parameters = new Hashtable();
    private HttpRequestLine requestLine = new HttpRequestLine();
    private String requestURI;
    private ContainerInvocationCacheElement cacheElement;
    private org.apache.log4j.Category cat
            = org.apache.log4j.Category.getInstance("com.azoft.nusuth."
            + "container.http");
    private LogCategoryProxy catProxy
            = LogCategoryProxy.getInstance("com.azoft.nusuth.container.http");
    private int usingStream = 0;
    private int serverPort;
    private String serverHost;
    private HttpDate date = new HttpDate();
    private StrBuffer logMessage = new StrBuffer();
    private boolean successfullyParsed = false;
    private char[] reqTime;
    private static ResourceBundle lStrings
            = ResourceBundle.getBundle("javax.servlet.http.LocalStrings");

    static {
        if (File.pathSeparatorChar == ':') {
            systemCRLF = new char[1];
            systemCRLF[0] = '\n';
        } else {
            systemCRLF = new char[2];
            systemCRLF[0] = '\r';
            systemCRLF[1] = '\n';
        }
    }

    /**Constructor.
     */
    public HttpProtocolAdapter() {
        request = new HttpNusuthRequest(headers, this);
    }

    /**
     * @return request object.
     */
    public NusuthRequest getRequest() {
        return request;
    }

    /**
     * @return response object.
     */
    public NusuthResponse getResponse() {
        return response;
    }

    /**
     * @return request's URI.
     */
    public StrBuffer getRequestURI() {
        if (requestURI == null) {
            return requestLine.uri;
        } else {
            StrBuffer tmp = new StrBuffer();
            tmp.append(requestURI);
            return tmp;
        }
    }

    /**This method sets the socket picket out for the request processing.
     * It gets the input stream from socket and creates the output stream.
     * @param socket the socket picked out for this connection.
     */
    public void setSocket(Socket socket) {
        super.setSocket(socket);
        try {
            inputStream.init(socket.getInputStream());
            outputStream = socket.getOutputStream();
        } catch (IOException ioex) {
            //Logger.log("Cannot get input stream from socket", ioex, 1);
            cat.error("Cannot get input stream from socket", ioex);
            good = false;
            return;
        }
    }

    /**This method parses the request or doing nothing if there is no input
     * stream or output stream associated with the socket.
     */
    public void parse() {
        //Checks if there are input, output streams available.
        if (inputStream == null || outputStream == null) {
            //Logger.log("Invalid socket", 1);
            cat.error("Invalid socket");
            good = false;
            return;
        }
        reqTime = HttpDate.getCurrentDate4log();
        try {
            inputStream.readRequestLine(requestLine);
        } catch (IOException ioex) {
            //Logger.log(ioex, -1);
            cat.debug("Cannot read request line", ioex);
            good = false;
            return;
        }


        if (requestLine.uri.equals(star)) {
            processServerRequest();
            good = false;
            return;
        }
        if (requestLine.uri.startsWith(httpStart)) {
            requestURI = requestLine.uri.toString();
            int index = requestURI.indexOf('/', 8);
            host = index > -1
                    ? requestURI.substring(7, index)
                    : requestURI.substring(7, requestURI.length());
            requestURI = index > -1
                    ? requestURI.substring(index, requestURI.length())
                    : "/";
        }
        String jsession = requestLine.uri.cutToEnd(sessionChars, false);
        if (jsession != null) {
            request.setSessionIdFromURL(jsession);
        }
        try {
            headers.read(inputStream);
        } catch (IOException ioex) {
            //Logger.log("Error occured while processing headers", ioex, 1);
            cat.debug("Error occured while processing headers", ioex);
            good = false;
            errorCode = HttpServletResponse.SC_BAD_REQUEST;
            writeError();
            return;
        }

        successfullyParsed = true;
        keepAlive = !isStandAlone();
    }

    /**This method sends response with the error message.
     */
    private void writeError(Exception ex) {
        //    System.out.println("!!!!!!!!!!!!!!!!!!!1");
        try {
            servletOutput.init(outputStream);
            response.init(servletOutput, keepAlive);
            if (!isStandAlone()) {
                //        response.setContainerID(containerID);
            }
            if (ex != null) {
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                PrintStream ps = new PrintStream(baos);
                ex.printStackTrace(ps);
                ps.flush();
                Exception exception = null;
                if (ex instanceof ServletException) {
                    exception = (Exception) ((ServletException) ex).getRootCause() == null
                            ? exception
                            : (Exception) ((ServletException) ex).getRootCause();
                } else {
                    exception = ex;
                }
                response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                        baos.toString());
            } else {
                response.sendError(errorCode);
            }
        } catch (IOException ioex) {
            //Logger.log("Error occured while writing error", ioex, 1);
            //      cat.error("Error occured while writing error");
        }
    }

    private void writeError() {
        writeError(null);
    }

    /**Doing nothing :)
     */
    private void processServerRequest() {
    }

    /**This method takes the error code number and then sends response with
     * the error message and then closes connection socket.
     * @param error error code.
     */
    public void processError(int error) {
        processError(error, null);
    }

    public void processError(int error, Exception ex) {
        switch (error) {
            case ERROR_SERVLET_NOT_FOUND:
                errorCode = 404;
                break;
            case ERROR_OK:
                errorCode = 200;
                break;
            case ERROR_FORBIDDEN:
                errorCode = 403;
                break;
            case ERROR_UNAUTHORIZED:
                errorCode = 401;
                processUnauthorizedError(true);
                break;
            case ERROR_AUTHENTICATION_FAILED:
                errorCode = 401;
                processUnauthorizedError(false);
                break;
            case ERROR_CANNOT_INIT_SERVLET:
            case ERROR_HANDLER_INTERNAL:
            case ERROR_SERVLET_REPORTED:
            default:
                errorCode = 500;
                break;
        }
        if (error != ERROR_UNAUTHORIZED && error != ERROR_AUTHENTICATION_FAILED)
            writeError(ex);
        /*    try {
         socket.close();
         } catch (IOException ioex) {
         //Logger.log("Error occured while closing socket", ioex, 1);
         cat.error("Error occured while closing socket");
         }*/
    }

    public ResourceChain getResourceChain() {
        return cacheElement.chain;
    }

    /**
     * This method process unauthorized error.
     * @param isLoginPageNeeded True if login page needed for user.
     */
    private void processUnauthorizedError(boolean isLoginPageNeeded) {
        NusuthContext currContext = getContext();
        switch (currContext.getDefaultAuthType()) {
            case AuthenticationData.AUTH_METHOD_FORM:
                String formPage = isLoginPageNeeded
                        ? getContext().getFormLoginPage().toString()
                        : getContext().getFormErrorPage().toString();
                if (isLoginPageNeeded)
                    saveRequest();
                try {
                    String url = this.getScheme() + "://" + getServerHost() + ':'
                            + getServerPort() + this.getContextPath();
                    url += formPage.startsWith("/") ? formPage : '/' + formPage;
                    if (!isLoginPageNeeded) {
                        RequestDispatcher disp
                                = request.getRequestDispatcher(formPage.startsWith("/") ? formPage : '/' + formPage);
                        response.reset();
                        response.setStatus(401);
                        try {
                            disp.include(request, response);
                        } catch (ServletException e) {
                            cat.error("Caanot send error page", e);
                        }
                    } else {
                        sendRedirect(url);
                    }
                } catch (IOException ioex) {
                    //cat.error("Error occured while requesting user authentication");
                }
                break;
            case AuthenticationData.AUTH_METHOD_CERT:
                // not implemented
            case AuthenticationData.AUTH_METHOD_DIGEST:
                // not implemented
            case AuthenticationData.AUTH_METHOD_BASIC:
            default:
                servletOutput.init(outputStream);
                response.init(servletOutput, keepAlive);
                response.reset();
                response.setHeader("WWW-Authenticate",
                        "Basic realm=" + getContext().getAuthRealm());
                response.setContentType("text/html");
                response.setStatus(errorCode);
                try {
                    response.getOutputStream().println("<HTML><TITLE>Unauthorized"
                            + "</TITLE><BODY><H1>401 "
                            + "Unauthorized</H1><br>"
                            + "<pre>Unauthorized</pre>"
                            + "</BODY></HTML>");
                } catch (IOException ioex) {
                    //cat.error("Error occured while requesting user authentication");
                }
                break;
        }
    }

    /**This method creates the request object and sets all it's attributes such
     * as servlet path , servlet name,
     * method name, scheme name etc.... It also creates response object.
     * @param context the @see NusuthContext defined by the request URL.
     * @param contextPath the path to the web application context(defined by
     * the request URL) in the jndi context.
     */
    public ContainerInvocationCacheElement setContext(NusuthContext context,
                                                      String contextPath) {
        if (requestURI == null) {
            requestURI = requestLine.uri.toString();
        }
        String path = requestURI.substring(requestURI.indexOf(contextPath)
                + contextPath.length());
        if (!path.startsWith("/")) {
            path = "/" + path;
        }
        Object[] chain = null;
        chain = context.findResourceChain(path);
        if (chain == null) {
            cat.error("Cannot find servlet for path " + path
                    + ", request URI: " + requestURI);
            good = false;
            errorCode = HttpServletResponse.SC_NOT_FOUND;
            writeError();
            return null;
        }
//    String servletPath = fserv[0];
//    String servletName = fserv[1];
        String servletPath = null;
//    if (((ResourceChain)chain[1]).getServletPath().startsWith("*.")) {
        servletPath = (String) chain[0];
//    } else {
//      servletPath = ((ResourceChain)chain[1]).getServletPath();
//    }
        String servletName = ((ResourceChain) chain[1]).getServletName();
        String pathInfo
                = requestURI.substring(requestURI.indexOf(contextPath + servletPath)
                + (contextPath + servletPath).length(),
                        requestURI.length());
        ContainerInvocationCacheElement cacheElement
                = new ContainerInvocationCacheElement();
        cacheElement.context = context;
        cacheElement.chain = (ResourceChain) chain[1];
        cacheElement.contextPath = new StrBuffer(32);
        cacheElement.contextPath.append(contextPath);
        cacheElement.pathInfo = new StrBuffer(32);
        cacheElement.pathInfo.append(pathInfo);
        cacheElement.servletName = servletName;
        cacheElement.servletPath = new StrBuffer();
        cacheElement.servletPath.append(servletPath);
        setContext(cacheElement);
        return cacheElement;
    }

    public void setContext(ContainerInvocationCacheElement cacheElement) {
        this.cacheElement = cacheElement;
        NusuthServletInputStream is = retreiveInputStream();
        if (is == null) {
            //Logger.log("Internal error: undefined method", 1);
            cat.error("Internal error: undefined method");
            good = false;
            return;
        }
        request.init(is);
        servletName = cacheElement.servletName;
        keepAlive = isKeepAliveAllowed() && (!isStandAlone() ||
                (requestLine.protocol.equals(http11)
                && !headers.containsHeader(HttpConstants.CONNECTION,
                        HttpConstants.CLOSE)));
        //creates response object
        servletOutput.init(outputStream);
        response.init(servletOutput, keepAlive);
        if (requestLine.method.equals(HttpConstants.METHOD_HEAD)) {
            response.setBodySend(false);
        }
        response.setRequest(request);
        request.setSessionCreationListener(response);
        if (!isStandAlone()) {
            Cookie[] cookies = request.getCookies();
            boolean needContainerId = true;
            if (cookies != null) {
                for (int i = 0; i < cookies.length; i++) {
                    if (cookies[i].getName().equals("JCONTAINERID")) {
                        needContainerId = false;
                        break;
                    }
                }
            }
            if (needContainerId) {
                response.setContainerId(cacheElement.contextPath.toString());
            }
        }
    }

    /**This method returnes appropriate input stream depending on the request
     * parameters.
     * @return empty input stream for the requests without Conten-Length or
     * Transfer-Encoding headers or @see ChunkedServletInputStream class instance
     * with the socket intup stream inside for the requests with the chunked
     * transfer encoding or @see FixedLengthServletInputStream class instance
     * with the socket intup stream inside for the requests with the fixed
     * content length or null otherwise.
     */
    private NusuthServletInputStream retreiveInputStream() {
        int len = -1;
        try {
            len = Utils.retreiveContentLength(headers);
        } catch (IOException ioex) {
            //Logger.log(ioex, 1);
            cat.error("Bad request", ioex);
            good = false;
            usingStream = 0;
            return null;
        }
        if (!good) {
            usingStream = 0;
            return null;
        }
        if (len == -1) {
            if (requestLine.protocol.equals(http11)
                    && headers.containsHeader(HttpConstants.TRANSFER_ENCODING,
                            HttpConstants.CHUNKED)) {
                chunkedServletInput.init(inputStream);
                usingStream = 2;
                return chunkedServletInput;
            } else {
                nullServletInput.init(inputStream);
                return nullServletInput;
            }
        } else {
            contentLength = len;
            fixedServletInput.init(inputStream, len);
            usingStream = 1;
            return fixedServletInput;
        }
    }

    /**This method closes input and output streams of the socket.
     */
    protected void close() {
        //    Logger.log("Adapter - closing socket", -1);
        cat.info("Adapter - closing socket");
        try {
            /*      if (inputStream != null) {
             inputStream.close();
             }
             if (outputStream != null) {
             outputStream.close();
             }*/
            if (socket != null) {
                socket.close();
            }
        } catch (Exception ioex) {
            //Logger.log("Error occured while closing socket", ioex, 0);
            cat.warn("Error occured while closing socket", ioex);
        }
    }

    public String getHostAddress() {
        if (isStandAlone()) {
            return socket.getInetAddress().getHostAddress();
        } else {
            return headers.getHeader(REMOTE_ADDR_HEADER_NAME);
        }
    }

    public String getHostName() {
        if (isStandAlone()) {
            return socket.getInetAddress().getHostName();
        } else {
            return headers.getHeader(REMOTE_ADDR_HEADER_NAME);
        }
    }

    public void cleanup() {
        partialCleanup();
        super.cleanup();
        inputStream.cleanup();
        outputStream = null;
        keepAliveAllowed = false;
    }

    public void partialCleanup() {
        if (successfullyParsed) {
            if (catPool.containsKey(hostHeader)) {
                AccessLogWrapper wrapper = (AccessLogWrapper) catPool.get(hostHeader);
                AccessLogger category = wrapper.getCategory();
                switch (wrapper.getLogType()) {

                    case AccessLogWrapper.TYPE_COMMON:
                        createCommonLog(wrapper.isResolve());
                        logMessage.append(systemCRLF);
                        category.log(logMessage);
                        break;

                    case AccessLogWrapper.TYPE_EXTENDED:
                        createCommonLog(wrapper.isResolve());
                        if (!headers.containsHeader(REFERER_HEADER_NAME)) {
                            logMessage.append(chars4log[3]);
                        } else {
                            logMessage.append(chars4log[1]);
                            headers.appendHeaderValue(REFERER_HEADER_NAME, logMessage);
                            logMessage.append('\"');
                        }
                        if (!headers.containsHeader(AGENT_HEADER_NAME)) {
                            logMessage.append(chars4log[3]);
                        } else {
                            logMessage.append(chars4log[1]);
                            headers.appendHeaderValue(AGENT_HEADER_NAME, logMessage);
                            logMessage.append('\"');
                        }
                        logMessage.append(systemCRLF);
                        category.log(logMessage);
                        break;

                    default:
                        break;
                }
            }
        }
        successfullyParsed = false;
        logMessage.clear();
        reqTime = null;
        contentLength = -1;
        host = null;
        errorCode = HttpServletResponse.SC_OK;
        hostHeader.clear();
        hostId.clear();
        hostWithUri.clear();
        request.cleanup();
        response.cleanup();
        headers.clear();
        scPath = null;
        requestURI = null;
        parameters.clear();
        switch (usingStream) {
            case 1:
                fixedServletInput.cleanup();
                break;
            case 2:
                chunkedServletInput.cleanup();
                break;
            default:
                break;
        }
        servletOutput.cleanup();
        inputStream.partialCleanup();
        requestLine.clear();
        serverHost = null;
        serverPort = -1;
    }

    public String getProtocol() {
        return requestLine.protocol.toString();
    }

    public String getScheme() {
        if (isSecure) {
            return "https";
        } else {
            return "http";
        }
    }

    public String getMethod() {
        if (requestLine.method.equals(HttpConstants.METHOD_GET)) {
            return METHOD_GET;
        } else if (requestLine.method.equals(HttpConstants.METHOD_POST)) {
            return METHOD_POST;
        } else {
            return requestLine.method.toString();
        }
    }

    public String getQueryString(String encoding) {
        if (requestLine.queryString.length() != 0) {
            try {
                return requestLine.queryString.toString(encoding);
            } catch (UnsupportedEncodingException e) {
                return requestLine.queryString.toString();
            }
        } else {
            return null;
        }
    }

    public NusuthContext getContext() {
        return cacheElement.context;
    }

    public String getHostHeader() {
        return headers.getHeader("Host");
    }

    public String getContextPath() {
        return cacheElement.contextPath.toString();
    }

    public String getServletPath() {
        if (cacheElement.servletPath.length() != 0) {
            return cacheElement.servletPath.toString();
        } else {
            return "";
        }
    }

    public String getPathInfo() {
        if (cacheElement.pathInfo.length() != 0) {
            return cacheElement.pathInfo.toString();
        } else {
            return null;
        }
    }

    public int getContentLength() {
        return contentLength;
    }

    public Hashtable getParameters(String encoding) {
        if (requestLine.queryString.length() != 0) {
            try {
                parameters = Utils.parseQueryString(requestLine.queryString.toString(encoding));
            } catch (IllegalArgumentException iae) {
                cat.warn("Cannot parse query string " + requestLine.queryString);
            } catch (UnsupportedEncodingException uee) {
                cat.warn("Cannot decode query string " + requestLine.queryString);
            }
        }
        ServletInputStream is = request.getInputStream();
        Hashtable params = new Hashtable();
        if (getMethod().equals("POST") &&
                headers.containsHeader(HttpConstants.CONTENT_TYPE,
                        HttpConstants.WWW_FORM)) {
            try {
                Hashtable formprs
                        = parsePostData(Utils.retreiveContentLength(headers), is,
                                encoding);
                Enumeration enum = formprs.keys();
                String key;
                String[] urlValues;
                String[] postValues;
                String[] resValues;
                while (enum.hasMoreElements()) {
                    key = (String) enum.nextElement();
                    if (params.get(key) == null) {
                        params.put(key, formprs.get(key));
                    } else {
                        postValues = (String[]) formprs.get(key);
                        urlValues = (String[]) params.get(key);
                        resValues = new String[postValues.length + urlValues.length];
                        for (int i = 0; i < urlValues.length; i++) {
                            resValues[i] = urlValues[i];
                        }
                        for (int i = 0; i < postValues.length; i++) {
                            resValues[urlValues.length + i] = postValues[i];
                        }
                        params.put(key, resValues);
                    }
                }
                addParameters(params);
            } catch (IOException ioex) {
            }
        }
        return parameters;
    }

    protected void addParameters(Hashtable newParams) {
        Enumeration enum = newParams.keys();
        String[] oldParamSet;
        String[] newParamSet;
        String[] concatParamSet;
        String key;
        while (enum.hasMoreElements()) {
            key = (String) enum.nextElement();
            oldParamSet = (String[]) parameters.get(key);
            if (oldParamSet == null) {
                concatParamSet = (String[]) newParams.get(key);
            } else {
                newParamSet = (String[]) newParams.get(key);
                concatParamSet = new String[oldParamSet.length + newParamSet.length];
                System.arraycopy(newParamSet, 0, concatParamSet, 0, newParamSet.length);
                System.arraycopy(oldParamSet, 0, concatParamSet, newParamSet.length,
                        oldParamSet.length);
            }
            parameters.put(key, concatParamSet);
        }
    }

    /**
     * This method parse posted data.
     * @param len Length of data.
     * @param in InputStream with data.
     * @param encoding Character encoding to use.
     * @return Hashatable with parameters.
     */
    private Hashtable parsePostData(int len, ServletInputStream in,
                                    String encoding) {
        if (len <= 0)
            return new Hashtable();
        if (in == null)
            throw new IllegalArgumentException();
        byte postedBytes[] = new byte[len];
        try {
            int offset = 0;
            do {
                int inputLen = in.read(postedBytes, offset, len - offset);
                if (inputLen <= 0) {
                    String msg = lStrings.getString("err.io.short_read");
                    throw new IllegalArgumentException(msg);
                }
                offset += inputLen;
            } while (len - offset > 0);
        } catch (IOException e) {
            throw new IllegalArgumentException(e.getMessage());
        }
        try {
            return Utils.parseAndDecodeQuery(postedBytes, encoding);
        } catch (UnsupportedEncodingException e) {
            throw new IllegalArgumentException(e.getMessage());
        }
    }

    public String getServerHost() {
        if (serverHost == null) {
            retrieveServerParameters();
        }
        return serverHost;
    }

    public int getServerPort() {
        if (serverHost == null) {
            retrieveServerParameters();
        }
        return serverPort;
    }

    public void sendRedirect(String location) throws IOException {
        try {
            servletOutput.init(outputStream);
            response.init(servletOutput, keepAlive);
            response.sendRedirect(location);
        } catch (IOException ioex) {
            //Logger.log("Error occured while writing error", ioex, 1);
            cat.error("Error occured while redirecting request");
        }
        //    response.sendRedirect(location);
    }

    public void sendRedirect(String scheme, int port) {
        String uri = (requestURI == null) ? requestLine.uri.toString() : requestURI;
        String query = requestLine.queryString.toString();
        query = (query.length() == 0) ? query : ("?" + query);
        try {
            servletOutput.init(outputStream);
            response.init(servletOutput, false);
            response.sendRedirect(scheme + "://" + getServerHost() + ":" + port + uri + query);
        } catch (IOException e) {
            cat.error("Error occured while redirecting request");
        }
    }

    public void processUnavailable(int seconds, String message) {
        response.reset();
        response.setStatus(503);
        if (seconds != -1)
            response.setIntHeader("Retry-After", seconds);
        ServletOutputStream out = response.getOutputStream();
        try {
            out.println("<H1> 503 " + response.getErrorDescription(503) + "</H1>");
            out.println("<BR>");
            if (seconds != -1)
                out.println("Service unavailable for " + seconds + " seconds");
            else
                out.println("Service unavailable permanently");
            out.println("<BR>");
            out.println(message);
        } catch (IOException ex) {
        }
    }

    private void retrieveServerParameters() {
        String hostHeader = headers.getHeader("Host");
        if (hostHeader != null) {
            int scIndex = hostHeader.indexOf(':');
            serverHost = scIndex == -1 ? hostHeader : hostHeader.substring(0, scIndex);
            try {
                serverPort = scIndex == -1 ? isSecure ? 443 : 80 : Integer.parseInt(hostHeader.substring(scIndex + 1));
            } catch (Exception ex) {
                cat.warn(ex);
            }
        } else {
            serverHost = super.getServerHost() == null ? headers.getHeader("Server-Host") : super.getServerHost();
            serverPort = super.getServerPort() == -1 ? headers.getIntHeader("Server-Port") : super.getServerPort();
        }
    }

    public void appendHost(char[] name, StrBuffer target) {
        headers.appendHeaderValue(name, target);
        //    hostHeader = target.toString();
    }

    public static void addCategory(StrBuffer host, AccessLogWrapper wrapper) {
        catPool.put(host, wrapper);
    }

    /**
     * This method remove Category from pool.
     * @param host Key for category
     */
    public static void removeCategory(StrBuffer host) {
        catPool.remove(host);
    }

    public StrBuffer getSecretKeyCandidate() {
        return getRequestURI();
    }

    /**
     * This method return requested host.
     * @return Requested host or "*" if request not contains Host header.
     */
    public String getHost() {
        headers.appendHeaderValue(HOST_HEADER_NAME, hostId);
        hostId.cutToChar(':', false);
        if (hostId.length() != 0) {
            if (!allHosts.contains(hostId)) {
                hostId.clear();
                hostId.append('*');
                ;
            }
        } else {
            hostId.append('*');
        }
        return hostId.toString();
    }


    /**
     * This method return StrBuffer that contains information about requestded
     * host and uri.
     * @return Host with URI.
     */
    public StrBuffer getHostWithUri() {
        hostWithUri.clear();
        headers.appendHeaderValue(HOST_HEADER_NAME, hostWithUri);
        hostWithUri.cutToChar(':', false);
        if (hostWithUri.length() != 0) {
            if (!allHosts.contains(hostWithUri)) {
                hostWithUri.clear();
                hostWithUri.append('*');
                ;
            }
        } else {
            hostWithUri.append('*');
        }
        hostHeader.append(hostWithUri);
        hostWithUri.append(getRequestURI());
        return hostWithUri;
    }

    public static void setAllHosts(HashSet hosts) {
        allHosts = hosts;
    }

    public void writeDeny() {
        servletOutput.init(outputStream);
        response.init(servletOutput, false);
        try {
            response.sendError(403, "You do not have permission to access this server");
        } catch (IOException ioex) {
            cat.debug("Error occured while sending deny", ioex);
        }
    }

    private void createCommonLog(boolean resolve) {
        logMessage.append((resolve) ? getHostName() : getHostAddress());
        logMessage.append(chars4log[0]);
        logMessage.append(reqTime);
        logMessage.append(chars4log[1]);
        logMessage.append(requestLine.method);
        logMessage.append(' ');
        logMessage.append(requestLine.uri);
        if (requestLine.queryString.length() > 0) {
            logMessage.append('?');
            logMessage.append(requestLine.queryString.toString());
        }
        logMessage.append(' ');
        logMessage.append(requestLine.protocol);
        logMessage.append(chars4log[2]);
        logMessage.appendInt(response.getStatusCode());
        logMessage.append(' ');
        logMessage.appendInt(response.getNumberOfBytesTransfered());
    }

    // added by igork

    public ResourceSecurityRecord getResourceSecurityRecord() {
        StrBuffer resourcePath = new StrBuffer(cacheElement.servletPath.length() + 1 + cacheElement.pathInfo.length());
        resourcePath.append(cacheElement.servletPath);
        if (cacheElement.servletPath.length() > 0 && cacheElement.pathInfo.length() > 0 && !cacheElement.pathInfo.startsWith(slash))
            resourcePath.append('/');
        resourcePath.append(cacheElement.pathInfo);
        if (resourcePath.length() == 0)
            resourcePath.append('/');
        return new ResourceSecurityRecord(resourcePath, requestLine.method);
    }

    public void saveRequest() {
        NusuthSession session = (NusuthSession) request.getSession(true);
        String queryStringToSave = request.getQueryString() == null || request.getQueryString().length() == 0 ? "" : '?' + request.getQueryString();
        String urlToSave = (request.isSecure() ? "https://" : "http://") + getServerHost() + ':' + getServerPort() + getRequestURI() + queryStringToSave;
        session.saveUrl(urlToSave);
    }

    public void restoreRequest() {
        NusuthSession session = (NusuthSession) request.getSession(true);
        String url = session.getSavedUrl();
        if (url != null) {
            try {
                sendRedirect(url);
            } catch (IOException ioex) {
                cat.debug("Couldn't redirect to original URL after login", ioex);
            }
            /*request = state.savedRequest;
             requestLine = state.savedRequestLine;
             requestURI = null;
             response.setHeader("Location", requestLine.uri.toString());
             setContext(state.savedContext, state.savedContextPath);*/
            session.clearSavedUrl();
        }
    }

    /**This method gets the socket picket out for the request processing.
     */
    public Socket getSocket() {
        return socket;
    }
}

