/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import sun.tools.javac.Main;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class JavacJspCompiler extends JspCompiler {

    public JavacJspCompiler() {
        super();
    }

    public boolean compile(String source) {
        Main sunCompiler = new Main(errorOut, "nusuth");
        String[] params = {"-encoding", encoding, "-classpath", classPath, "-d", outputDir, source};
        return sunCompiler.compile(params);
    }
}

