/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import java.util.Enumeration;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class JspAction extends JspAttributeContainer {

    boolean body = true;

    public JspAction() {
        super();
    }

    boolean hasBody() {
        return body;
    }

    void setHasBody(boolean body) {
        this.body = body;
    }
}

