/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import java.util.Enumeration;
import java.util.Hashtable;
import javax.servlet.jsp.JspException;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class JspAttributeContainer {

    protected Hashtable attributes;

    public JspAttributeContainer() {
        attributes = new Hashtable();
    }

    public Enumeration getAttributeNames() {
        return attributes.keys();
    }

    public String getAttribute(String name) {
        return (String) attributes.get(name);
    }

    public void putAttribute(String name, String value) throws JspException {
        if (attributes.get(name) != null) {
            throw new JspException("Parser error: duplicate declaration of '" + name + "' attribute");
        }
        attributes.put(name, value);
    }
}

