/* Generated by VDGG */

package com.azoft.nusuth.jsp;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class JspConstants {
    public final static String DIRECTIVE_PAGE = "page";
    public final static String DIRECTIVE_INCLUDE = "include";
    public final static String DIRECTIVE_TAGLIB = "taglib";

    public final static String ATTRIBUTE_LANGUAGE = "language";
    public final static String ATTRIBUTE_EXTENDS = "extends";
    public final static String ATTRIBUTE_IMPORT = "import";
    public final static String ATTRIBUTE_SESSION = "session";
    public final static String ATTRIBUTE_BUFFER = "buffer";
    public final static String ATTRIBUTE_AUTOFLUSH = "autoFlush";
    public final static String ATTRIBUTE_ISTHREADSAFE = "isThreadSafe";
    public final static String ATTRIBUTE_INFO = "info";
    public final static String ATTRIBUTE_ERRORPAGE = "errorPage";
    public final static String ATTRIBUTE_ISERRORPAGE = "isErrorPage";
    public final static String ATTRIBUTE_CONTENTTYPE = "contentType";
    public final static String ATTRIBUTE_FILE = "file";
    public final static String ATTRIBUTE_URI = "uri";
    public final static String ATTRIBUTE_PREFIX = "prefix";
}

