/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import java.io.*;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
abstract public class JspCompiler {

    protected String classPath = "";
    protected String encoding = "ISO8859-1";
    protected String outputDir = ".";
    protected OutputStream errorOut;

    public void setClassPath(String classPath) {
        this.classPath = classPath;
    }

    public void addClassPath(String classPath) {
        classPath += (File.pathSeparator + classPath);
    }

    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public void setErrorOut(OutputStream errorOut) {
        this.errorOut = errorOut;
    }

    public abstract boolean compile(String source);
}

