/* Generated by VDGG */

package com.azoft.nusuth.jsp;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class JspDirective extends JspAttributeContainer {

    public JspDirective() {
        super();
    }
}

