/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import java.io.*;
import java.util.*;
import javax.servlet.jsp.JspException;
import javax.servlet.jsp.tagext.TagInfo;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class JspFileReader {
    private BufferedReader reader;
    private String encoding;
    private char[] buf;
    private int curPos = 0;
    private int endPos = -1;
    private ReaderInclusion previous;
    private Stack includes = new Stack();
    private int currentRow = 1;
    private int currentColumn = 1;
    private JspParser parser;

    public JspFileReader(InputStream stream, String encoding) throws UnsupportedEncodingException, IOException {
        this.encoding = encoding;
        reader = new BufferedReader(new InputStreamReader(stream, encoding));
        buf = new char[1024];
        refillBuffer();
        if (endPos == -1) {
            throw new IOException("Stream is empty");
        }
    }

    public JspFileReader(InputStream stream, String encoding, JspParser parser) throws UnsupportedEncodingException, IOException {
        this(stream, encoding);
        this.parser = parser;
    }

    public boolean readUntilTag(StringBuffer sb, boolean change) throws IOException {
        char[] tf = {'<'};
        return findFirstOf(tf, sb, change) == 0;
    }

    public boolean readUntil(String mark, StringBuffer sb, boolean change) throws IOException {
        char[] markChars = mark.toCharArray();
        char[] matchingChars = new char[markChars.length];
        int matchCount = 0;
        int tmp;
        while (matchCount < markChars.length) {
            if (curPos > endPos) {
                refillBuffer();
            }
            if (endPos == -1) {
                return false;
            }
            if (buf[curPos] == markChars[matchCount]) {
                matchingChars[matchCount] = buf[curPos];
                matchCount++;
            } else {
                if (matchCount == 0) {
                    if (sb != null) {
                        internalAppend(sb, buf[curPos], change);
                    }
                } else {
                    tmp = 0;
                    matchingChars[matchCount] = buf[curPos];
                    if (sb != null) {
                        internalAppend(sb, matchingChars[0], change);
                    }
                    for (int i = 0; i < matchCount; i++) {
                        if (isStartsWith(markChars, matchingChars, i + 1, matchCount - i)) {
                            tmp = i;
                            break;
                        } else {
                            if (sb != null) {
                                internalAppend(sb, matchingChars[i + 1], change);
                            }
                        }
                    }
                    if (tmp > 0) {
                        for (int i = 0; i < matchCount - tmp; i++) {
                            matchingChars[i] = matchingChars[i + tmp];
                        }
                        matchCount -= tmp;
                    } else {
                        matchCount = 0;
                    }
                }
            }
            if (buf[curPos] == '\n') {
                currentRow++;
                currentColumn = 0;
            }
            currentColumn++;
            curPos++;
        }
        return true;
    }

    public boolean skipUntil(String mark, boolean change) throws IOException {
        return readUntil(mark, null, change);
    }

    public JspDirective parseDirective() throws IOException, JspException {
        JspDirective result = new JspDirective();
        String name;
        boolean cont;
        skipSpaces();
        char[] nameStuff = {'=', '>', ' ', '\r', '\n', '\t'};
        char[] valueStuff = {'\"', '\''};
        StringBuffer sb = new StringBuffer();
        int tmp;
        char quot;
        char[] stuff = new char[1];
        while (true) {
            if (curPos > endPos) {
                refillBuffer();
            }
            sb.setLength(0);
            skipSpaces();
            switch (findFirstOf(nameStuff, sb, false)) {
                case -1:
                    throw new JspException("Close tag not found");
                case 0:
                    name = sb.toString();
                    skipSpaces();
                    if (buf[curPos] != '\'' && buf[curPos] != '\"') {
                        throw new JspException("Expected \" not found for " + name + " attribute");
                    }
                    quot = buf[curPos];
                    currentColumn++;
                    curPos++;
                    sb.setLength(0);
                    cont = true;
                    stuff[0] = quot;
                    while (cont) {
//            int num = findFirstOf(valueStuff, sb, false);
                        int num = findFirstOf(stuff, sb, false);
                        switch (num) {
                            case -1:
                                throw new JspException(name + " attribute value end not found");
                            default:
                                tmp = sb.length() - 1;
                                while (tmp >= 0 && sb.charAt(tmp--) == '\\') ;
                                cont = (sb.length() - tmp) % 2 != 0;
//Added by skilz...
                                if ((sb.length() % 2 == 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                    cont = false;
                                } else {
                                    if ((sb.length() % 2 != 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                        cont = true;
                                    }
                                }
                                if (sb.length() == 0) {
                                    cont = false;
                                }
//
                                if (cont) {
//                  sb.append('\"');
//                  sb.append(valueStuff[num]);
                                    sb.append(quot);
                                }
                                break;
                        }
                    }
//********************
                    if (curPos > endPos) {
                        refillBuffer();
                    }
//********************
                    if (buf[curPos] != ' ' && buf[curPos] != '\r' && buf[curPos] != '\n' && buf[curPos] != '\t' &&
                            buf[curPos] != '%') {
                        throw new JspException("Unexpected symbol " + buf[curPos] + " found after " + name + " attribute value");
                    }
                    result.putAttribute(name, sb.toString());
                    break;
                case 1:
                    if (sb.length() == 1 && sb.charAt(0) == '%') {
                        return result;
                    }
                    if (sb.length() > 0) {
                        throw new JspException("Unrecognized input found: " + sb.toString());
                    } else {
                        throw new JspException("Unexpected symbol > found");
                    }
                default:
                    name = sb.toString();
                    skipSpaces();
                    if (buf[curPos] != '=') {
                        throw new JspException("Expected = not found for " + name + " attribute");
                    }
                    currentColumn++;
                    curPos++;
                    skipSpaces();
                    if (buf[curPos] != '\'' && buf[curPos] != '\"') {
                        throw new JspException("Expected \" not found for " + name + " attribute");
                    }
                    quot = buf[curPos];
                    if (buf[curPos] == '\n') {
                        currentRow++;
                        currentColumn = 0;
                    }
                    currentColumn++;
                    curPos++;
                    if (curPos > endPos) {
                        refillBuffer();
                    }
                    sb.setLength(0);
                    cont = true;
                    stuff[0] = quot;
                    while (cont) {
//            int num = findFirstOf(valueStuff, sb, false);
                        int num = findFirstOf(stuff, sb, false);
                        switch (num) {
                            case -1:
                                throw new JspException(name + " attribute value end not found");
                            default:
                                tmp = sb.length() - 1;
                                while (tmp >= 0 && sb.charAt(tmp--) == '\\') ;
                                cont = (sb.length() - tmp) % 2 != 0;
//Added by skilz...
                                if ((sb.length() % 2 == 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                    cont = false;
                                } else {
                                    if ((sb.length() % 2 != 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                        cont = true;
                                    }
                                }
                                if (sb.length() == 0) {
                                    cont = false;
                                }
//
                                if (cont) {
//                  sb.append('\"');
//                  sb.append(valueStuff[num]);
                                    sb.append(quot);
                                }
                                break;
                        }
                    }
//********************
                    if (curPos > endPos) {
                        refillBuffer();
                    }
//********************
                    if (buf[curPos] != ' ' && buf[curPos] != '\r' && buf[curPos] != '\n' && buf[curPos] != '\t' &&
                            buf[curPos] != '%') {
                        throw new JspException("Unexpected symbol " + buf[curPos] + " found after " + name + " attribute value");
                    }
                    result.putAttribute(name, sb.toString());
                    break;
            }
        }
    }

    public JspAction parseAction() throws IOException, JspException {
        JspAction result = new JspAction();
        String name;
        boolean cont;
        skipSpaces();
        char[] nameStuff = {'=', '>', ' ', '\r', '\n', '\t'};
        char[] valueStuff = {'\"', '\''};
        StringBuffer sb = new StringBuffer();
        int tmp;
        char quot;
        char[] stuff = new char[1];
        boolean bodyfound = false;
        while (!bodyfound) {
            if (curPos > endPos) {
                refillBuffer();
            }
            sb.setLength(0);
            skipSpaces();
            switch (findFirstOf(nameStuff, sb, false)) {
                case -1:
                    throw new JspException("Close tag not found");
                case 0:
                    name = sb.toString();
                    skipSpaces();
                    if (buf[curPos] != '\'' && buf[curPos] != '\"') {
                        throw new JspException("Expected \" not found for " + name + " attribute");
                    }
                    quot = buf[curPos];
                    if (buf[curPos] == '\n') {
                        currentRow++;
                        currentColumn = 0;
                    }
                    currentColumn++;
                    curPos++;
                    sb.setLength(0);
                    cont = true;
                    stuff[0] = quot;
                    while (cont) {
//            int num = findFirstOf(valueStuff, sb, false);
                        int num = findFirstOf(stuff, sb, false);
                        switch (num) {
                            case -1:
                                throw new JspException(name + " attribute value end not found");
                            default:
                                tmp = sb.length() - 1;
                                while (tmp >= 0 && sb.charAt(tmp--) == '\\') ;
                                cont = (sb.length() - tmp) % 2 != 0;
//Added by skilz...
                                if ((sb.length() % 2 == 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                    cont = false;
                                } else {
                                    if ((sb.length() % 2 != 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                        cont = true;
                                    }
                                }
                                if (sb.length() == 0) {
                                    cont = false;
                                }
//
                                if (cont) {
//                  sb.append('\"');
//                  sb.append(valueStuff[num]);
                                    sb.append(quot);
                                }
                                break;
                        }
                    }
//********************
                    if (curPos > endPos) {
                        refillBuffer();
                    }
//********************
                    if (buf[curPos] != ' ' && buf[curPos] != '\r' && buf[curPos] != '\n' && buf[curPos] != '\t' &&
                            buf[curPos] != '>' && buf[curPos] != '/') {
                        throw new JspException("Unexpected symbol " + buf[curPos] + " found after " + name + " attribute value");
                    }
                    result.putAttribute(name, sb.toString());
                    break;
                case 1:
                    if (sb.length() == 0) {
                        bodyfound = true;
                    } else if (sb.length() == 1 && sb.charAt(0) == '/') {
                        result.setHasBody(false);
                        return result;
                    } else {
                        throw new JspException("Unrecognized input found: " + sb.toString());
                    }
                    break;
                default:
                    name = sb.toString();
                    skipSpaces();
                    if (buf[curPos] != '=') {
                        throw new JspException("Expected = not found for " + name + " attribute");
                    }
                    if (buf[curPos] == '\n') {
                        currentRow++;
                        currentColumn = 0;
                    }
                    currentColumn++;
                    curPos++;
                    skipSpaces();
                    if (buf[curPos] != '\'' && buf[curPos] != '\"') {
                        throw new JspException("Expected \" not found for " + name + " attribute");
                    }
                    quot = buf[curPos];
                    if (buf[curPos] == '\n') {
                        currentRow++;
                        currentColumn = 0;
                    }
                    currentColumn++;
                    curPos++;
                    if (curPos > endPos) {
                        refillBuffer();
                    }
                    sb.setLength(0);
                    cont = true;
                    stuff[0] = quot;
                    while (cont) {
//            int num = findFirstOf(valueStuff, sb, false);
                        int num = findFirstOf(stuff, sb, false);
                        switch (num) {
                            case -1:
                                throw new JspException(name + " attribute value end not found");
                            default:
                                tmp = sb.length() - 1;
                                while (tmp >= 0 && sb.charAt(tmp--) == '\\') ;
                                cont = (sb.length() - tmp) % 2 != 0;
//Added by skilz...
                                if ((sb.length() % 2 == 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                    cont = false;
                                } else {
                                    if ((sb.length() % 2 != 0) && (isOnlyChar(sb.toString(), '\\'))) {
                                        cont = true;
                                    }
                                }
                                if (sb.length() == 0) {
                                    cont = false;
                                }
//
                                if (cont) {
//                  sb.append('\"');
//                  sb.append(valueStuff[num]);
                                    sb.append(quot);
                                }
                                break;
                        }
                    }
//********************
                    if (curPos > endPos) {
                        refillBuffer();
                    }
//********************
                    if (buf[curPos] != ' ' && buf[curPos] != '\r' && buf[curPos] != '\n' && buf[curPos] != '\t' &&
                            buf[curPos] != '/') {
                        throw new JspException("Unexpected symbol " + buf[curPos] + " found after " + name + " attribute value");
                    }
                    result.putAttribute(name, sb.toString());
                    break;
            }
        }
        return result;
    }

    public JspScript parseScript() throws IOException, JspException {
        StringBuffer sb = new StringBuffer();
        JspScript result = new JspScript();
        skipSpaces();
        if (!readUntil("%>", sb, false)) {
            throw new JspException("End of script tag not found");
        }
        result.setScript(sb.toString());
        return result;
    }

    public void skipSpaces() throws IOException {
        if (curPos > endPos) {
            refillBuffer();
        }
        while (buf[curPos] == ' ' || buf[curPos] == '\r' || buf[curPos] == '\n' || buf[curPos] == '\t') {
            if (buf[curPos] == '\n') {
                currentRow++;
                currentColumn = 0;
            }
            currentColumn++;
            curPos++;
            if (curPos > endPos) {
                refillBuffer();
            }
            if (curPos > endPos) {
                throw new EOFException("Cannot skip spaces - end of file found");
            }
        }
    }

    public String readToken() throws IOException {
        skipSpaces();
        StringBuffer sb = new StringBuffer();
        char[] stuff = {' ', '\r', '\n', '\t'};
        findFirstOf(stuff, sb, false);
        return sb.toString();
    }

    public String getEncoding() {
        return encoding;
    }

    private void refillBuffer() throws IOException {
        curPos = 0;
        endPos = -1;
        int readed;
        while (reader.ready() && (readed = reader.read(buf, endPos + 1, buf.length - endPos - 1)) >= 0 &&
                endPos < buf.length - 1) {
            endPos += readed;
        }
        if (endPos < 0 && previous != null) {
            buf = previous.buf;
            reader = previous.reader;
            curPos = previous.curPos;
            endPos = previous.endPos;
            currentRow = previous.currentRow;
            currentColumn = previous.currentColumn;
            previous = previous.previous;
            parser.endOfInclude();
            if (curPos > endPos) {
                refillBuffer();
            }
        }
    }

    private boolean isStartsWith(char[] cnst, char[] dnm, int off, int len) {
        for (int i = 0; i < len; i++) {
            if (cnst[i] != dnm[i + off]) {
                return false;
            }
        }
        return true;
    }

    public int findFirstOf(char[] toFind, StringBuffer sb, boolean change) throws IOException {
        int matchPlace = -1;
        while (matchPlace == -1) {
            if (curPos > endPos) {
                refillBuffer();
            }
            if (endPos == -1) {
                break;
            }
            for (int i = 0; i < toFind.length; i++) {
                if (buf[curPos] == toFind[i]) {
                    if (buf[curPos] == '\n') {
                        currentRow++;
                        currentColumn = 0;
                    }
                    currentColumn++;
                    curPos++;
                    return i;
                }
            }
            internalAppend(sb, buf[curPos], change);
            if (buf[curPos] == '\n') {
                currentRow++;
                currentColumn = 0;
            }
            currentColumn++;
            curPos++;
        }
        return matchPlace;
    }

    void includeStream(InputStream stream) throws UnsupportedEncodingException {
        ReaderInclusion incl = new ReaderInclusion();
        incl.buf = buf;
        incl.reader = reader;
        incl.previous = previous;
        incl.curPos = curPos;
        incl.endPos = endPos;
        incl.currentRow = currentRow;
        incl.currentColumn = incl.currentColumn;
        reader = new BufferedReader(new InputStreamReader(stream, encoding));
        buf = new char[1024];
        curPos = 0;
        endPos = -1;
        currentRow = 1;
        currentColumn = 1;
        previous = incl;
    }

    char read() throws IOException {
        if (curPos > endPos) {
            refillBuffer();
        }
        if (endPos == -1) {
            throw new IOException("End of jsp reached");
        }
        if (buf[curPos] == '\n') {
            currentRow++;
            currentColumn = 0;
        }
        currentColumn++;
        return buf[curPos++];
    }

    int findFirstOf(char[][] toFind, StringBuffer sb, boolean change) throws IOException {
        int matchPlace = -1;
        int[] matches = new int[toFind.length];
        for (int i = 0; i < matches.length; i++) {
            matches[i] = 0;
        }
        while (matchPlace == -1) {
            if (curPos > endPos) {
                refillBuffer();
            }
            if (endPos == -1) {
                break;
            }
            for (int i = 0; i < toFind.length; i++) {
                if (buf[curPos] == toFind[i][matches[i]]) {
                    matches[i]++;
                } else {
                    matches[i] = (buf[curPos] == toFind[i][0]) ? 1 : 0;
                }
                if (toFind[i].length == matches[i]) {
                    if (buf[curPos] == '\n') {
                        currentRow++;
                        currentColumn = 0;
                    }
                    currentColumn++;
                    curPos++;
                    return i;
                }
            }
            internalAppend(sb, buf[curPos], change);
            if (buf[curPos] == '\n') {
                currentRow++;
                currentColumn = 0;
            }
            currentColumn++;
            curPos++;
        }
        return matchPlace;
    }

    private void internalAppend(StringBuffer sb, char c, boolean change) {
        if (change) {
            switch (c) {
                case '\r':
                    sb.append("\\r");
                    break;
                case '\"':
                    sb.append("\\\"");
                    break;
                case '\'':
                    sb.append("\\\'");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                default:
                    sb.append(c);
                    break;
            }
        } else {
            sb.append(c);
        }
    }

    public int getCurrentRow() {
        return currentRow;
    }

    public int getCurrentColumn() {
        return currentColumn;
    }

    private boolean isOnlyChar(String str, char ch) {
        boolean b = true;
        for (int i = 0; i < str.length(); i++) {
            if (str.charAt(i) != ch) {
                b = false;
                break;
            }
            if (!b) {
                break;
            }
        }
        return b;
    }

    class ReaderInclusion {
        BufferedReader reader;
        char[] buf;
        int curPos = 0;
        int endPos = 0;
        int currentRow = 1;
        int currentColumn = 1;
        ReaderInclusion previous;
    }
}

