/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import com.azoft.nusuth.container.InvocationCacheElement;


public class JspInvocationCacheElement extends InvocationCacheElement {

    public java.io.File realFile;

}
