/* Generated by VDGG */

package com.azoft.nusuth.jsp;

public class JspScript {

    private String script;

    public JspScript() {
    }

    public String getScript() {
        return script;
    }

    public void setScript(String script) {
        this.script = script;
    }
}

