/* Generated by Together */

package com.azoft.nusuth.jsp;

import javax.servlet.jsp.*;
import javax.servlet.*;
//import com.azoft.nusuth.util.Logger;
import java.io.IOException;
import java.util.*;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthJspFactory extends JspFactory {

    private static NusuthJspEngineInfo info;
    private static Stack contexts;
    private org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.jsp");

    static {
        info = new NusuthJspEngineInfo();
        contexts = new Stack();
    }

    public NusuthJspFactory() {
        super();
    }

    public JspEngineInfo getEngineInfo() {
        return info;
    }

    public PageContext getPageContext(Servlet servlet, ServletRequest request, ServletResponse response,
                                      String errorPageURL, boolean needsSession, int bufferSize, boolean autoFlush) {
        PageContext pc = null;
        synchronized (contexts) {
            if (contexts.empty()) {
                pc = new NusuthPageContext();
            } else {
                pc = (PageContext) contexts.pop();
            }
        }
        try {
            pc.initialize(servlet, request, response, errorPageURL, needsSession, bufferSize, autoFlush);
        } catch (Exception ex) {
            //Logger.log(ex, 1);
            cat.error("Error initialize pagecontext", ex);
        }
        return pc;
    }

    public void releasePageContext(PageContext context) {
        context.release();
        if (contexts.size() < 50) {
            synchronized (contexts) {
                contexts.push(context);
            }
        }
    }
}
