/* Generated by VDGG */

package com.azoft.nusuth.jsp;

//import com.azoft.nusuth.util.Logger;

import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthPageContext extends PageContext {
    private boolean initialized = false;
//  private Hashtable pageAttrs = new Hashtable();
    private Stack outs = new Stack();
//Added by skilz
    private JspWriter writer = null;
    private ServletContext application = null;
    private ServletConfig config = null;
    private Servlet page = null;
    private ServletRequest request = null;
    private ServletResponse response = null;
    private HttpSession session = null;
    private Hashtable pageContext = null;
    private Exception exception = null;
    private String errorPage = null;
    private org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.jsp");


    public NusuthPageContext() {
        super();
        writer = new NusuthJspWriter();
        pageContext = new Hashtable();
    }

//****************************************************
    public void handlePageException(Throwable t) throws ServletException, IOException {
        if (errorPage == null) {
/*
//      pageAttrs.put(EXCEPTION, ex);
      exception = ex;
      //Logger.log(ex, 1);
      cat.error("page exception, intended to internal handling", ex);
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      ex.printStackTrace(ps);
      ps.flush();
//      HttpServletResponse response = (HttpServletResponse)pageAttrs.get(RESPONSE);
      if (response.isCommitted()){
        response.getOutputStream().write("<pre>".getBytes());
        response.getOutputStream().write(baos.toByteArray());
        response.getOutputStream().write("</pre>".getBytes());
      } else {
        ((HttpServletResponse)response).sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, baos.toString());
      }
*/
            throw new ServletException(t.getMessage(), t);
        } else {
//      HttpServletRequest request = (HttpServletRequest)pageAttrs.get(REQUEST);
            request.setAttribute("javax.servlet.jsp.JspException", t);
            if (request.getAttribute("javax.servlet.include.request_uri") == null)
                forward(errorPage);
            else
                include(errorPage);
        }
    }

    public Object findAttribute(String name) {
        Object result = null;
//    Hashtable ht = (Hashtable)pageAttrs.get(PAGECONTEXT);
        if (pageContext != null) {
            result = pageContext.get(name);
        }
        if (result == null) {
//      ServletRequest sr = (ServletRequest)pageAttrs.get(REQUEST);
            if (request != null) {
                result = request.getAttribute(name);
            }
        }
        if (result == null) {
//      HttpSession session = (HttpSession)pageAttrs.get(SESSION);
            if (session != null) {
                result = session.getAttribute(name);
            }
        }
        if (result == null) {
//      ServletContext context = (ServletContext)pageAttrs.get(APPLICATION);
            if (application != null) {
                result = application.getAttribute(name);
            }
        }
        return result;
    }

    public void forward(String relativeUrlPath) throws ServletException, IOException {
//    ServletRequest request = (ServletRequest)pageAttrs.get(REQUEST);
//    ServletResponse response = (ServletResponse)pageAttrs.get(RESPONSE);
        if (request == null) {
            throw new IllegalStateException("Page context not initialized");
        }
        RequestDispatcher dispatcher = request.getRequestDispatcher(relativeUrlPath);
        dispatcher.forward(request, response);
    }

    public Object getAttribute(String name) {
        return getAttribute(name, PAGE_SCOPE);
    }

    public Object getAttribute(String name, int scope) {
        Object result = null;
        switch (scope) {
            case PAGE_SCOPE:
//        Hashtable ht = (Hashtable)pageAttrs.get(PAGECONTEXT);
                if (pageContext != null) {
                    result = pageContext.get(name);
                }
                break;
            case REQUEST_SCOPE:
//        ServletRequest sr = (ServletRequest)pageAttrs.get(REQUEST);
                if (request != null) {
                    result = request.getAttribute(name);
                }
                break;
            case SESSION_SCOPE:
//        HttpSession session = (HttpSession)pageAttrs.get(SESSION);
                if (session != null) {
                    result = session.getAttribute(name);
                }
                break;
            case APPLICATION_SCOPE:
//        ServletContext context = (ServletContext)pageAttrs.get(APPLICATION);
                if (application != null) {
                    result = application.getAttribute(name);
                }
                break;
            default:
                throw new IllegalArgumentException("Cannot find corresponding scope");
        }
        return result;
    }

    public Enumeration getAttributeNamesInScope(int scope) {
        switch (scope) {
            case PAGE_SCOPE:
//        Hashtable ht = (Hashtable)pageAttrs.get(PAGECONTEXT);
                return pageContext.keys();
            case REQUEST_SCOPE:
//        ServletRequest sr = (ServletRequest)pageAttrs.get(REQUEST);
                return request.getAttributeNames();
            case SESSION_SCOPE:
//        HttpSession session = (HttpSession)pageAttrs.get(SESSION);
                if (session != null) {
                    session.getAttributeNames();
                } else {
                    return null;
                }
            case APPLICATION_SCOPE:
//        ServletContext context = (ServletContext)pageAttrs.get(APPLICATION);
                return application.getAttributeNames();
            default:
                throw new IllegalArgumentException("Cannot find corresponding scope");
        }
    }

    public int getAttributesScope(String name) {
//    Hashtable ht = (Hashtable)pageAttrs.get(PAGECONTEXT);
        if (pageContext != null && pageContext.get(name) != null) {
            return PAGE_SCOPE;
        }
//    ServletRequest sr = (ServletRequest)pageAttrs.get(REQUEST);
        if (request != null && request.getAttribute(name) != null) {
            return REQUEST_SCOPE;
        }
//    HttpSession session = (HttpSession)pageAttrs.get(SESSION);
        if (session != null && session.getAttribute(name) != null) {
            return SESSION_SCOPE;
        }
//    ServletContext context = (ServletContext)pageAttrs.get(APPLICATION);
        if (application != null && application.getAttribute(name) != null) {
            return APPLICATION_SCOPE;
        }
        return 0;
    }

    public Exception getException() {
//    return (Exception)pageAttrs.get(EXCEPTION);
        return exception;
    }

    public JspWriter getOut() {
//    return (JspWriter)pageAttrs.get(OUT);
        return writer;
    }

    public Object getPage() {
//    return pageAttrs.get(PAGE);
        return page;
    }

    public ServletRequest getRequest() {
//    return (ServletRequest)pageAttrs.get(REQUEST);
        return request;
    }

    public ServletResponse getResponse() {
//    return (ServletResponse)pageAttrs.get(RESPONSE);
        return response;
    }

    public ServletConfig getServletConfig() {
//    return (ServletConfig)pageAttrs.get(CONFIG);
        return config;
    }

    public ServletContext getServletContext() {
//    return (ServletContext)pageAttrs.get(APPLICATION);
        return application;
    }

    public HttpSession getSession() {
//    return (HttpSession)pageAttrs.get(SESSION);
        return session;
    }

//  public void handlePageException(Exception ex) throws ServletException, IOException {
//    pageAttrs.put(EXCEPTION, ex);
//    Logger.log(ex, 1);
//    ByteArrayOutputStream baos = new ByteArrayOutputStream();
//    PrintStream ps = new PrintStream(baos);
//    ex.printStackTrace(ps);
//    ps.flush();
//    HttpServletResponse response = (HttpServletResponse)pageAttrs.get(RESPONSE);
//    response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, baos.toString());
//  }

// Added by skilz...

    public void handlePageException(Exception t) throws ServletException, IOException {
        if (errorPage == null) {
            throw new ServletException(t.getMessage(), t);
        } else {
            request.setAttribute("javax.servlet.jsp.JspException", t);
            if (request.getAttribute("javax.servlet.include.request_uri") == null)
                forward(errorPage);
            else
                include(errorPage);
        }
    }

    public void include(String relativeUrlPath) throws ServletException, IOException {
        if (request == null) {
            throw new IllegalStateException("Page context not initialized");
        }
        RequestDispatcher dispatcher = request.getRequestDispatcher(relativeUrlPath);
        dispatcher.include(request, response);
    }

    public void initialize(Servlet servlet, ServletRequest request, ServletResponse response, String errorPageURL,
                           boolean needsSession, int bufferSize, boolean autoFlush) throws IOException {
// Added by skilz
        if (errorPageURL != null) {
//      pageAttrs.put("errorPage", errorPageURL);
            errorPage = errorPageURL;
        }
//
//    pageAttrs.put(APPLICATION, servlet.getServletConfig().getServletContext());
        page = servlet;
        config = servlet.getServletConfig();
        application = config.getServletContext();
//    pageAttrs.put(CONFIG, servlet.getServletConfig());
        ((NusuthJspWriter) writer).init(bufferSize, autoFlush, response.getOutputStream());
//    pageAttrs.put(OUT, writer);
//    pageAttrs.put(PAGE, servlet);
//    pageAttrs.put(PAGECONTEXT,
//                  new Hashtable());
//    pageContext = new Hashtable();
//    pageAttrs.put(REQUEST, request);
        this.request = request;
//    pageAttrs.put(RESPONSE, response);
        this.response = response;
        if (needsSession) {
//      pageAttrs.put(SESSION, ((HttpServletRequest)request).getSession(true));
            session = ((HttpServletRequest) request).getSession(true);
        }
    }

    public void release() {
//    try {
//      this.getOut().close();
//    } catch (Exception ex) {
//    }
//    writer.cleanUp();
//    pageAttrs.clear();
        application = null;
        config = null;
        page = null;
        request = null;
        response = null;
        session = null;
//    pageContext = null;
        exception = null;
        errorPage = null;
        while (!outs.isEmpty()) {
            writer = (JspWriter) outs.pop();
        }
        ((NusuthJspWriter) writer).cleanUp();
        pageContext.clear();
    }

    public void removeAttribute(String name) {
        removeAttribute(name, PAGE_SCOPE);
    }

    public void removeAttribute(String name, int scope) {
        switch (scope) {
            case PAGE_SCOPE:
//        Hashtable ht = (Hashtable)pageAttrs.get(PAGECONTEXT);
                if (pageContext != null) {
                    pageContext.remove(name);
                }
                break;
            case REQUEST_SCOPE:
//        ServletRequest sr = (ServletRequest)pageAttrs.get(REQUEST);
                if (request != null) {
                    request.removeAttribute(name);
                }
                break;
            case SESSION_SCOPE:
//        HttpSession session = (HttpSession)pageAttrs.get(SESSION);
                if (session != null) {
                    session.removeAttribute(name);
                }
                break;
            case APPLICATION_SCOPE:
//        ServletContext context = (ServletContext)pageAttrs.get(APPLICATION);
                if (application != null) {
                    application.removeAttribute(name);
                }
                break;
            default:
                throw new IllegalArgumentException("Cannot find corresponding scope");
        }
    }

    public void setAttribute(String name, Object attribute) {
        setAttribute(name, attribute, PAGE_SCOPE);
    }

    public void setAttribute(String name, Object attribute, int scope) {
        switch (scope) {
            case PAGE_SCOPE:
//        Hashtable ht = (Hashtable)pageAttrs.get(PAGECONTEXT);
                if (pageContext != null) {
                    pageContext.put(name, attribute);
                }
                break;
            case REQUEST_SCOPE:
//        ServletRequest sr = (ServletRequest)pageAttrs.get(REQUEST);
                if (request != null) {
                    request.setAttribute(name, attribute);
                }
                break;
            case SESSION_SCOPE:
//        HttpSession session = (HttpSession)pageAttrs.get(SESSION);
                if (session != null) {
                    session.setAttribute(name, attribute);
                }
                break;
            case APPLICATION_SCOPE:
//        ServletContext context = (ServletContext)pageAttrs.get(APPLICATION);
                if (application != null) {
                    application.setAttribute(name, attribute);
                }
                break;
            default:
                throw new IllegalArgumentException("Cannot find corresponding scope");
        }
    }

    public BodyContent pushBody() {
        JspWriter current = getOut();
        outs.push(current);
        BodyContent res = new NusuthBodyContent(current);
//    pageAttrs.put(OUT, res);
        writer = res;
        return res;
    }

    public JspWriter popBody() {
        NusuthBodyContent w = (NusuthBodyContent) this.getOut();
        JspWriter res = null;
        try {
            res = (JspWriter) outs.pop();
        } catch (EmptyStackException ese) {
            throw new RuntimeException("Internal error: JspWriter stack is empty");
        }
//    pageAttrs.put(OUT, res);
        writer = res;
        return res;
    }
}
