/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import javax.servlet.http.*;
import javax.servlet.*;
import javax.servlet.jsp.*;

import com.azoft.nusuth.core.*;
import com.azoft.nusuth.container.InvocationCache;
import com.azoft.nusuth.util.*;

import java.net.URLDecoder;
import java.io.*;

/**
 * This class extends HttpServlet. It intend for processing requests for jsp
 * pages.
 * @author vdgg, skilz
 * @version 1.22
 * @since Nusuth1.0
 */
public class NusuthJspServlet extends HttpServlet {

    private JspLoader jspLoader;
    private static InvocationCache cache;
    private NusuthContext context;

    static {
        cache = new InvocationCache();
    }

    public void init(ServletConfig config) throws ServletException {
        super.init(config);
        try {
            context = (NusuthContext) config.getServletContext();
            jspLoader = context.getJspLoader();
        } catch (Exception ex) {
            throw new ServletException("Cannot create jsp loader, nested: " + ex);
        }
    }

    /**
     * This method process request for jsp page
     * @param request HttpServletRequest
     * @param response HttpServletResponse
     */
    public void service(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {
        if (request.getMethod().equals("HEAD")) {
            HttpNusuthResponse resp = getRealResponse(response);
            resp.setBodySend(false);
        }
        boolean[] swu = {true, false};
        boolean[] swuold = {false, true};
        boolean writerUsed = false;
        HttpNusuthResponse resp = getRealResponse(response);
        if (resp.isWriterUsed()) {
            writerUsed = true;
            resp.getWriter().flush();
            resp.setStreamWriterUsage(swu);
        }
        JspPage page = null;
        String jspPath = (String) request.getAttribute("javax.servlet."
                + "include.servlet_path");
        if (jspPath == null) {
            jspPath = request.getServletPath();
//      response.setContentType("text/html");
        }
        //Added !!!!!!!!!!!!
        File rFile;
        String requestURI = (String) request.getAttribute("javax.servlet.include."
                + "request_uri");
        StrBuffer strRequestURI = null;
        HttpNusuthRequest httpJBirdRequest = getRealRequest(request);
        if (requestURI == null) {
            strRequestURI = httpJBirdRequest.getRequestURIAsStrBuffer();
        } else {
            strRequestURI = new StrBuffer();
            strRequestURI.append(requestURI);
        }
        StrBuffer sb = new StrBuffer();
        sb.append(request.getServerName());
        sb.append('/');
        try {
            sb.append(URLConverter.decodeURL(strRequestURI));
        } catch (Exception ex) {
            ((NusuthContext) getServletContext()).processError(request, response, 400,
                    null,
                    "Can't decode url \""
                    + strRequestURI + "\"",
                    null,
                    request.getRequestURI(),
                    request.
                    getServletPath());
        }
        strRequestURI = sb;
        JspInvocationCacheElement element
                = (JspInvocationCacheElement) cache.find(strRequestURI);
        try {
            jspPath = URLConverter.decodeURL(jspPath);
        } catch (Exception e) {
            ((NusuthContext) getServletContext()).processError(request, response, 400,
                    null,
                    "Can't decode url \""
                    + strRequestURI + "\"",
                    null,
                    request.getRequestURI(),
                    request.
                    getServletPath());
        }
        if (element != null) {
            rFile = element.realFile;
        } else {
            String rPath = context.getRealPath(jspPath);
            if (rPath == null) {
                ((NusuthContext) getServletContext()).
                        processError(request, response,
                                HttpServletResponse.SC_NOT_FOUND, null,
                                "Cannot find jsp " + jspPath, null,
                                request.getRequestURI(),
                                request.getServletPath());
                if (writerUsed) {
                    resp.setStreamWriterUsage(swuold);
                }
                return;
            }
            rFile = new File(rPath);
            if (!rFile.exists() || rFile.isDirectory() ||
                    !((NusuthContext) getServletContext()).containsResource(jspPath)) {
                ((NusuthContext) getServletContext()).
                        processError(request, response,
                                HttpServletResponse.SC_NOT_FOUND, null,
                                "Cannot find jsp " + jspPath, null,
                                request.getRequestURI(),
                                request.getServletPath());
                if (writerUsed) {
                    resp.setStreamWriterUsage(swuold);
                }
                return;
            }
            element = new JspInvocationCacheElement();
            element.realFile = rFile;
            cache.add(strRequestURI, element);
        }
        //!!!!!!!!!!!!!!!!!!
        // Modified by skilz...
        String queryString = request.getQueryString();
        if (queryString == null || queryString.indexOf("jsp_precompile") == -1) {
            try {
                page = jspLoader.loadJsp(jspPath, rFile, false);
            } catch (JspException jse) {
                ((NusuthContext) getServletContext()).
                        processError(request, response,
                                HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                                jse.getClass(), "Cannot load jsp page", jse,
                                request.getRequestURI(),
                                request.getServletPath());
                if (writerUsed) {
                    resp.setStreamWriterUsage(swuold);
                }
                return;
            }
            if (page == null) {
                ((NusuthContext) getServletContext()).
                        processError(request, response,
                                HttpServletResponse.SC_NOT_FOUND, null,
                                "Cannot find jsp " + request.getServletPath(),
                                null, request.getRequestURI(),
                                request.getServletPath());
            } else {
                page.service(request, response);
            }
        } else {
            int index = request.getQueryString().indexOf("jsp_precompile");
            String query = request.getQueryString().substring(index + 14);
            if (query.length() == 0 || query.startsWith("&")) {
                try {
                    page = jspLoader.loadJsp(jspPath, rFile, false);
                } catch (JspException jse) {
                    ((NusuthContext) getServletContext()).
                            processError(request, response,
                                    HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                                    jse.getClass(), "Internal server error", jse,
                                    request.getRequestURI(),
                                    request.getServletPath());
                    if (writerUsed) {
                        resp.setStreamWriterUsage(swuold);
                    }
                    return;
                }
            } else {
                if (query.charAt(0) == '=') {
                    query = query.substring(1);
                    if (query.startsWith("\"false\"")) {
                        query = query.substring(7);
                        if (query.length() == 0 || query.charAt(0) == '&') {
/*
              try {
                page = jspLoader.loadJsp(jspPath, rFile);
              } catch(JspException jse) {
                  ((NusuthContext)getServletContext()).
                  processError(request, response,
                  HttpServletResponse.SC_INTERNAL_SERVER_ERROR, jse.getClass(),
                  "Internal server error", jse, request.getRequestURI());
                if (writerUsed) {
                  ((HttpNusuthResponse)response).setStreamWriterUsage(swuold);
                }
                return;
              }
              if (page == null) {
                  ((NusuthContext)getServletContext()).
                  processError(request, response,
                  HttpServletResponse.SC_NOT_FOUND, null,
                  "Cannot find jsp "+request.getServletPath(), null,
                  request.getRequestURI());
              } else {
                page.service(request, response);
              }
*/
                        } else {
                            ((NusuthContext) getServletContext()).
                                    processError(request, response,
                                            HttpServletResponse.SC_BAD_REQUEST, null,
                                            "Incorrect query string", null,
                                            request.getRequestURI(),
                                            request.getServletPath());
                        }
                    } else {
                        if (query.startsWith("\"true\"")) {
                            query = query.substring(6);
                            if (query.length() == 0 || query.charAt(0) == '&') {
                                try {
                                    page = jspLoader.loadJsp(jspPath, rFile, false);
                                } catch (JspException jse) {
                                    ((NusuthContext) getServletContext()).
                                            processError(request, response,
                                                    HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                                                    jse.getClass(),
                                                    "Internal server error", jse,
                                                    request.getRequestURI(),
                                                    request.getServletPath());
                                    if (writerUsed) {
                                        resp.setStreamWriterUsage(swuold);
                                    }
                                    return;
                                }
                            } else {
                                ((NusuthContext) getServletContext()).
                                        processError(request, response,
                                                HttpServletResponse.SC_BAD_REQUEST, null,
                                                "Incorrect query string", null,
                                                request.getRequestURI(),
                                                request.getServletPath());
                            }
                        } else {
                            ((NusuthContext) getServletContext()).
                                    processError(request, response,
                                            HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                                            null, "Incorrerct value for "
                                    + "\"jsp_precompile\" parameter !\r\nThe"
                                    + " \"jsp_precompile\" parameter may have "
                                    + "no value, or may have values "
                                    + "\"true\" or \"false\".", null,
                                            request.getRequestURI(),
                                            request.getServletPath());
                            if (writerUsed) {
                                resp.setStreamWriterUsage(swuold);
                            }
                            return;
                        }
                    }
                }
            }
        }
        if (writerUsed) {
            resp.setStreamWriterUsage(swuold);
        }
    }

    /**
     * This method return "real" response from given. If given response is
     * wrapper, then this method get response from it.
     * @param response HTTP response or wrapper;
     * @return HttpNusuthResponse Real HTTP response.
     */
    public HttpNusuthResponse getRealResponse(HttpServletResponse response) {
        HttpServletResponse resp = response;
        while (resp instanceof HttpServletResponseWrapper) {
            resp = (HttpServletResponse)
                    ((HttpServletResponseWrapper) resp).getResponse();
        }
        return (HttpNusuthResponse) resp;
    }

    /**
     * This method return "real" request from given. If given request is wrapper,
     * then this method get request from it.
     * @param request HTTP request or wrapper;
     * @return HttpNusuthRequest Real HTTP request.
     */
    public HttpNusuthRequest getRealRequest(HttpServletRequest request) {
        HttpServletRequest req = request;
        while (req instanceof HttpServletRequestWrapper) {
            req = (HttpServletRequest)
                    ((HttpServletRequestWrapper) req).getRequest();
        }
        return (HttpNusuthRequest) req;
    }

    public void destroy() {
        jspLoader.destroyAll();
    }
}

