/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import javax.servlet.jsp.JspEngineInfo;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthJspEngineInfo extends JspEngineInfo {

    public NusuthJspEngineInfo() {
        super();
    }

    public String getSpecificationVersion() {
        return "1.1";
    }
}

