/* Generated by VDGG */

package com.azoft.nusuth.jsp;

import java.util.*;
//import com.azoft.nusuth.util.Logger;
import java.io.*;

/**
 * This class is a result of Parser.preGenerate().
 * It contains all parts of source code that must be contained in resulted servlet. This parts
 * are: methods and directives.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
class PreServlet {

    private String packName;
    private String className;
    private StringBuffer imports = new StringBuffer();
    private StringBuffer declarations = new StringBuffer();
    private StringBuffer staticBlock = new StringBuffer();
    private StringBuffer jspServiceMethod = new StringBuffer();
    private int templateCounter = 0;
    private final static String jspPrefix = "javax.servlet.jsp.";
    private final static String servletPrefix = "javax.servlet.";
    private final static String jbirdPrefix = "com.azoft.nusuth.jsp.";
    private String extClass = "com.azoft.nusuth.jsp.NusuthJspPage";
    private boolean needSession = true;
    private int bufferSize = 8192;
    private boolean autoFlush = true;
    private boolean isThreadSafe = true;
    private String info = null;
    private String errorPage = null;
    private boolean isErrorPage = false;
    private String contentType = "text/html";
    private Hashtable tagDeclarations = new Hashtable();
    private boolean useRawStream = true;
    private String encoding;
    private boolean templateTextStarted = false;
    org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.jsp");

    PreServlet(String packName, String className, String encoding) {
        this.encoding = encoding;
        this.packName = packName;
        this.className = className;
        add2Imports("javax.servlet.*");
        add2Imports("javax.servlet.http.*");
        add2Imports("javax.servlet.jsp.*");
        add2Imports("javax.servlet.jsp.tagext.*");
    }

    void add2Imports(String imPath) {
        imports.append("import " + imPath + ";\r\n");
    }

    void add2Declarations(String decl) {
        declarations.append("  " + decl + "\r\n");
    }

    void add2StaticBlock(String cont) {
        staticBlock.append("    " + cont + "\r\n");
    }

    void add2Service(String content) {
        jspServiceMethod.append(content);
    }

    void setExtends(String extClass) {
        this.extClass = extClass;
    }

    void setNeedSession(boolean needSession) {
        this.needSession = needSession;
    }

    void setBufferSize(int bufferSize) {
        this.bufferSize = bufferSize;
    }

    void setAutoFlush(boolean autoFlush) {
        this.autoFlush = autoFlush;
    }

    void setIsThreadSafe(boolean isThreadSafe) {
        this.isThreadSafe = isThreadSafe;
    }

    void setInfo(String info) {
        this.info = info;
    }

    void setErrorPage(String errorPage) {
//    this.errorPage = errorPage;
//Added by skilz...
        this.errorPage = "\"" + errorPage + "\"";
    }

    void setIsErrorPage(boolean isErrorPage) {
        this.isErrorPage = isErrorPage;
    }

    void setContentType(String contentType) {
        this.contentType = contentType;
    }

    void setEncoding(String encoding) {
        this.encoding = encoding;
    }

    String getContentType() {
        return contentType;
    }

    void addTemplateText(StringBuffer sb) {
        if (sb.length() > 0) {
            if (useRawStream) {
/*        int start = 0;
        int end;
        int increase = 0;
        while(start < sb.length()) {
          end = start + 160 > sb.length() ? sb.length() : start + 160;
          if (end < sb.length() && sb.charAt(end-1) == '\\' && (sb.charAt(end) == 'r' ||
                                                                  sb.charAt(end) == 'n' || sb.charAt(end) == 't' || sb.charAt(end) == '\"' ||
                                                                  sb.charAt(end) == '\'')) {
            increase = 1;
          }
          add2Declarations("private static byte[] _jsp_template"+templateCounter+";");
          if (!templateTextStarted) {
            add2StaticBlock("try {");
            templateTextStarted = true;
          }
          add2StaticBlock("  _jsp_template"+templateCounter+" = \""+sb.substring(start, end+increase)+"\".getBytes(\""+encoding+"\");");
          add2Service("\r\n      _jsp_jbirdWriter.rawWrite(_jsp_template"+templateCounter+");\r\n");
          templateCounter++;
          start += (160+increase);
          increase = 0;
        }
*/
                add2Declarations("private static byte[] _jsp_template" + templateCounter + ";");
                if (!templateTextStarted) {
                    add2StaticBlock("try {");
                    templateTextStarted = true;
                }
                add2StaticBlock("  _jsp_template" + templateCounter + " = \"" + sb.toString() + "\".getBytes(\"" + encoding + "\");");
                add2Service("\r\n      _jsp_nusuthWriter.rawWrite(_jsp_template" + templateCounter + ");\r\n");
                templateCounter++;

            } else {
                add2Service("      out.print(\"" + sb.toString() + "\");\r\n");
            }
        }
    }

    void addTemplateText(String s) {
        addTemplateText(new StringBuffer(s));
    }

    void addDeclaredTag(String className, String varName) {
        tagDeclarations.put(varName, className);
    }

    void writeTo(PrintWriter writer) throws IOException {
        if (info != null) {
            add2Declarations("public String getServletInfo() {\r\n    return \"" + info + "\";\r\n  }");
        }
        writer.println("/* Generated by Nusuth Engine */");
        writer.println("package " + packName + ";");
        writer.println();
        writer.println(imports);
//    writer.print("public class "+className+" extends "+extClass);
        writer.print("public class " + className.replace(' ', '_') + " extends " + extClass.replace(' ', '_'));
        if (!isThreadSafe) {
            writer.print(" implements SingleThreadModel");
        }
        writer.println(" {");
        writer.println();
        writer.println(declarations);
        if (templateTextStarted) {
            add2StaticBlock("} catch(java.io.UnsupportedEncodingException _jsp_uee) {}");
        }
        writer.println("  static {");
        writer.print(staticBlock);
        writer.println("  }");
        writer.println();

//writer.println("  public void jspInit() {");
//writer.print(jspInitMethod);
//writer.println("  }");
//writer.println();

        writer.println("  public void _jspService(HttpServletRequest request, HttpServletResponse response)");
        writer.println("                         throws ServletException, java.io.IOException {");
//    writer.println("    response.setContentType(\""+contentType+";charset="+encoding+"\");");
        writer.println("    response.setContentType(\"" + contentType + "\");");
        writer.print("    " + jspPrefix + "PageContext pageContext = " + jspPrefix + "JspFactory.getDefaultFactory().getPageContext(this, request, response, ");
        writer.print(errorPage == null ? "null" : errorPage);
        writer.println(", " + needSession + ", " + bufferSize + ", " + autoFlush + ");");
        writer.println("    Object page = this;");
        writer.println("    " + jspPrefix + "JspWriter out = pageContext.getOut();");
// Added by skilz...
        if (isErrorPage) {
            writer.println("    Throwable exception = (Throwable) request.getAttribute(\"javax.servlet.jsp.JspException\");     ");
        }
//
        writer.println("    " + servletPrefix + "ServletContext application = pageContext.getServletContext();");
        writer.println("    " + servletPrefix + "ServletConfig config = pageContext.getServletConfig();");
        if (needSession) {
            writer.println("    " + servletPrefix + "http.HttpSession session = pageContext.getSession();");
        }
//    writer.println("    response.setContentType(\""+contentType+"\");");
        writer.println();
        writer.println("    " + jbirdPrefix + "NusuthJspWriter _jsp_nusuthWriter = (" + jbirdPrefix + "NusuthJspWriter)out;");
        writer.println("    _jsp_nusuthWriter.setEncoding(\"" + encoding + "\");");
        writer.println();
        if (tagDeclarations.size() > 0) {
            Enumeration enum = tagDeclarations.keys();
            String className;
            String varName;
            while (enum.hasMoreElements()) {
                varName = (String) enum.nextElement();
                className = (String) tagDeclarations.get(varName);
                writer.println("    " + className + " " + varName + " = null;");
            }
            writer.println();
        }
        writer.println("    try {");
        writer.println(jspServiceMethod);
        writer.println("    } catch (Exception ex) {");
        writer.println("      pageContext.handlePageException(ex);");
        writer.println("    } finally {");
        writer.println("      _jsp_nusuthWriter.fakeFlush();");
        writer.println("      " + jspPrefix + "JspFactory.getDefaultFactory().releasePageContext(pageContext);");
//    writer.println("    }");
//    writer.print("  }\r\n}");
//    writer.flush();
/*    if (tagDeclarations.size() > 0) {
      Enumeration enum = tagDeclarations.keys();
      String varName;
      while(enum.hasMoreElements()) {
        varName = (String)enum.nextElement();
        writer.println("      if ("+varName+"!=null) {\r\n        "+varName+".release();\r\n      }");
      }
    }
*/
        writer.println("    }");
        writer.print("  }\r\n}");
        writer.flush();

    }

    public Hashtable getTagDeclarations() {
        return tagDeclarations;
    }

    void setUseRawStream(boolean useRawStream) {
        this.useRawStream = useRawStream;
    }
}

