package com.azoft.nusuth.management.rmi;

/*****************************************************************************
 *                                                                           *
 *                      (c) 2000-2001 Thruport Technologies                  *
 *                                                                           *
 *****************************************************************************/
/* Generated by VDGG */

import com.azoft.nusuth.management.ApplicationInputStream;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.io.*;

public class RmiApplicationInputStreamImpl extends UnicastRemoteObject implements RmiApplicationInputStream {

    private InputStream stream = null;
    private boolean eof = true;


    /**
     * Insert the method's description here.
     * Creation date: (17.01.01 13:27:29)
     * @param source java.io.InputStream
     * @exception java.rmi.RemoteException The exception description.
     */
    public RmiApplicationInputStreamImpl(InputStream source) throws java.rmi.RemoteException {
        stream = source;
        eof = false;
    }


    /**
     * Insert the method's description here.
     * Creation date: (17.01.01 3:34:50)
     * @return int
     */
    public int available() throws RemoteException {

        try {
            return stream.available();
        } catch (IOException ioex) {
            throw new RemoteException("", ioex);
        }
    }


    public void close() throws RemoteException {

        try {
            stream.close();
        } catch (IOException ioex) {
            throw new RemoteException("Can't close, nested:", ioex);
        }
    }


    /**
     * Insert the method's description here.
     * Creation date: (17.01.01 13:29:34)
     * @return boolean
     */
    public boolean isEof() {
        return eof;
    }


    /**
     * read method comment.
     */
    public byte[] read(int length) throws RemoteException {
        if (eof)
            return new byte[0];
        try {
            byte[] buffer = new byte[length];
            int readed = 0, total_readed = 0;
            while (!eof && (total_readed < length)) {
                readed = stream.read(buffer, total_readed, length - total_readed);
                if (readed == -1) {
                    byte[] result = new byte[total_readed];
                    System.arraycopy(buffer, 0, result, 0, total_readed);
                    eof = true;
                    return result;
                }
                total_readed += readed;
            }
            return buffer;
        } catch (IOException ioex) {
            throw new RemoteException("Can't read, nested:", ioex);
        }
    }
}