/*****************************************************************************
 *                                                                           *
 *                      (c) 2000-2001 Thruport Technologies                  *
 *                                                                           *
 *****************************************************************************/
package com.azoft.nusuth.management.rmi;

/* Generated by VDGG */

import java.rmi.Remote;
import java.rmi.RemoteException;
import java.util.Vector;
import java.io.InputStream;

import com.azoft.nusuth.management.ContainerState;

public interface RmiContainerManager
        extends RmiComponentManager {
    public ContainerState getState() throws RemoteException;

    void startServer() throws RemoteException;

    void stopServer() throws RemoteException;

    void addApplication(String virtualHost, String appUrl, RmiApplicationInputStream application) throws RemoteException;

    RmiApplicationInputStream getVirtualHosts() throws RemoteException;

    void patchApplication(String virtualHost, String appUrl, RmiApplicationInputStream patch, boolean overwrite) throws RemoteException;

    void removeApplication(String virtualHost, String appUrl) throws RemoteException;

    void replaceApplicationContent(String virtualHost, String appUrl, RmiApplicationInputStream content) throws RemoteException;

    void startApplication(String virtualHost, String appUrl) throws RemoteException;

    void stopApplication(String virtualHost, String appUrl) throws RemoteException;

    int getHttpPort() throws RemoteException;
}
