package com.azoft.nusuth.management.rmi;/* Generated by Together */

/*****************************************************************************
 *                                                                           *
 *                      (c) 2000-2001 Thruport Technologies                  *
 *                                                                           *
 *****************************************************************************/
/* Generated by Together */

import java.rmi.Remote;
import java.util.Vector;
import java.util.Arrays;

import com.azoft.nusuth.management.*;
import com.azoft.nusuth.management.security.*;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;

public class RmiClusterManagerImpl extends UnicastRemoteObject implements RmiClusterManager {

    private ClusterManager clusterManager;


    public RmiClusterManagerImpl(ClusterManager manager) throws RemoteException {
        clusterManager = manager;
    }


    public RmiApplicationInputStream getComponentSettings(String sessionId, String componentType, String componentId) throws RemoteException {
        try {
            return new RmiApplicationInputStreamImpl(clusterManager.getComponentSettings(sessionId, new ComponentType(componentType), componentId));
        } catch (UnauthorizedAccessException uaex) {
            throw new RemoteException("", uaex);
        } catch (AccessDeniedException adex) {
            throw new RemoteException(adex.getMessage(), adex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public ContainerState getContainerState(String sessionId, String containerId) throws RemoteException {
        try {
            return clusterManager.getContainerState(sessionId, containerId);
        } catch (UnauthorizedAccessException uaex) {
            throw new RemoteException("", uaex);
        } catch (AccessDeniedException adex) {
            throw new RemoteException(adex.getMessage(), adex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public DistributorState getDistributorState(String sessionId, String distributorId) throws RemoteException {
        try {
            return clusterManager.getDistributorState(sessionId, distributorId);
        } catch (UnauthorizedAccessException uaex) {
            throw new RemoteException("", uaex);
        } catch (AccessDeniedException adex) {
            throw new RemoteException(adex.getMessage(), adex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RemoteException("", ex);
        }
    }


    public String login(String user, String encodedPassword) throws RemoteException {
        return clusterManager.login(user, encodedPassword);
    }


    public void setComponentSettings(String sessionId, String componentType, String componentId, RmiApplicationInputStream componentSettings) throws RemoteException {
        try {
            clusterManager.setComponentSettings(sessionId, new ComponentType(componentType), componentId, new ApplicationInputStreamWrapper(componentSettings));
        } catch (UnauthorizedAccessException e) {
            throw new RemoteException("", e);
        } catch (AccessDeniedException adex) {
            throw new RemoteException(adex.getMessage(), adex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void addComponent(String sessionId, String host, int port) throws RemoteException {
        try {
            clusterManager.addComponent(sessionId, host, port);
        } catch (UnauthorizedAccessException e) {
            throw new RemoteException("", e);
        } catch (AccessDeniedException adex) {
            throw new RemoteException(adex.getMessage(), adex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public RmiApplicationInputStream getApplicationsDeployment(String sessionId) throws RemoteException {
        try {
            return new RmiApplicationInputStreamImpl(clusterManager.getApplicationsDeployment(sessionId));
        } catch (UnauthorizedAccessException e) {
            throw new RemoteException("", e);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public Vector getRegisteredComponents(String sessionId) throws RemoteException {
        try {
            return clusterManager.getRegisteredComponents(sessionId);
        } catch (UnauthorizedAccessException uaex) {
            throw new RemoteException("", uaex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void removeComponent(String sessionId, ComponentInfo cinfo) throws RemoteException {
        try {
            clusterManager.removeComponent(sessionId, cinfo);
        } catch (UnauthorizedAccessException e) {
            throw new RemoteException("", e);
        } catch (AccessDeniedException adex) {
            throw new RemoteException(adex.getMessage(), adex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void setApplicationsDeployment(String sessionId, RmiApplicationInputStream applicationsDeployment) throws RemoteException {
        try {
            clusterManager.setApplicationsDeployment(sessionId, new ApplicationInputStreamWrapper(applicationsDeployment));
        } catch (UnauthorizedAccessException e) {
            throw new RemoteException("", e);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public RmiApplicationInputStream getApplicationsDeploymentErrors(String sessionId) throws RemoteException {
        try {
            return new RmiApplicationInputStreamImpl(clusterManager.getApplicationsDeploymentErrors(sessionId));
        } catch (UnauthorizedAccessException uaex) {
            throw new RemoteException("", uaex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void registerCallback(RmiGuiCallback gui) throws RemoteException {
        clusterManager.registerCallback(new GuiCallbackWrapper(gui));
    }


    public RmiApplicationInputStream getSecuritySettings(String sessionId) throws RemoteException {
        try {
            return new RmiApplicationInputStreamImpl(clusterManager.getSecuritySettings(sessionId));
        } catch (UnauthorizedAccessException uaex) {
            throw new RemoteException("", uaex);
        } catch (AccessDeniedException adex) {
            throw new RemoteException(adex.getMessage(), adex);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void setSecuritySettings(String sessionId, RmiApplicationInputStream newSettings) throws RemoteException {
        try {
            clusterManager.setSecuritySettings(sessionId, new ApplicationInputStreamWrapper(newSettings));
        } catch (UnauthorizedAccessException e) {
            throw new RemoteException("", e);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }

    public void reconnect(String sessionId, String componentType, String componentId) throws RemoteException {
        try {
            clusterManager.reconnect(sessionId, componentType, componentId);
        } catch (UnauthorizedAccessException e) {
            throw new RemoteException("", e);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }
}
