package com.azoft.nusuth.management.rmi;

/*****************************************************************************
 *                                                                           *
 *                      (c) 2000-2001 Thruport Technologies                  *
 *                                                                           *
 *****************************************************************************/

import com.azoft.nusuth.management.ManagementException;/* Generated by Together */
import com.azoft.nusuth.management.*;
import com.azoft.nusuth.management.security.AdminPortListener;
import com.azoft.nusuth.jndi.DistributedJNDIContext;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.Vector;

public class RmiDeployerImpl extends UnicastRemoteObject implements RmiDeployer {
    private Deployer deployer;


    public RmiDeployerImpl(Deployer deployer) throws RemoteException {
        this.deployer = deployer;
    }


    public RmiApplicationInputStream getSettings() throws RemoteException {
        try {
            return new RmiApplicationInputStreamImpl(deployer.getSettings());
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void setSettings(RmiApplicationInputStream settings) throws RemoteException {
        try {
            deployer.setSettings(new ApplicationInputStreamWrapper(settings));
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void addApplication(Vector hosts) throws RemoteException {
        try {
            deployer.addApplication(hosts);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public RmiApplicationInputStream getWebInf(String docBase, String location) throws java.rmi.RemoteException {
        try {
            return new RmiApplicationInputStreamImpl(deployer.getWebInf(docBase, location));
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void patchApplication(Vector hosts, boolean overwrite) throws RemoteException {
        try {
            deployer.patchApplication(hosts, overwrite);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }


    public void replaceContent(Vector hosts) throws RemoteException {
        try {
            deployer.replaceContent(hosts);
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }

    public DistributedJNDIContext getDistributedContext() throws RemoteException {
        try {
            return deployer.getDistributedContext();
        } catch (ManagementException mex) {
            throw new RemoteException(mex.getMessage(), mex);
        }
    }
}
