/* Generated by VDGG */

package com.azoft.nusuth.deployment;

import java.util.*;
import java.io.*;

import org.w3c.dom.*;
import com.azoft.nusuth.util.StrBuffer;

/**CompositeNusuthWebAppElement represents complex element of the web app
 * configuration file. It consists of the lists of the simple sub elemets and
 * complex sub elements of this complex element. Provides methods for working
 * with them , such as add methods , set methods etc.
 * @author vdgg, skilz
 * @version 1.11
 * @since Nusuth1.0
 */
public class CompositeNusuthWebAppElement extends NusuthWebAppElement implements Serializable {
    //Hashtable that consists of the elements defined by xml schema and defines nesting of the elements.
    protected static Hashtable dtdTables = new Hashtable();

    protected Hashtable dtdTable;
    //Hashtable that consists of the sub elements of this element defined by xml schema and defines their nesting.
    private Hashtable innerDTDTable;

    /**
     *@link aggregation
     *      @associates <{com.azoft.nusuth.deployment.SimpleNusuthWebAppElement}>
     * @supplierCardinality 0..*
     * @supplierRole simpleElements
     */
    private Hashtable simpleElements = new Hashtable();

    /**
     *@link aggregation
     *      @associates <{com.azoft.nusuth.deployment.CompositeNusuthWebAppElement}>
     * @supplierCardinality 0..*
     * @supplierRole compositeElements
     */
    private Hashtable compositeElements = new Hashtable();

    private String type;


    /**The CompositeNusuthWebAppElement constructor method.(Calles the init method of this class)
     * @param node the node from the DOM tree that is associated with this composite element.
     * @param depth the depth of the composite element in the xml tree.
     * @exception DeploymentException is thrown if it occures while the sub elements are created.
     */
    protected CompositeNusuthWebAppElement(String type, Node node, int depth) throws DeploymentException {
        super(node, depth);
        init(type);
        NodeList lst = node.getChildNodes();
        //    System.out.println(node.getNodeName());
        Node n;
        List sList;
        //Creates Classes for the sub elements :
        for (int i = 0; i < lst.getLength(); i++) {
            n = lst.item(i);
            if (!n.getNodeName().equals("#text") && !n.getNodeName().equals("#comment")) {
                //        System.out.println(n.getNodeName());
                //If this node name is in the dtdTable HashTable then it is a composite elenment otherwise it is simle element.
                checkExistence(n.getNodeName());
                if (dtdTable.get(n.getNodeName()) == null) {
                    sList = (List) simpleElements.get(n.getNodeName());
                    try {
                        sList.add(new SimpleNusuthWebAppElement(n, getDepth() + 1));
                    } catch (ClassCastException ex) {
                        throw new DeploymentException("Element \"" + n.getNodeName() + "\" must be simple");
                    }
                } else {
                    sList = (List) compositeElements.get(n.getNodeName());
                    sList.add(new CompositeNusuthWebAppElement(type, n, getDepth() + 1));
                }
            } else if (n.getNodeName().equals("#text") && n.getNodeValue().trim().length() > 0) {
                throw new DeploymentException("Template text \"" + n.getNodeValue().trim() + "\" not allowed inside \"" + n.getParentNode().getNodeName() + "\" element");
            }
        }
    }


    /**The CompositeNusuthWebAppElement constructor method.(Calles the init method of this class)
     * @param name the tag name of the xml tree element associated with this composite element.
     * @param depth the of depth the element associated with this composite element in the xml tree of the web app configuration file.
     * @exception DeploymentException is thrown in the same cases as for the init method of this class.
     */
    protected CompositeNusuthWebAppElement(String type, String name, int depth) throws DeploymentException {
        super(name, depth);
        init(type);
    }

    /**
     * This method validate current element corresponding to the node.
     * @param node The DOM node that used during valitation.
     * @exception DeploymentException is thrown if validation is not processed.
     */
    public void validate(Node node) throws DeploymentException {
        if (node.hasAttributes()) {
            checkForAttributes(node);
        }
        NodeList list = node.getChildNodes();
        for (int i = 0; i < list.getLength(); i++) {
            if (((Node) list.item(i)).hasAttributes())
                checkForAttributes((Node) list.item(i));
        }
        Enumeration compositeNames = getCompositeChildrenNames();
        Enumeration simpleNames = getSimpleChildrenNames();
        String childName = null;
        while (compositeNames.hasMoreElements()) {
            childName = (String) compositeNames.nextElement();
            check(childName, true, node);
        }
        while (simpleNames.hasMoreElements()) {
            childName = (String) simpleNames.nextElement();
            check(childName, false, node);
        }
    }

    /**
     * This method check if the <i>childName</i> is allowed inside <i>node</i>.
     * @param childName Child element name.
     * @param isComposite Indicates the type of <i>childName</i>.
     * @param node Parent node.
     */
    private void check(String childName, boolean isComposite, Node node)
            throws DeploymentException {
        checkExistence(childName);
        Enumeration enum = isComposite ? getCompositeChild(childName)
                : getSimpleChild(childName);
        if (!enum.hasMoreElements() && isChildRequired(childName)) {
            Inclusion incl = (Inclusion) innerDTDTable.get(childName);
            if (incl.getChoiceLinks() != null) {
                if (notContainsRequiredElements(incl.getChoiceLinks())) {
                    List list = incl.getChoiceLinks();
                    StrBuffer error = new StrBuffer();
                    error.append("One of the elements \"" + list.get(0) + "\"");
                    for (int i = 1; i < list.size(); i++)
                        error.append(", \"" + list.get(i) + "\"");
                    error.append(" must be declared inside \"" + getNode().getNodeName()
                            + "\" element");
                    throw new DeploymentException(error.toString());
                }
            } else if (isChildRequired(childName)) {
                throw new DeploymentException("Element " + childName
                        + " is required inside "
                        + node.getNodeName() + " element");
            }
        }
        int count = 0;
        NodeList l = ((Element) node).getElementsByTagName(childName);
        while (enum.hasMoreElements()) {
            count++;
            Inclusion incl = (Inclusion) innerDTDTable.get(childName);
            if (incl.getChoiceLinks() != null) {
                if (containsAnotherElement(incl.getChoiceLinks(), childName)) {
                    List list = incl.getChoiceLinks();
                    StrBuffer error = new StrBuffer();
                    error.append("Only one of the elements \"" + list.get(0) + "\"");
                    for (int i = 1; i < list.size(); i++)
                        error.append(", \"" + list.get(i) + "\"");
                    error.append(" allowed inside \"" + getNode().getNodeName()
                            + "\" element");
                    throw new DeploymentException(error.toString());
                }
            }
            if (!isChildUnbounded(childName) && count > 1) {
                throw new DeploymentException("Only one element \"" + childName
                        + "\" allowed  inside \""
                        + getNode().getNodeName() + "\" element");
            }
            if (isComposite) {
                CompositeNusuthWebAppElement elem =
                        (CompositeNusuthWebAppElement) enum.nextElement();
                elem.validate(l.item(count - 1));
            } else {
                enum.nextElement();
            }
        }
    }

    private boolean notContainsRequiredElements(List list) {
        for (int i = 0; i < list.size(); i++) {
            if (((ArrayList) simpleElements.get(list.get(i))).size() > 0)
                return false;
        }
        return true;
    }

    private boolean containsAnotherElement(List list, String name) {
        for (int i = 0; i < list.size(); i++) {
            if (((ArrayList) simpleElements.get(list.get(i))).size() > 0
                    && !list.get(i).equals(name))
                return true;
        }
        return false;
    }

    private void checkForAttributes(Node node) throws DeploymentException {
        NamedNodeMap attrs = node.getAttributes();
        for (int i = 0; i < attrs.getLength(); i++) {
            if (((Attr) attrs.item(i)).getSpecified() && !((Attr) attrs.item(i)).getName().equalsIgnoreCase("id"))
                throw new DeploymentException("Element \"" + node.getNodeName() + "\" can't have any attributes except \"id\"");
        }
    }

    /** This method adds necessary sub elements to this composite element class.
     * @exception DeploymentException is thrown if this element tag corresponds to the simple element.
     */
    private void init(String type) throws DeploymentException {
        dtdTable = (Hashtable) dtdTables.get(type);
        if (dtdTable == null) {
            throw new DeploymentException("Cannot find dtd table of type " + type);
        }
        this.type = type;
        innerDTDTable = (Hashtable) dtdTable.get(getTag());
        if (innerDTDTable == null) {
            throw new DeploymentException("No element " + getTag() + " defined in dtd");
        }
        Enumeration enum = innerDTDTable.keys();
        String name;
        while (enum.hasMoreElements()) {
            name = (String) enum.nextElement();
            if (dtdTable.get(name) == null) {
                simpleElements.put(name, new ArrayList());
            } else {
                compositeElements.put(name, new ArrayList());
            }
        }
    }


    /**This method is used to get tag names of the simple sub elements of this composite element.
     * @return the enumeration of Strings - the tag names of the simple sub elements.
     */
    public Enumeration getSimpleChildrenNames() {
        return simpleElements.keys();
    }


    /**This method is used to get tag names of the composite sub elements of this composite element.
     * @return enumeration of Strings - the tag names of the composite sub elements.
     */
    public Enumeration getCompositeChildrenNames() {
        return compositeElements.keys();
    }


    /**This method is used to get the Enumeration of the simple sub elements of this composite element, with the given tag name.
     * @param childName the tag name.
     * @return Enumeration of SimpleNusuthWebAppElement classes.
     * @exception DeploymentException is thrown if the given name is not the name of the simple element or it is not the permitted name for the sub element of this composite element.
     */
    public void setAllRequiredChilds() throws DeploymentException {
        Enumeration enum = getCompositeChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            if (isChildRequired(name) && !getCompositeChild(name).hasMoreElements()) {
                if (isChildUnbounded(name)) {
                    addCompositeChild(name);
                } else {
                    setCompositeChild(name);
                }
                ((CompositeNusuthWebAppElement) getCompositeChild(name).nextElement()).setAllRequiredChilds();
            }
        }
        enum = getSimpleChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            if (isChildRequired(name) && !getSimpleChild(name).hasMoreElements()) {
                if (isChildUnbounded(name)) {
                    addSimpleChild(name);
                } else {
                    setSimpleChild(name);
                }
                ((SimpleNusuthWebAppElement) getSimpleChild(name).nextElement()).setContent("");
            }
        }
    }

    public void removeEmptyComponents() throws DeploymentException {
        Enumeration enum = getSimpleChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getSimpleChild(name);
            while (enum1.hasMoreElements()) {
                SimpleNusuthWebAppElement simp = (SimpleNusuthWebAppElement) enum1.nextElement();
                if (!isChildRequired(name) && simp.getContent() != null && simp.getContent().trim().length() == 0) {
                    removeSimpleChild(name, simp);
                    enum1 = getSimpleChild(name);
                }
            }
        }
        enum = getCompositeChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getCompositeChild(name);
            while (enum1.hasMoreElements()) {
                CompositeNusuthWebAppElement comp = (CompositeNusuthWebAppElement) enum1.nextElement();
                comp.removeEmptyComponents();
            }
        }
        enum = getCompositeChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getCompositeChild(name);
            while (enum1.hasMoreElements()) {
                CompositeNusuthWebAppElement comp = (CompositeNusuthWebAppElement) enum1.nextElement();
                if (!comp.containsElements() && !isChildRequired(name)) {
                    removeCompositeChild(name, comp);
                    enum1 = getCompositeChild(name);
                }
            }
        }
    }

    public void removeEmptyComponents(String exlusion) throws DeploymentException {
        Enumeration enum = getSimpleChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getSimpleChild(name);
            while (enum1.hasMoreElements()) {
                SimpleNusuthWebAppElement simp = (SimpleNusuthWebAppElement) enum1.nextElement();
                if (!isChildRequired(name) && simp.getContent() != null && simp.getContent().trim().length() == 0) {
                    removeSimpleChild(name, simp);
                    enum1 = getSimpleChild(name);
                }
            }
        }
        enum = getCompositeChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getCompositeChild(name);
            while (enum1.hasMoreElements()) {
                CompositeNusuthWebAppElement comp = (CompositeNusuthWebAppElement) enum1.nextElement();
                if (!comp.getTag().equals(exlusion)) {
                    comp.removeEmptyComponents();
                }
            }
        }
        enum = getCompositeChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getCompositeChild(name);
            while (enum1.hasMoreElements()) {
                CompositeNusuthWebAppElement comp = (CompositeNusuthWebAppElement) enum1.nextElement();
                if (!comp.containsElements() && !isChildRequired(name) && !comp.getTag().equals(exlusion)) {
                    removeCompositeChild(name, comp);
                    enum1 = getCompositeChild(name);
                }
            }
        }
    }

    private boolean containsElements() throws DeploymentException {
        boolean contains = false;
        Enumeration enum = getSimpleChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getSimpleChild(name);
            while (enum1.hasMoreElements()) {
                SimpleNusuthWebAppElement simple = (SimpleNusuthWebAppElement) enum1.nextElement();
                if (simple.getContent() != null && simple.getContent().trim().length() > 0)
                    return true;
            }
        }
        enum = getCompositeChildrenNames();
        while (enum.hasMoreElements()) {
            String name = (String) enum.nextElement();
            Enumeration enum1 = getCompositeChild(name);
            while (enum1.hasMoreElements()) {
                CompositeNusuthWebAppElement comp = (CompositeNusuthWebAppElement) enum1.nextElement();
                contains = comp.containsElements();
                if (contains) return true;
            }
        }
        return false;
    }

    public boolean containsSimpleChild(String elementName, String content) throws DeploymentException {
        Enumeration enum = getSimpleChild(elementName);
        while (enum.hasMoreElements()) {
            SimpleNusuthWebAppElement element = (SimpleNusuthWebAppElement) enum.nextElement();
            if (element.getContent().trim().equals(content)) {
                return true;
            }
        }
        return false;
    }

    public boolean containsCompositeChild(String elementName, String elementIdName, String id) throws DeploymentException {
        Enumeration enum = getCompositeChild(elementName);
        while (enum.hasMoreElements()) {
            CompositeNusuthWebAppElement element = (CompositeNusuthWebAppElement) enum.nextElement();
            if (element.containsSimpleChild(elementIdName, id)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method return true if current element contains given composite element
     * @param element Element to find.
     * @param name Name of element
     * @return True if current element contains given composite element with
     * specified name.
     * @throws DeploymentException Throws if any errors occurs during checking
     * existence.
     */
    public boolean containsCompositeChild(CompositeNusuthWebAppElement element,
                                          String name)
            throws DeploymentException {
        Enumeration enum = getCompositeChild(name);
        while (enum.hasMoreElements()) {
            CompositeNusuthWebAppElement el
                    = (CompositeNusuthWebAppElement) enum.nextElement();
            if (el.equals(element)) {
                return true;
            }
        }
        return false;
    }

    public Enumeration getSimpleChild(String childName) throws DeploymentException {
        //XXX the additional check !?
        checkExistence(childName);
        if (simpleElements.get(childName) == null) {
            throw new DeploymentException("Child named " + childName + " is not simple");
        }
        return Collections.enumeration((List) simpleElements.get(childName));
    }


    /**This method is used to get the Enumeration of the composite sub elements with the given tag name.
     * @param childName the tag name.
     * @return Enumeration of CompositeNusuthWebAppElement classes.
     * @exception DeploymentException is thrown if the diven name is not the name of the composite element or it is not the permitted name for the sub element of this composite element.
     */
    public Enumeration getCompositeChild(String childName) throws DeploymentException {
        //XXX the additional check !?
        checkExistence(childName);
        if (compositeElements.get(childName) == null) {
            throw new DeploymentException("Child named " + childName + " is not composite");
        }
        return Collections.enumeration((List) compositeElements.get(childName));
    }


    /**
     * @param childName the sub element tag name.
     * @exception DeploymentException  is thrown if the given name is not the tag name of some sub element of this composite element or it is not the permitted name for the sub element of this composite element.
     * @return True if the element with the given name is the requited subelement of this composite element, otherwise it returns False.
     */
    public boolean isChildRequired(String childName) throws DeploymentException {
        checkExistence(childName);
        Inclusion incl = (Inclusion) innerDTDTable.get(childName);
        return incl.isRequired();
    }


    /**
     * @param childName the sub element tag name.
     * @exception DeploymentException  is thrown if the given name is not the tag name of the sub element of this composite element or it is not the permitted name for the sub element of this composite element.
     * @return True if the element with the given name is unbounded it means that there can be any number of such elements, otherwise it returns False.
     */
    public boolean isChildUnbounded(String childName) throws DeploymentException {
        checkExistence(childName);
        Inclusion incl = (Inclusion) innerDTDTable.get(childName);
        return incl.isUnbounded();
    }


    /**This method adds the new simple element with the given name to this composite element.
     * @param childName the name of the elements tag.
     * @exception DeploymentException is thrown if such exists and if it is not unbounded or it is not the permitted name for the sub element of this composite element.
     * @return the added element of the SimpleNusuthWebAppElement class type.
     */
    public SimpleNusuthWebAppElement addSimpleChild(String childName) throws DeploymentException {
        checkExistence(childName);
        if (!isChildUnbounded(childName)) {
            throw new DeploymentException("Child named " + childName + " is bounded by 1, use set instead");
        }
        SimpleNusuthWebAppElement res = new SimpleNusuthWebAppElement(childName, getDepth() + 1);
        List sList = (List) simpleElements.get(childName);
        if (sList == null) {
            sList = new ArrayList();
            simpleElements.put(childName, sList);
        }
        sList.add(res);
        return res;
    }


    /**This method adds the new compsite element with the given name to this composite element.
     * @param childName the name of the elements tag.
     * @exception DeploymentException is thrown if such exists and if it is not unbounded or it is not the permitted name for the sub element of this composite element.
     * @return the added element of the CompositeNusuthWebAppElement class type.
     */
    public CompositeNusuthWebAppElement addCompositeChild(String childName) throws DeploymentException {
        checkExistence(childName);
        if (!isChildUnbounded(childName)) {
            throw new DeploymentException("Child named " + childName + " is bounded by 1, use set instead");
        }
        CompositeNusuthWebAppElement res = new CompositeNusuthWebAppElement(type, childName, getDepth() + 1);
        List sList = (List) compositeElements.get(childName);
        if (sList == null) {
            sList = new ArrayList();
            compositeElements.put(childName, sList);
        }
        sList.add(res);
        return res;
    }

    public Object clone() {
        try {
            CompositeNusuthWebAppElement result = new CompositeNusuthWebAppElement(type, getTag(), getDepth());
            Enumeration enum = getSimpleChildrenNames();
            while (enum.hasMoreElements()) {
                String name = (String) enum.nextElement();
                Enumeration enum1 = getSimpleChild(name);
                while (enum1.hasMoreElements()) {
                    SimpleNusuthWebAppElement simple = (SimpleNusuthWebAppElement) enum1.nextElement();
                    if (isChildUnbounded(name)) {
                        SimpleNusuthWebAppElement simple1 = result.addSimpleChild(name);
                        simple1.setContent(simple.getContent());
                    } else {
                        SimpleNusuthWebAppElement simple1 = result.setSimpleChild(name);
                        simple1.setContent(simple.getContent());
                    }
                }
            }
            enum = getCompositeChildrenNames();
            while (enum.hasMoreElements()) {
                String name = (String) enum.nextElement();
                Enumeration enum1 = getCompositeChild(name);
                while (enum1.hasMoreElements()) {
                    CompositeNusuthWebAppElement comp = (CompositeNusuthWebAppElement) enum1.nextElement();
                    result.addCompositeChild(name, (CompositeNusuthWebAppElement) comp.clone());
                }
            }
            return result;
        } catch (DeploymentException e) {
            return null;
        }
    }

    /**This method removes the simple sub element with the given name from this composite element.
     * @param childName the tag name of the simple element that will be removed.
     * @param element the simple element that will be removed.
     * @exception DeploymentException is thrown if this element can not be removed or it is not the permitted name for the sub element of this composite element.
     * @return  True if this element is successfully removed , otherwise False.
     */
    public boolean removeSimpleChild(String childName, SimpleNusuthWebAppElement element) throws DeploymentException {
        checkExistence(childName);
        List sList = (List) simpleElements.get(childName);
        if (sList == null) {
            return false;
        }
        if (isChildRequired(childName) && sList.size() == 1) {
            throw new DeploymentException("Child named " + childName + " required, cannot remove last occurence");
        }
        return sList.remove(element);
    }


    public void addCompositeChild(String childName, CompositeNusuthWebAppElement element) throws DeploymentException {
        checkExistence(childName);
        List sList = (List) compositeElements.get(childName);
        sList.add(element);
    }

    /**This method removes the composite sub element with the given name from this composite element.
     * @param childName the tag name of the composite element that will be removed.
     * @param element the composite element that will be removed.
     * @exception DeploymentException is thrown if this element can not be removed or it is not the permitted name for the sub element of this composite element.
     * @return  True if this element is successfully removed , otherwise False.
     */
    public boolean removeCompositeChild(String childName, CompositeNusuthWebAppElement element) throws DeploymentException {
        checkExistence(childName);
        List sList = (List) compositeElements.get(childName);
        if (sList == null) {
            return false;
        }
        if (isChildRequired(childName) && sList.size() == 1) {
            throw new DeploymentException("Child named " + childName + " required, cannot remove last occurence");
        }
        return sList.remove(element);
    }


    /**This method sets the new simple element with the given tag name.
     * @param childName the tag name of the new element.
     * @exception DeploymentException is thrown if this is the tag name of the unbounded element or if it is not the tag name of the simple element or it is not the permitted name for the sub element of this composite element.
     * @return the created element of SimpleNusuthWebAppElement class type.
     */
    public SimpleNusuthWebAppElement setSimpleChild(String childName) throws DeploymentException {
        checkExistence(childName);
        if (isChildUnbounded(childName)) {
            throw new DeploymentException("Child named " + childName + " is unbounded, use add instead");
        }
        List sList = (List) simpleElements.get(childName);
        if (sList == null) {
            throw new DeploymentException("Child named " + childName + " is not simple");
        }
        Inclusion incl = (Inclusion) innerDTDTable.get(childName);
        List list = incl.getChoiceLinks();
        if (list != null) {
            Iterator iter = list.iterator();
            List tmpList;
            String linkName;
            while (iter.hasNext()) {
                linkName = (String) iter.next();
                tmpList = (List) simpleElements.get(linkName);
                if (tmpList == null) {
                    tmpList = (List) compositeElements.get(linkName);
                }
                tmpList.clear();
            }
        }
        SimpleNusuthWebAppElement res = new SimpleNusuthWebAppElement(childName, getDepth() + 1);
        sList.clear();
        sList.add(res);
        return res;
    }


    /**This method sets the new composite element with the given tag name.
     * @param childName the tag name of the new element.
     * @exception DeploymentException is thrown if this is the tag name of the unbounded element or if it is not the tag name of the simple element or it is not the permitted name for the sub element of this composite element.
     * @return the created element of CompositeNusuthWebAppElement class type.
     */
    public CompositeNusuthWebAppElement setCompositeChild(String childName) throws DeploymentException {
        checkExistence(childName);
        if (isChildUnbounded(childName)) {
            throw new DeploymentException("Child named " + childName + " is unbounded, use add instead");
        }
        List sList = (List) compositeElements.get(childName);
        if (sList == null) {
            throw new DeploymentException("Child named " + childName + " is not composite");
        }
        Inclusion incl = (Inclusion) innerDTDTable.get(childName);
        List list = incl.getChoiceLinks();
        if (list != null) {
            Iterator iter = list.iterator();
            List tmpList;
            String linkName;
            while (iter.hasNext()) {
                linkName = (String) iter.next();
                tmpList = (List) simpleElements.get(linkName);
                if (tmpList == null) {
                    tmpList = (List) compositeElements.get(linkName);
                }
                tmpList.clear();
            }
        }
        CompositeNusuthWebAppElement res = new CompositeNusuthWebAppElement(type, childName, getDepth() + 1);
        sList.clear();
        sList.add(res);
        return res;
    }


    public String compose(String doctype, String systemId) {
        StringBuffer sb = new StringBuffer();
        sb.append("<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\r\n\r\n");
        sb.append("<!DOCTYPE " + doctype + " SYSTEM \"" + systemId + "\">\r\n\r\n");
        sb.append(toString());
        return sb.toString();
    }


    /**This method creates string from the composite element information. Needed for serialization.
     * When we wont to save the changed xml configuration of the web application in the xml file.
     * @return string which contains the formatted xml representation of this composite element.
     */
    public String toString() {
        StringBuffer sb = new StringBuffer();
        char[] tmp = null;
        if (getDepth() > 0) {
            tmp = new char[getDepth() * 2];
            Arrays.fill(tmp, ' ');
            sb.append(tmp);
        }
        sb.append("<" + getTag() + (getID() == null ? ">\r\n" : " id=\"" + getID() + "\">\r\n"));
        Object[] entries = innerDTDTable.entrySet().toArray();
        Arrays.sort(entries, new InclusionComparator());
        Enumeration children;
        for (int i = 0; i < entries.length; i++) {
            try {
                children = getSimpleChild((String) ((Map.Entry) entries[i]).getKey());
                while (children.hasMoreElements()) {
                    sb.append(children.nextElement().toString());
                }
            } catch (DeploymentException dex) {
            }
            try {
                children = getCompositeChild((String) ((Map.Entry) entries[i]).getKey());
                while (children.hasMoreElements()) {
                    sb.append(children.nextElement().toString());
                }
            } catch (DeploymentException dex) {
            }
        }
        /*    Enumeration en1 = getSimpleChildrenNames();
         Enumeration en2;
         while (en1.hasMoreElements()) {
         try {
         en2 = getSimpleChild((String)en1.nextElement());
         } catch(DeploymentException dex) {
         throw new IllegalStateException("Internal error occurs, nested: "+dex);
         }
         while (en2.hasMoreElements()) {
         sb.append(en2.nextElement().toString());
         }
         }
         en1 = getCompositeChildrenNames();
         while (en1.hasMoreElements()) {
         try {
         en2 = getCompositeChild((String)en1.nextElement());
         } catch(DeploymentException dex) {
         throw new IllegalStateException("Internal error occurs, nested: "+dex);
         }
         while (en2.hasMoreElements()) {
         sb.append(en2.nextElement().toString());
         }
         }*/
        if (getDepth() > 0) {
            sb.append(tmp);
        }
        sb.append("</" + getTag() + ">\r\n");
        return sb.toString();
    }


    /**This method sets the HashTable that contains the nesting information of the elements in the xml configuration file .
     * In this table any complex element name is associated with the set of names of it's sub elements.
     * @param newDTDTable this is the HashTable that contains the nesting information of the elements in the xml configuration file .
     */
    static void addDTDTable(String type, Hashtable newDTDTable) {
        dtdTables.put(type, newDTDTable);
    }


    /**This method checks if the given name is the tag name of the sub element of this composite element.
     * @param childName the tag name that this method should check.
     * @exception DeploymentException is thrown if the given name it is not the permitted name for the sub element of this composite element.
     */
    private void checkExistence(String childName) throws DeploymentException {
        if (innerDTDTable.get(childName) == null) {
            throw new DeploymentException("Child named " + childName + " not contained in dtd");
        }
    }


    /**This method is used to get the tag names from the choice list of this element
     * (if exists, the choice list includes the tag name this element).
     * If this element doesn't have the choice list then the empty Enumeration is returned.
     * @param the tag name of sub element.
     * @exception DeploymentException is thrown if the given name it is not the permitted name for the sub element of this composite element.
     * @return the enumeration of Strings - contains the tag names from the choice list.
     */
    public Enumeration getChildChoices(String childName) throws DeploymentException {
        checkExistence(childName);
        Inclusion incl = (Inclusion) innerDTDTable.get(childName);
        return incl.hasChoice() ? Collections.enumeration(incl.getChoiceLinks()) : new Enumeration() {
            public boolean hasMoreElements() {
                return false;
            }

            public Object nextElement() {
                return null;
            }
        };
    }

    public boolean equals(Object obj) {
        if (obj instanceof CompositeNusuthWebAppElement && super.equals(obj)) {
            try {
                CompositeNusuthWebAppElement other = (CompositeNusuthWebAppElement) obj;
                Enumeration names = other.getCompositeChildrenNames();
                while (names.hasMoreElements()) {
                    String name = (String) names.nextElement();
                    Enumeration enum = other.getCompositeChild(name);
                    List children = (List) compositeElements.get(name);
                    int count = 0;
                    while (enum.hasMoreElements()) {
                        CompositeNusuthWebAppElement composite = (CompositeNusuthWebAppElement) enum.nextElement();
                        if (!children.contains(composite)) {
                            return false;
                        }
                        count++;
                    }
                    if (count != children.size()) {
                        return false;
                    }
                }
                names = other.getSimpleChildrenNames();
                while (names.hasMoreElements()) {
                    String name = (String) names.nextElement();
                    Enumeration enum = other.getSimpleChild(name);
                    List children = (List) simpleElements.get(name);
                    int count = 0;
                    while (enum.hasMoreElements()) {
                        SimpleNusuthWebAppElement simple = (SimpleNusuthWebAppElement) enum.nextElement();
                        if (!children.contains(simple)) {
                            return false;
                        }
                        count++;
                    }
                    if (count != children.size()) {
                        return false;
                    }
                }
                return true;
            } catch (DeploymentException e) {
                return false;
            }
        }
        return false;
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        out.writeObject(type);
        out.writeObject(compose(type, ""));
    }

    private void readObject(ObjectInputStream in)
            throws IOException, ClassNotFoundException {
        String xmlType = (String) in.readObject();
        String xml = (String) in.readObject();
        CompositeNusuthWebAppElement conf
                = null;
        try {
            conf = NusuthAppConfigFactory.
                    createConfig(xmlType, new ByteArrayInputStream(xml.getBytes()));
        } catch (ParserException e) {
//e.printStackTrace();
            conf = null;
        }
        compositeElements = conf.compositeElements;
        dtdTable = conf.dtdTable;
        innerDTDTable = conf.innerDTDTable;
        simpleElements = conf.simpleElements;
        type = conf.type;
        depth = conf.depth;
        ID = conf.ID;
        node = conf.node;
        tag = conf.tag;
    }

    class InclusionComparator implements Comparator {

        public int compare(Object o1, Object o2) {
            if (!(o1 instanceof Map.Entry && o2 instanceof Map.Entry)) {
                return 0;
            }
            Inclusion inc1 = null;
            Inclusion inc2 = null;
            try {
                inc1 = (Inclusion) ((Map.Entry) o1).getValue();
                inc2 = (Inclusion) ((Map.Entry) o2).getValue();
            } catch (ClassCastException cce) {
                return 0;
            }
            return inc1.getOrder() - inc2.getOrder();
        }
    }
}
