/* Generated by VDGG */

package com.azoft.nusuth.deployment;

import org.xml.sax.*;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class ContainerEntityResolver implements EntityResolver {


    public ContainerEntityResolver() {
        super();
    }


    public InputSource resolveEntity(String publicId, String systemId) {
        return new InputSource(getClass().getClassLoader().getResourceAsStream("com/azoft/nusuth/deployment/container.dtd"));
    }
}