/* Generated by VDGG */

package com.azoft.nusuth.deployment;

/* Generated by VDGG */

/**This exception is thrown if any error occures while working with
 * the tree representation of the xml configuration file.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class DeploymentException extends Exception {


    public DeploymentException() {
        super();
    }


    /**
     * @param message that describes the exception.
     */
    public DeploymentException(String message) {
        super(message);
    }
}