/* Generated by VDGG */

package com.azoft.nusuth.deployment;

import java.util.*;
import java.io.Serializable;

/**This class is used to hold some element information such as : if it is required element,
 * if it is unbouned element and the choice links.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
class Inclusion implements Serializable {
    private int order;
    private boolean required;
    private boolean unbounded;
    private List choiceLinks;


    /**Constructor of the Inclusion class.
     * @param required True if the associated element is the required element,otherwise False.
     * @param unbounded True if there may be any number of such elements, otherwise False.
     */
    Inclusion(int order, boolean required, boolean unbounded) {
        this(order, required, unbounded, null);
    }


    /**Constructor of the Inclusion class.
     * @param required True if the associated element is the required element,otherwise False.
     * @param unbounded True if there may be any number of such elements, otherwise False.
     * @param choiceLinks the list of choice , contains the tag names of the elements.
     */
    Inclusion(int order, boolean required, boolean unbounded, List choiceLinks) {
        this.order = order;
        this.required = required;
        this.unbounded = unbounded;
        this.choiceLinks = choiceLinks;
    }


    /**
     * @return True if this is required element, otherwise false.
     */
    boolean isRequired() {
        return required;
    }


    /**
     * @return true if this is unbouned element, it means that there can be any number of such elements.
     */
    boolean isUnbounded() {
        return unbounded;
    }


    /**
     * @return True if there is a choice list for this element.
     */
    boolean hasChoice() {
        return choiceLinks != null;
    }


    /**
     * @return List of Strings(tag names)-the choise list for this element.
     */
    List getChoiceLinks() {
        return choiceLinks;
    }


    int getOrder() {
        return order;
    }
}