/* Generated by VDGG */

package com.azoft.nusuth.deployment;

import java.io.*;
import java.util.*;
import java.net.URL;

import org.apache.xerces.parsers.DOMParser;
import org.w3c.dom.*;
import org.xml.sax.*;

/**This method is used to create the tree representation of the xml
 * configuration file of the web application , depending on the xml
 * schema and dtd.
 * @author vdgg, skilz
 * @version 1.8
 * @since Nusuth1.0
 */
abstract public class NusuthAppConfigFactory {
    private static Hashtable dtdTables = new Hashtable();
    private static Hashtable resolvers = new Hashtable();
    private static ErrorHandler errorHandler = new WebErrorHandler();


    /**This method opens and parses the deployment descriptor file(xml configuration file) of the web application .
     * It also parses the xml scheme file which contains the dtd information for the xml configuration file.
     * @param systemId the platform independent path to the root folder of the web application.
     * @return the root composite element of the xml configuration file tree representation.
     * @exception ParserException is thrown if it cannnot get the full path to the deployment descriptor file or if it can't open it.
     */
    public static CompositeNusuthWebAppElement createConfig(String type, String systemId) throws ParserException {
        String fullPath = null;
        try {
            fullPath = (new File(systemId)).getCanonicalPath();
        } catch (IOException ioex) {
            //      ioex.printStackTrace();
            throw new ParserException("Cannot get full path for " + systemId + ", nested: " + ioex.getMessage());
        }
        try {
            return createConfig(type, (new File(fullPath)).toURL());
        } catch (IOException ioex) {
            throw new ParserException("Cannot open " + fullPath + ", nested: " + ioex.getMessage());
        }
    }

    /**This method opens and parses the deployment descriptor file(xml configuration file) of the web application .
     * @param url the url to the deployment descriptior.
     * @return the root composite element of the xml configuration file tree representation.
     * @exception ParserException is thrown if it cannnot get the full path to the deployment descriptor file or if it can't open it.
     */
    public static CompositeNusuthWebAppElement createConfig(String type, URL url) throws ParserException {
        try {
            return createConfig(type, url.openStream());
        } catch (IOException e) {
            throw new ParserException("Cannot open stream from url " + url);
        }
    }


    /**This method parses the deployment descriptor file(xml configuration file) of the web application .
     * It also parses the xml scheme file which contains the dtd information for the xml configuration file.
     * @param stream the input stream binded with the deployment descriptor file (xml configuration file) of the web application.
     * @return the root composite object of the xml configuration file tree representation.
     * @throw ParserException  is thrown if parser doesn't support necessary features or some problem occures while reading the xml configuration file or the format of the xml configuretion file is incorrect.
     */
    public static CompositeNusuthWebAppElement createConfig(String type, InputStream stream) throws ParserException {
        return createConfig(type, new InputSource(stream));
    }


    /**This method parses the deployment descriptor file(xml configuration file) of the web application.
     *  It also parses the xml scheme file which contains the dtd information for the xml configuration file.
     * @param source the org.xml.sax.InputSource class object binded with the xml configuration file.
     * @return the root composite object of the xml configuration file tree representation.
     * @throw ParserException is thrown if parser doesn't support necessary features or some problem occures while reading the xml configuration file or the format of the xml configuretion file is incorrect.
     */
    public static CompositeNusuthWebAppElement createConfig(String type,
                                                            InputSource source)
            throws ParserException {
        DOMParser parser = new DOMParser();
        //Checks if parser supports necessary features.
        if (resolvers.get(type) != null) {
            parser.setEntityResolver((EntityResolver) resolvers.get(type));
        }
        try {
            parser.setFeature("http://xml.org/sax/features/validation", true);
        } catch (Exception ex) {
            throw new ParserException("XML parser not supports necessary features, "
                    + "nested: " + ex.getMessage());
        }

        try {
            parser.setFeature("http://xml.org/sax/features/namespaces", false);
        } catch (Exception ex) {
            throw new ParserException("Cannot disable feature, nested: "
                    + ex.getMessage());
        }

        if (dtdTables.get(type) == null) {
            try {
                parser.setFeature("http://apache.org/xml/features/domx/grammar-access",
                        true);
            } catch (Exception ex) {
                throw new ParserException("XML parser not supports necessary features, "
                        + "nested: " + ex.getMessage());
            }
        }
        //Parses the xml configuration file.
        try {

            if (dtdTables.get(type) == null) {
                parser.parse(new InputSource(
                        NusuthAppConfigFactory.class.getClassLoader().
                        getResourceAsStream("com/azoft/nusuth/deployment/"
                        + type + ".xml")));
                Document document = parser.getDocument();
                init(type, document.getDoctype());
            }

            parser.parse(source);
        } catch (Exception ex) {
            throw new ParserException("Error while parsing document, nested: "
                    + ex.getMessage());
        }
        Document document = parser.getDocument();
        NodeList nList = document.getElementsByTagName(type);
        if (nList.getLength() != 1) {
            throw new ParserException("In deployment descriptor file must be one "
                    + "and only one definition of web application");
        }
        Node node = nList.item(0);
        try {
            //Makes the configuration tree, that reflects the xml configuration file.
            CompositeNusuthWebAppElement elem
                    = new CompositeNusuthWebAppElement(type, node, 0);
            elem.validate(elem.getNode());
            return elem;
        } catch (DeploymentException ex) {
            throw new ParserException("Cannot create config, nested: " + ex);
        }
    }


    /**This method parses the xml schema file that represents the dtd for the web application xml
     * configuration file and creates the HashTable which reflects the nesting of the elements.
     * It also gets the additional information about elements : if it is required element, if it is unbounded element, and the list of choice(contains the tag names of the elements).
     * @param root the root node of the xml configuration file.
     * @exception ParserException is thrown if it cannot find schema node in the xml configuration file or if any parser error occures.
     */
    public static void init(String type, Node root) throws ParserException {
        Hashtable dtdTable = new Hashtable();
        dtdTables.put(type, dtdTable);
        Node node = root.getFirstChild();
        while (node != null && !node.getNodeName().equals("schema")) {
            node = node.getNextSibling();
        }
        if (node == null) {
            dtdTable = null;
            throw new ParserException("Cannot find schema node in dtd");
        }
        NodeList lst = node.getChildNodes();
        NodeList tmpList;
        String name;
        Hashtable tmpHash;
        NamedNodeMap map;
        Node tmpNode;
        List mList;
        for (int i = 0; i < lst.getLength(); i++) {
            node = lst.item(i);
            if (node.getNodeName().equals("element")) {
                name = node.getAttributes().getNamedItem("name").getNodeValue();
                node = node.getFirstChild();
                while (node != null && !node.getNodeName().equals("complexType")) {
                    node = node.getNextSibling();
                }
                if (node != null) {
                    node = node.getFirstChild();
                    while (node != null && !(node.getNodeName().equals("sequence") || node.getNodeName().equals("element"))) {
                        node = node.getNextSibling();
                    }
                    if (node != null) {
                        tmpHash = new Hashtable();
                        dtdTable.put(name, tmpHash);
                        if (node.getNodeName().equals("sequence")) {
                            tmpList = node.getChildNodes();
                            for (int j = 0; j < tmpList.getLength(); j++) {
                                node = tmpList.item(j);
                                if (node.getNodeName().equals("element")) {
                                    map = node.getAttributes();
                                    tmpHash.put(map.getNamedItem("ref").getNodeValue(), new Inclusion(j, map.getNamedItem("minOccurs") == null, map.getNamedItem("maxOccurs") != null));
                                } else if (node.getNodeName().equals("choice")) {
                                    tmpNode = node.getFirstChild();
                                    mList = new ArrayList();
                                    while (tmpNode != null) {
                                        if (tmpNode.getNodeName().equals("element")) {
                                            map = tmpNode.getAttributes();
                                            mList.add(map.getNamedItem("ref").getNodeValue());
                                            tmpHash.put(map.getNamedItem("ref").getNodeValue(), new Inclusion(j, true, false, mList));
                                        }
                                        tmpNode = tmpNode.getNextSibling();
                                    }
                                }
                            }
                        } else {
                            if (node.getNodeName().equals("element")) {
                                map = node.getAttributes();
                                tmpHash.put(map.getNamedItem("ref").getNodeValue(), new Inclusion(0, map.getNamedItem("minOccurs") == null, map.getNamedItem("maxOccurs") != null));
                            } else if (node.getNodeName().equals("choice")) {
                                tmpNode = node.getFirstChild();
                                mList = new ArrayList();
                                while (tmpNode != null) {
                                    if (tmpNode.getNodeName().equals("element")) {
                                        map = tmpNode.getAttributes();
                                        mList.add(map.getNamedItem("ref").getNodeValue());
                                        tmpHash.put(map.getNamedItem("ref").getNodeValue(), new Inclusion(0, true, false, mList));
                                    }
                                    tmpNode = tmpNode.getNextSibling();
                                }
                            }
                        }
                    }
                }
            }
        }
        CompositeNusuthWebAppElement.addDTDTable(type, dtdTable);
    }


    public static void addEntityResolver(String type, EntityResolver resolver) {
        resolvers.put(type, resolver);
    }
}