/*Generated by VDGG*/

package com.azoft.nusuth.deployment;

/*Generated by VDGG*/

/**
 * This interface contains tags of all elements defined in Sun's data type definition document for web application.
 * @version 1.0
 * @author VDGG (vdgg@azoft.com)
 * @since 1.0*/
public interface Tags {
    final static String WEB_APP = "web-app";
    final static String ICON = "icon";
    final static String SMALL_ICON = "small-icon";
    final static String LARGE_ICON = "large-icon";
    final static String DISPLAY_NAME = "display-name";
    final static String DESCRIPTION = "description";
    final static String DISTRIBUTABLE = "distributable";
    final static String CONTEXT_PARAM = "context-param";
    final static String PARAM_NAME = "param-name";
    final static String PARAM_VALUE = "param-value";
    final static String SERVLET = "servlet";
    final static String SERVLET_NAME = "servlet-name";
    final static String SERVLET_CLASS = "servlet-class";
    final static String JSP_FILE = "jsp-file";
    final static String INIT_PARAM = "init-param";
    final static String LOAD_ON_STARTUP = "load-on-startup";
    final static String SERVLET_MAPPING = "servlet-mapping";
    final static String URL_PATTERN = "url-pattern";
    final static String SESSION_CONFIG = "session-config";
    final static String SESSION_TIMEOUT = "session-timeout";
    final static String MIME_MAPPING = "mime-mapping";
    final static String EXTENSION = "extension";
    final static String MIME_TYPE = "mime-type";
    final static String WELCOME_FILE_LIST = "welcome-file-list";
    final static String WELCOME_FILE = "welcome-file";
    final static String TAGLIB = "taglib";
    final static String TAGLIB_URI = "taglib-uri";
    final static String TAGLIB_LOCATION = "taglib-location";
    final static String ERROR_PAGE = "error-page";
    final static String ERROR_CODE = "error-code";
    final static String EXCEPTION_TYPE = "exception-type";
    final static String LOCATION = "location";
    final static String RESOURCE_REF = "resource-ref";
    final static String RES_REF_NAME = "res-ref-name";
    final static String RES_TYPE = "res-type";
    final static String RES_AUTH = "res-auth";
    final static String SECURITY_CONSTRAINT = "security-constraint";
    final static String WEB_RESOURCE_COLLECTION = "web-resource-collection";
    final static String WEB_RESOURCE_NAME = "web-resource-name";
    final static String HTTP_METHOD = "http-method";
    final static String USER_DATA_CONSTRAINT = "user-data-constraint";
    final static String TRANSPORT_GUARANTEE = "transport-gurantee";
    final static String AUTH_CONSTRAINT = "auth-constraint";
    final static String ROLE_NAME = "role-name";
    final static String LOGIN_CONFIG = "login-config";
    final static String REALM_NAME = "realm-name";
    final static String FORM_LOGIN_CONGIG = "form-login-config";
    final static String FORM_LOGIN_PAGE = "form-login-page";
    final static String FORM_ERROR_PAGE = "form-error-page";
    final static String AUTH_METHOD = "auth-method";
    final static String SECURITY_ROLE = "security-role";
    final static String SECURITY_ROLE_REF = "security-role-ref";
    final static String ROLE_LINK = "role-link";
    final static String ENV_ENTRY = "env-entry";
    final static String ENV_ENTRY_NAME = "env-entry-name";
    final static String ENV_ENTRY_VALUE = "env-entry-value";
    final static String ENV_ENTRY_TYPE = "env-entry-type";
    final static String EJB_REF = "ejb-ref";
    final static String EJB_REF_NAME = "ejb-ref-name";
    final static String EJB_REF_TYPE = "ejb-ref-type";
    final static String HOME = "home";
    final static String REMOTE = "remote";
    final static String EJB_LINK = "ejb-link";
    final static String FILTER = "filter";
    final static String FILTER_NAME = "filter-name";
    final static String FILTER_CLASS = "filter-class";
    final static String FILTER_MAPPING = "filter-mapping";
    final static String LISTENER = "listener";
    final static String LISTENER_CLASS = "listener-class";
}