/* Generated by VDGG */

package com.azoft.nusuth.deployment;

import org.xml.sax.*;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class WebErrorHandler implements ErrorHandler {

    private org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.deployment");


    public WebErrorHandler() {
        super();
    }


    public void warning(SAXParseException ex) throws SAXException {
        cat.error("Error while parsing", ex);
        throw new SAXException("Fatal parser error: " + ex);
    }


    public void error(SAXParseException ex) throws SAXException {
        cat.error("Error while parsing", ex);
        throw new SAXException("Fatal parser error: " + ex);
    }


    public void fatalError(SAXParseException ex) throws SAXException {
        cat.error("Error while parsing", ex);
        throw new SAXException("Fatal parser error: " + ex);
    }
}