/* Generated by VDGG */

package com.azoft.nusuth.deployment;

import org.xml.sax.*;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class WebEntityResolver implements EntityResolver {


    public WebEntityResolver() {
        super();
    }


    public InputSource resolveEntity(String publicId, String systemId) {
        return new InputSource(getClass().getClassLoader().getResourceAsStream("com/azoft/nusuth/deployment/web.dtd"));
    }
}