package com.azoft.nusuth.distributor;/* Generated by VDGG */

import com.azoft.nusuth.container.http.HttpProtocolAdapter;
import com.azoft.nusuth.core.*;
import com.azoft.nusuth.distributor.cache.CachedElement;
import com.azoft.nusuth.gui.Base64;
import com.azoft.nusuth.util.*;

import javax.net.ssl.SSLPeerUnverifiedException;
import javax.net.ssl.SSLSocket;
import javax.security.cert.CertificateEncodingException;
import javax.security.cert.X509Certificate;
import javax.servlet.http.Cookie;
import java.io.*;

/**
 * This class represents methods for process client requests.
 *
 * @author VDGG
 * @author IgorK
 * @author Skillz
 * @version 1.11
 * @see DistributorRequestAdapter
 * @see DistributorRequestHandler
 * @since JBird 1.0
 */
public class HttpDistributorRequestAdapter
        extends DistributorRequestAdapter
        implements FlushListener {
    protected HttpRequestLine requestLine = new HttpRequestLine();
    protected HttpNusuthServletInputStream clientHSIS = new HttpNusuthServletInputStream(null);
    protected HttpNusuthServletInputStream containerHSIS = new HttpNusuthServletInputStream(null);

    private final static char[] HTTP1 = "HTTP/1.".toCharArray();
    private final static char[] HTTP11 = "HTTP/1.1".toCharArray();
    private final static StrBuffer OK_RESPONSE_LINE = new StrBuffer();
    private final static StrBuffer NOT_MODIFIED_RESPONSE_LINE = new StrBuffer();
    private final static char[] HTTP_RESPONSE_CODE_304 = "304".toCharArray();
    private final static String HTTP_LAST_MODIFIED = new String(HttpConstants.LAST_MODIFIED);
    private final static String HTTP_IF_MODIFIED_SINCE = new String(HttpConstants.IF_MODIFIED_SINCE);
    private final static String HTTP_CONTENT_LENGTH = new String(HttpConstants.CONTENT_LENGTH);

    protected NusuthHeaders requestHeaders = new NusuthHeaders();
    protected NusuthHeaders responseHeaders = new NusuthHeaders();
    protected NusuthHeaders cachedHeaders;

    private final static String CONTAINER_COOKIE_NAME = "JCONTAINERID";
    private final static String SESSION_COOKIE_NAME = "JSESSIONID";

    private boolean responseIsCacheable = false;
    private long requestModifiedSince = 0;

    private byte[] clientCertificate = null;

    static {
        OK_RESPONSE_LINE.append("HTTP/1.1 200 OK\r\n");
        NOT_MODIFIED_RESPONSE_LINE.append("HTTP/1.1 304 Not Modified\r\n");
    }

    /** Cleanups adapter for new connection. Creation date: (22.11.00 12:10:06) */
    public void cleanup() {
        super.cleanup();
        CIS.cleanup();
        FIS.cleanup();
        partiallyCleanup();
        clientCertificate = null;
    }

    public void parseRequest()
            throws DistributorException {
        if (logProxy.isDebugEnabled())
            logger.debug("Parse request");
        state = PROCESSING_REQUEST;

        clientHSIS.init(clientIS);
        clientJSOS.init(clientOS);
        clientJSOS.setFlushListener(this);

        try {
            clientHSIS.readRequestLine(requestLine);
        } catch (InterruptedIOException inex) {
            throw new DistributorException("Client input stream timeout", inex, ERROR_BadClientSocket);
        } catch (IOException ioex) {
            throw new DistributorException(
                    "Couldn't read request line: " + requestLine.method + ' ' + requestLine.uri + '?' + requestLine.queryString + ' ' + requestLine.protocol,
                    ioex,
                    ERROR_BadClientSocket);
        }

        if (!requestLine.protocol.startsWith(HTTP1)) {
            throw new DistributorException("Wrong protocol: " + requestLine.protocol, null, ERROR_BadRequest);
        }

        try {
            requestHeaders.read(clientHSIS);
        } catch (InterruptedIOException inex) {
            throw new DistributorException("Client input stream timeout", inex, ERROR_BadClientSocket);
        } catch (IOException ioex) {
            throw new DistributorException("Error occured while processing headers", ioex, ERROR_BadClientSocket);
        }

        requestHeaders.appendHeaderValue(HttpConstants.HOST, requestURI);
        requestURI.cutToFirstChar(':', false);
        if (requestURI.length() == 0)
            requestURI.append('*');
        if (!requestLine.uri.startsWith(SLASH))
            requestURI.append('/');
        requestURI.append(requestLine.uri);

        clientKeepAlive = requestLine.protocol.equals(HTTP11) && requestHeaders.containsHeader(HttpConstants.CONNECTION, HttpConstants.KEEP_ALIVE);

        if (containerID.length() > 0)
            containerID.clear();
        Cookie[] cookies = requestHeaders.processCookies();
        if (cookies != null && cookies.length > 0) {
            boolean sFound = false;
            boolean cFound = false;
            for (int i = 0; i < cookies.length; i++) {
                Cookie cookie = cookies[i];
                if (cookie.getName().equals(CONTAINER_COOKIE_NAME)) {
                    if (!cFound)
                        containerID.append(cookie.getValue());
                    cFound = true;
                } else if (cookie.getName().equals(SESSION_COOKIE_NAME)) {
                    if (!sFound)
                        sessionID.append(cookie.getValue());
                    sFound = true;
                }

            }
        }
        requestModifiedSince = requestHeaders.getDateHeader(HTTP_IF_MODIFIED_SINCE);

        if (isSecure()) {
            SSLSocket sslSocket = (SSLSocket) clientSocket;
            if (clientCertificate == null) {
                if (sslSocket.getNeedClientAuth()) {
                    try {
                        X509Certificate[] clientCertificates = sslSocket.getSession().getPeerCertificateChain();
                        if (clientCertificates != null && clientCertificates.length > 0) {
                            clientCertificate = clientCertificates[0].getEncoded();
                        }
                    } catch (SSLPeerUnverifiedException puvex) {
                        if (logProxy.isDebugEnabled())
                            logger.debug("Couldn't get client certificate chain", puvex);
                    } catch (CertificateEncodingException ceex) {
                        if (logProxy.isDebugEnabled())
                            logger.debug("Couldn't encode client certificate", ceex);
                    }
                }
            }
            if (clientCertificate != null) {
                requestHeaders.addHeader(HttpConstants.CLIENT_CERTIFICATE_HEADER_NAME, Base64.encode(clientCertificate));
            }
        }
    }


    public void parseResponse() throws DistributorException {
        if (logProxy.isDebugEnabled())
            logger.debug("Parse response");
        try {
            state = PROCESSING_RESPONSE;
            containerHSIS.readLine(responseLine);
            getResponseCode(responseLine, responseCode);

            responseHeaders.read(containerHSIS);
            clientKeepAlive &= responseHeaders.containsHeader(HttpConstants.CONNECTION, HttpConstants.KEEP_ALIVE);
        } catch (InterruptedIOException inex) {
            throw new DistributorException("Container input stream timeout", inex, ERROR_BadContainerSocket);
        } catch (IOException ioex) {
            throw new DistributorException("Couldn't read response header", ioex, ERROR_BadContainerSocket);
        }
    }

    private static void getResponseCode(StrBuffer response_line, StrBuffer response_code) {
        response_code.clear();
        int length = response_line.length();
        int i = 0;
        while (i < length && response_line.charAt(i) != ' ')
            i++;
        if (i < length)
            for (char c = response_line.charAt(++i); c != ' ' && i < length - 1; c = response_line.charAt(++i))
                response_code.append(c);
    }

    /** Insert the method's description here. Creation date: (17.11.00 10:48:47) */
    public void partiallyCleanup() {
        requestURI.clear();
        sessionID.clear();
        plainRequestLine.clear();
        requestHeaders.clear();
        requestLine.clear();
        responseHeaders.clear();
        responseLine.clear();

        clientHSIS.cleanup();
        clientJSOS.cleanup();

        containerHSIS.cleanup();
        containerJSOS.cleanup();

        state = PROCESSING_REQUEST;
    }

    public void processRequest()
            throws DistributorException {
        if (logProxy.isDebugEnabled())
            logger.debug("Process request");
        int contentLength = 0;
        try {
            contentLength = Utils.retreiveContentLength(requestHeaders);
        } catch (IOException ioex) {
            throw new DistributorException("Couldn't retrieve request content length", ioex, ERROR_BadRequest);
        }

        if (contentLength > -1) { // fixed content length
            if (contentLength != 0) {
                FIS.init(clientHSIS, contentLength);
                processBody(FIS, containerJSOS);
                FIS.cleanup();
            }
        } else if (requestHeaders.containsHeader(HttpConstants.TRANSFER_ENCODING, HttpConstants.CHUNKED)) {
            CIS.init(clientHSIS);
            containerJSOS.setChunked(true);
            processBody(CIS, containerJSOS);
            CIS.cleanup();
        } /*else {
       if (logProxy.isDebugEnabled())
       logger.debug("Cannot define request content length");
       }*/

        try {
            containerJSOS.close();
        } catch (InterruptedIOException inex) {
            throw new DistributorException("Output stream timeout", inex, ERROR_BadContainerSocket);
        } catch (IOException ioex) {
            throw new DistributorException("Couldn't flush output stream", ioex, ERROR_BadContainerSocket);
        }
    }


    public byte[] processResponse()
            throws DistributorException {
        if (logProxy.isDebugEnabled())
            logger.debug("Process response");
        byte[] responseBody = null;
        responseIsCacheable = responseHeaders.containsHeader(FileServlet.FILE_SERVLET_HEADER_NAME) && responseHeaders.getIntHeader(HTTP_CONTENT_LENGTH) < cache.getMaxPageSize();
        responseHeaders.clearHeader(FileServlet.FILE_SERVLET_HEADER_NAME);
        boolean isResponseKeepAilve = responseHeaders.containsHeader(HttpConstants.CONNECTION, HttpConstants.KEEP_ALIVE);
        boolean isChunked = responseHeaders.containsHeader(HttpConstants.TRANSFER_ENCODING, HttpConstants.CHUNKED);
        if (isResponseKeepAilve != clientKeepAlive)
            responseHeaders.putHeader(HttpConstants.CONNECTION, clientKeepAlive ? HttpConstants.KEEP_ALIVE : HttpConstants.CLOSE);
        if (!clientKeepAlive)
            responseHeaders.clearHeader(HttpConstants.TRANSFER_ENCODING);
        if (isChunked) {
            CIS.init(containerHSIS);
            clientJSOS.setChunked(clientKeepAlive);
            responseBody = processBody(CIS, clientJSOS);
            CIS.cleanup();
        } else {
            int contentLength = -1;
            try {
                contentLength = Utils.retreiveContentLength(responseHeaders);
            } catch (IOException ioex) {
                throw new DistributorException("Couldn't retrieve response content length", ioex, ERROR_BadResponse);
            }

            if (contentLength > -1) { // fixed content length
                if (contentLength != 0) {
                    FIS.init(containerHSIS, contentLength);
                    responseBody = processBody(FIS, clientJSOS);
                    FIS.cleanup();
                }
            } else {
                throw new DistributorException("Couldn't define response content length", null, ERROR_BadResponse);
            }
        }

        try {
            clientJSOS.close();
        } catch (InterruptedIOException inex) {
            throw new DistributorException("Output stream timeout", inex, ERROR_BadClientSocket);
        } catch (IOException ioex) {
            throw new DistributorException("Couldn't flush output stream", ioex, ERROR_BadClientSocket);
        }

        return responseBody;
    }


    /** Writes request header (request line & http headers & Remote-Address header) to container socket. */
    private void writeRequestHeader() throws DistributorException {
        if (!skipRequest) {
            // create request line
            plainRequestLine.append(requestLine.method);
            plainRequestLine.append(' ');
            plainRequestLine.append(requestLine.uri);
            if (requestLine.queryString.length() > 0) {
                plainRequestLine.append('?');
                //      plainRequestLine.append(requestLine.queryString);
                plainRequestLine.append(requestLine.queryString.toString());
            }
            plainRequestLine.append(' ');
            plainRequestLine.append(requestLine.protocol);
            plainRequestLine.append('\r');
            plainRequestLine.append('\n');

            try {
                plainRequestLine.writeToOutputStream(containerJSOS);

                requestHeaders.addHeader(HttpProtocolAdapter.REMOTE_ADDR_HEADER_NAME, clientAddress);
                requestHeaders.write(containerJSOS);
            } catch (InterruptedIOException inex) {
                throw new DistributorException("Container output stream timeout", inex, ERROR_BadContainerSocket);
            } catch (IOException ioex) {
                throw new DistributorException("Couldn't write request header to container", ioex, ERROR_BadContainerSocket);
            }
        }
    }


    private void writeResponseHeader() throws DistributorException {
        try {
            responseLine.writeToOutputStream(clientJSOS);
            if (isCachedResponse && cachedHeaders != responseHeaders) {
                clientJSOS.write(HttpDate.getCurrentDateHeader());

                cachedHeaders.write(clientJSOS);
            } else {
                responseHeaders.write(clientJSOS);
            }
        } catch (InterruptedIOException inex) {
            //      throw new DistributorException("Client output stream timeout", inex, ERROR_BadClientSocket);
        } catch (IOException ioex) {
            //      throw new DistributorException("Couldn't write response header to client", ioex, ERROR_BadClientSocket);
        }
    }

    private NusuthServletOutputStream clientJSOS = new NusuthServletOutputStream(null);
    private NusuthServletOutputStream containerJSOS = new NusuthServletOutputStream(null);
    private StrBuffer plainRequestLine = new StrBuffer(128);
    private final static int PROCESSING_REQUEST = 1;
    private final static int PROCESSING_RESPONSE = 2;
    private StrBuffer responseLine = new StrBuffer(128);
    private StrBuffer responseCode = new StrBuffer(4);
    private int state = PROCESSING_REQUEST;
    private byte[] tempBuffer = new byte[2048];
    private boolean isCachedResponse = false;
    private boolean skipRequest = false;


    /**This method is called on Flush.
     */
    public void onFlush() throws IOException {
        switch (state) {
            case PROCESSING_REQUEST:
                writeRequestHeader();
                break;
            case PROCESSING_RESPONSE:
                writeResponseHeader();
                break;
        }
    }


    /**
     * Insert the method's description here.
     * Creation date: (31.01.2001 20:44:40)
     * @return int
     */
    public void process() throws DistributorException {
        containerHSIS.init(containerIS);
        containerJSOS.init(containerOS);
        containerJSOS.setFlushListener(this);

        CachedElement page = cache.getPage(requestLine.uri);
        isCachedResponse = (page != null);
        boolean isPageExpired = isCachedResponse ? cache.isPageExpired(page, requestModifiedSince) : true;
        boolean notModifiedResponseAllowed = requestHeaders.containsHeader(HttpConstants.IF_MODIFIED_SINCE);
        if (isCachedResponse && isPageExpired)
            requestHeaders.putDateHeader(HttpConstants.IF_MODIFIED_SINCE, page.getLastModified() < requestModifiedSince || requestModifiedSince == -1 ? page.getLastModified() : requestModifiedSince);

        skipRequest = isCachedResponse && !isPageExpired;
        processRequest();

        if (isCachedResponse && !isPageExpired) {
            processCachedResponse(page, notModifiedResponseAllowed && page.getLastModified() <= requestModifiedSince);
            cache.touchPage(page);
        } else {
            parseResponse();
            cachedHeaders = responseHeaders;
            boolean isNotModifiedResponse = responseCode.equals(HTTP_RESPONSE_CODE_304);
            if (isNotModifiedResponse && !notModifiedResponseAllowed) {
                processMergedResponse(page);
                page.setLastChecked();
                cache.touchPage(page);
            } else {
                byte[] body = processResponse();
                if (responseIsCacheable) {
                    try {
                        cache.putPage(requestLine.uri, responseHeaders, body);
                    } catch (IOException ioex) {
                        logger.warn("Couldn't put page \"" + requestLine.uri + "\" to cache", ioex);
                    }
                } else if (isCachedResponse && isNotModifiedResponse) {
                    long lastMod = page.getHeaders().getDateHeader(HTTP_LAST_MODIFIED);
                    if (lastMod != -1)
                        page.setLastModified(lastMod);
                    page.setLastChecked();
                    cache.touchPage(page);
                } else if (isCachedResponse) {
                    cache.removePage(page);
                }
            }
        }
    }


    protected byte[] processBody(NusuthServletInputStream in, OutputStream out)
            throws DistributorException {
        byte[] body = state == PROCESSING_RESPONSE && responseIsCacheable ? new byte[0] : null;
        for (int readed = 0; readed > -1;) {
            try {
                readed = in.read(tempBuffer);
            } catch (InterruptedIOException inex) {
                throw new DistributorException("Input stream timeout", inex, (state == PROCESSING_REQUEST ? ERROR_BadClientSocket : ERROR_BadContainerSocket));
            } catch (IOException ioex) {
                throw new DistributorException("Exception in processBody", ioex, (state == PROCESSING_REQUEST ? ERROR_BadClientSocket : ERROR_BadContainerSocket));
            }
            if (readed > 0) {
                if (responseIsCacheable && state == PROCESSING_RESPONSE) {
                    byte[] tmp = body;
                    body = new byte[body.length + readed];
                    System.arraycopy(tmp, 0, body, 0, tmp.length);
                    System.arraycopy(tempBuffer, 0, body, tmp.length, readed);
                }

                if (state == PROCESSING_RESPONSE || !skipRequest) {
                    try {
                        out.write(tempBuffer, 0, readed);
                    } catch (IOException ioex) {
                        if (state == PROCESSING_RESPONSE && readed > -1)
                            readAllFromContainer(in);
                        throw new DistributorException(
                                ioex instanceof InterruptedIOException ? "Stream timeout" : "Exception in processBody",
                                ioex,
                                state == PROCESSING_REQUEST ? ERROR_BadContainerSocket : ERROR_BadClientSocket);
                    }
                }
            }
        }
        return body;
    }


    /**
     *This method  generates and sends the Error response with the error message which depends on the given error code.
     * @param sc the error code.
     */
    public void processError(int errorCode, String message) {
        int httpErr = 0;
        switch (errorCode) {
            case OK:
                return;
            case ERROR_BadClientSocket:
                return;
            case ERROR_BadRequest:
                httpErr = 400;
                break;
            case ERROR_NotFound:
                httpErr = 404;
                break;
            default :
                httpErr = 500;
                break;
        }

        try {
            if (logProxy.isDebugEnabled())
                logger.debug("Sending http error #" + httpErr + " at " + Thread.currentThread().getName());
            NusuthServletOutputStream jbirdOutputStream = new NusuthServletOutputStream(clientSocket.getOutputStream());
            HttpNusuthResponse response = new HttpNusuthResponse(jbirdOutputStream);
            response.init(jbirdOutputStream, false);
            if (logProxy.isDebugEnabled())
                response.sendError(httpErr, "Internal error #" + errorCode + ", message \"" + message + "\", thread " + Thread.currentThread().getName());
            else
                response.sendError(httpErr, message);
        } catch (IOException ioex) {
            logger.error("Couldn't send error " + httpErr, ioex);
        }
    }

    protected ChunkedServletInputStream CIS = new ChunkedServletInputStream(null);
    protected FixedLengthServletInputStream FIS = new FixedLengthServletInputStream(null);
    private final static char[] SLASH = {'/'};


    private void readAllFromContainer(InputStream containerInputStream) throws DistributorException {
        try {
            while (containerInputStream.read(tempBuffer) > -1) ;
        } catch (IOException ioex) {
            throw new DistributorException(
                    ioex instanceof InterruptedIOException ? "Container input stream timeout" : "Couldn't read from container input stream",
                    ioex,
                    ERROR_BadContainerSocket);
        }
    }

    private void processCachedResponse(CachedElement page, boolean isNotModifiedResponse)
            throws DistributorException {
        if (logProxy.isDebugEnabled())
            logger.debug("Process cached response");
        state = PROCESSING_RESPONSE;
        responseLine.clear();
        cachedHeaders = (NusuthHeaders) page.getHeaders();
        if (isNotModifiedResponse) {
            responseLine.append(NOT_MODIFIED_RESPONSE_LINE);
            cachedHeaders.clearHeader(HttpConstants.CONTENT_LENGTH);
        } else {
            responseLine.append(OK_RESPONSE_LINE);
            cachedHeaders.putHeader(HttpConstants.CONTENT_LENGTH, String.valueOf(page.getBody().length).toCharArray());
        }
        cachedHeaders.putDateHeader(HTTP_LAST_MODIFIED, page.getLastModified());
        if (clientKeepAlive)
            cachedHeaders.putHeader(HttpConstants.CONNECTION, HttpConstants.KEEP_ALIVE);
        else
            cachedHeaders.putHeader(HttpConstants.CONNECTION, HttpConstants.CLOSE);

        if (!isNotModifiedResponse) {
            try {
                clientJSOS.write(page.getBody());
                logger.debug("Cached response body writed sucessfully");
            } catch (IOException ioex) {
                throw new DistributorException("Couldn't write cached response", ioex, ERROR_BadResponse);
            }
        }

        try {
            clientJSOS.close();
            logger.debug("Cached response flushed sucessfully");
        } catch (InterruptedIOException inex) {
            throw new DistributorException("Output stream timeout", inex, ERROR_BadClientSocket);
        } catch (IOException ioex) {
            throw new DistributorException("Couldn't flush output stream", ioex, ERROR_BadClientSocket);
        }
    }

    private void processMergedResponse(CachedElement page)
            throws DistributorException {
        if (logProxy.isDebugEnabled())
            logger.debug("Process merged response for \"" + page.getUrl() + '"');
        responseIsCacheable = responseHeaders.containsHeader(FileServlet.FILE_SERVLET_HEADER_NAME) && responseHeaders.getIntHeader(HTTP_CONTENT_LENGTH) < cache.getMaxPageSize();
        responseHeaders.clearHeader(FileServlet.FILE_SERVLET_HEADER_NAME);
        boolean isResponseKeepAilve = responseHeaders.containsHeader(HttpConstants.CONNECTION, HttpConstants.KEEP_ALIVE);
        boolean isChunked = responseHeaders.containsHeader(HttpConstants.TRANSFER_ENCODING, HttpConstants.CHUNKED);
        if (isResponseKeepAilve != clientKeepAlive)
            responseHeaders.putHeader(HttpConstants.CONNECTION, clientKeepAlive ? HttpConstants.KEEP_ALIVE : HttpConstants.CLOSE);
        if (!clientKeepAlive)
            responseHeaders.clearHeader(HttpConstants.TRANSFER_ENCODING);
        if (isChunked) {
            CIS.init(containerHSIS);
            readAllFromContainer(CIS);
            CIS.cleanup();
        } else {
            int contentLength = -1;
            try {
                contentLength = Utils.retreiveContentLength(responseHeaders);
            } catch (IOException ioex) {
                throw new DistributorException("Couldn't retrieve response content length", ioex, ERROR_BadResponse);
            }

            if (contentLength > -1) { // fixed content length
                if (contentLength != 0) {
                    FIS.init(containerHSIS, contentLength);
                    readAllFromContainer(FIS);
                    FIS.cleanup();
                }
            } else {
                throw new DistributorException("Couldn't define response content length", null, ERROR_BadResponse);
            }
        }

        processCachedResponse(page, false);
    }
}
