application-deployment.child=host
host.child=context

//securityConfig.child=resources;users;roles
//resources.child=distributors;containers;deployers;web-apps
//distributors.child=distributor
//containers.child=container
//deployers.child=deployer
//web-apps.child=web-app
//users.child=group;user
