container.displayComp=name
distributor.displayComp=name
application-deployment.host.displayComp=id
application-deployment.host.componentIdComp=id
application-deployment.host.context.displayComp=url
application-deployment.host.context.componentIdComp=url

web-app.displayComp=display-name
web-app.servlet.displayComp=display-name,servlet-name
web-app.filter.displayComp=display-name,filter-name
web-app.mime-mapping.displayComp=extension
//web-app.secutiry-constraint.web-resource-collection.displayComp=web-resource-name
web-resource-collection.displayComp=web-resource-name
user-data-constraint.displayComp=transport-guarantee
auth-constraint.displayComp=role-name
permissions.displayComp=role
taglib.displayComp=display-name,short-name
taglib.tag.displayComp=display-name,name

securityConfig.users.group.displayComp=name
securityConfig.users.user.displayComp=name
securityConfig.resources.distributors.distributor.displayComp=name
securityConfig.resources.containers.container.displayComp=name
securityConfig.resources.deployers.deployer.displayComp=name
securityConfig.resources.web-apps.web-app.displayComp=name

right.displayComp=group-name,user-name



//users.display=Users and Groups

tcp-server.display=TCP Server
container.tcp-server.display=TCP Server

container.name.display=Name
deployer.name.display=Name
distributor.name.display=Name
securityConfig.resources.distributors.distributor.name.display=Name
securityConfig.resources.containers.container.name.display=Name
securityConfig.resources.deployers.deployer.name.display=Name
securityConfig.resources.web-apps.web-app.name.display=Name
securityConfig.users.group.name.display=Name
securityConfig.users.user.name.display=Name
securityConfig.users.user.password.display=Password

host.doc-base.display=Doc base
host.id.display=Id
ssl-server.display=SSL Server
logger.display=Logging System
connection-factory.display=Connection Factory
manager.display=Management System
protocol-adapter.display=Protocol adapter
port.display=Listen port
handler-timeout.display=Handler time to live
queue.display=Socket queue length
allow-hosts.display=Allow hosts
min-handlers.display=Minimum number \n of handlers
max-keepalives.display=Maximum keep-alive \n connections allowed
so-timeout.display=Connection timeout
max-handlers.display=Maximum concurrent \n connections allowed
deny-hosts.display=Deny hosts
is-client-authentication-needed.display=Is client authentication needed
keystore.display=Key Store
keystore.location.display=Location
keystore.password.display=Password
trustedstore.location.display=Location
trustedstore.password.display=Password
context.location.display=Location path
url.display=Mapped at URL
is-running.display=started
logger.location.display=Located in directory
cache.display=Cache

cluster-key.display=Cluster key
class-name.display=Class name
init-parameters.display=Initialization Parameters
standalone.display=Is stand alone
admin-ip.display=IP list allowed to shutdown
default-web-config.display=Default application config
work-dir.display=Working directory
manager.port.display=Communication port
manager.auth-key.display=Authentification key
jsp.display=JSP Engine Configuration
refresh.display=Check for \n changes every
compiler.display=Use compiler
config.display=Alternative config location
level.display=Logging level

session-timeout.display=Session timeout
application.display-name.display=Display name
servlet.display-name.display=Display name
filter.display-name.display=Display name
taglib.display-name.display=Display name
tag.display-name.display=Display name
servlet.servlet-name.display=Servlet name
servlet.servlet-class.display=Servlet class
servlet.jsp-file.display=Jsp file
servlet.load-on-startup.display=Load on startup
filter.filter-name.display=Filter name
filter.filter-class.display=Filter class
application.description.display=Description
servlet.description.display=Description
filter.description.display=Description
taglib.description.display=Description
tag.description.display=Description
welcome-file-list.welcome-file.display=Welcome file
web-app.listener.display=Listeners
taglib.listener.display=Listeners
icon.small-icon.display=Small icon
icon.large-icon.display=Large icon
taglib.small-icon.display=Small icon
taglib.large-icon.display=Large icon
tag.small-icon.display=Small icon
tag.large-icon.display=Large icon
servlet-mapping.display=Servlet mapplings
filter-mapping.display=Filter mapplings
auth-method.display=Auth method
form-login-page.display=Form login page
form-error-page.display=Form error page
realm-name.display=Realm name
taglib.tlib-version.display=Taglib version
taglib.jsp-version.display=Jsp version
taglib.short-name.display=Short name
taglib.uri.display=URI
validator.validator-class.display=Validator class
tag.name.display=Name
tag.tag-class.display=Tag class
tag.tei-class.display=Tei class
tag.body-content.display=Body content


param-name.display=name
param-value.display=value

security-roles.role-name.display=name

env-entry-name.display=name
env-entry-type.display=type
env-entry-value.display=value

ejb-ref-name.display=name
ejb-ref-type.display=type

resource-env-ref-name.display=name
resource-env-ref-type.display=type

res-ref-name.display=name

web-app.context-param.columnOrder=param-name,param-value
web-app.filter-mapping.columnOrder=filter-name,url-pattern,servlet-name
web-app.servlet-mapping.columnOrder=servlet-name,url-pattern
web-app.mime-mapping.columnOrder=extension,mime-type
web-app.error-page.columnOrder=error-code,exception-type,location
web-app.taglib.columnOrder=taglib-uri,taglib-location
web-app.resource-env-ref.columnOrder=resource-env-ref-name,resource-env-ref-type
web-app.resource-ref.columnOrder=res-ref-name,res-type,res-auth,res-sharing-scope
web-app.security-constraint.columnOrder=display-name,web-resource-collection,auth-constraint,user-data-constraint
web-app.security-role.columnOrder=role-name
web-app.env-entry.columnOrder=env-entry-name,env-entry-type,env-entry-value
web-app.ejb-ref.columnOrder=ejb-ref-name,ejb-ref-type,home,remote,ejb-link,run-as

web-app.servlet.init-param.columnOrder=param-name,param-value
web-app.servlet.security-role-ref.columnOrder=role-name,role-link

web-app.filter.init-param.columnOrder=param-name,param-value

taglib.validator.init-param.columnOrder=param-name,param-value

taglib.tag.variable.columnOrder=name-given,name-from-attribute,variable-class,declare,scope
taglib.tag.attribute.columnOrder=name,type,required,rtexprvalue

securityConfig.resources.resource.columnOrder=name,owner-role,permissions
securityConfig.resources.resource.permissions.columnOrder=role,permission
securityConfig.users.user.columnOrder=name,password,role