ContainerState.functions=ActiveHandlers;ActiveKeepAlives;TotalHandlers;RequestCount;SessionCount;TotalRequestCount;TotalSessionCount
DistributorState.functions=ActiveHandlers;ActiveKeepAlives;TotalHandlers;ApplicationRequestCount

ActiveHandlers=getActiveHandlers
TotalHandlers=getTotalHandlers
ActiveKeepAlives=getActiveKeepAlives

RequestCount=getRequestCount;java.lang.String
SessionCount=getSessionCount;java.lang.String
TotalRequestCount=getTotalRequestCount
TotalSessionCount=getTotalSessionCount

ApplicationRequestCount=getApplicationRequestCount;java.lang.String


