web-app.basics.contains=context;session-config;icon;welcome-file-list;context-param


web-app.basics.components=container;display_description;context_param

container.border.title=Container
// gridwidth = -1 - RELATIVE; fill = 3 - VERTICAL;
container.constraints=gridwidth=-1;gridheight=1;weightx=0;weighty=0.1;fill=3;insets=7,7,7,7
// 0.5 from basics
//container.size.width=0.5
container.elements=started_el;dialog_els;distributable_el;context_containers_el;empty

started_el.hasBorder=false
started_el.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0;fill=2
started_el.elements=started;protocol

started.constraints=insets=5,5,5,5;gridwidth=-1;gridheight=1;weightx=0;weighty=0;fill=0
started.path=context.is-running
protocol.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0;fill=2;anchor=10
protocol.label=none
protocol.path=context.protocol

dialog_els.hasBorder=false
dialog_els.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0;fill=2
dialog_els.elements=location;url;session-timeout

location.constraints=insets=5,5,5,5
location.path=context.location
url.path=context.url
session-timeout.path=session-config.session-timeout


distributable_el.hasBorder=false
distributable_el.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0;fill=2
distributable_el.elements=distributable

distributable.constraints=insets=5,5,5,5
distributable.path=distributable


context_containers_el.hasBorder=false
context_containers_el.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0;fill=2
context_containers_el.elements=context_containers

context_containers.constraints=insets=0,15,5,0
context_containers.label=none
context_containers.path=context.container

empty.hasBorder=false
empty.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=1;fill=1

display_description.border.title=
display_description.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0.1;fill=1;insets=15,0,9,9
display_description.elements=display_els;description-els

display_els.hasBorder=false
display_els.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0.1;fill=1;insets=0,0,0,0
display_els.elements=display_name;small_icon;large_icon

display_name.constraints=insets=5,5,5,5
display_name.path=display-name

small_icon.path=icon.small-icon
large_icon.path=icon.large-icon

description-els.hasBorder=false
description-els.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=0.1;fill=1;insets=0,0,0,0
description-els.elements=description;welcome_files

description.constraints=insets=2,5,3,5
description.label=up
description.path=description

welcome_files.label=up
welcome_files.path=welcome-file-list.welcome-file



context_param.border.title=Context initial parameters
// 1 - BOTH
context_param.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=1;fill=1;insets=0,7,7,7
context_param.elements=params

params.constraints=gridwidth=0;gridheight=1;weightx=1;weighty=1;fill=1;insets=5,5,5,5
params.path=context-param


distributable.enables=context.container
