/* Generated by VDGG */

package com.azoft.nusuth.gui;

/**
 * @author vdgg, tanya
 * @version 1.0
 * @since Nusuth1.0
 */
public interface NameChangedListener {

    void nameChanged(EditorPanel source, String oldValue, String newValue);

    void componentIdChanged(EditorPanel source, String oldValue, String newValue);
}

