web-app.add=web-app.servlet;web-app.filter

securityConfig.resources.distributors.add=securityConfig.resources.distributors.distributor
securityConfig.resources.containers.add=securityConfig.resources.containers.container
securityConfig.resources.deployers.add=securityConfig.resources.deployers.deployer
securityConfig.resources.web-apps.add=securityConfig.resources.web-apps.web-app
securityConfig.users.add=securityConfig.users.group;securityConfig.users.user

application-deployment.add=application-deployment.host
application-deployment.host.add=application
