container.standalone=CheckBooleanElementRenderer
container.autoload=BooleanElementRenderer
logger.level=FixArrayElementRenderer;DEBUG;INFO;WARN;ERROR
jsp.refresh=TimeElementRenderer
application.distributable=CheckBooleanElementRenderer
application.description=TextAreaElementRenderer;2
servlet.description=TextAreaElementRenderer;2
filter.description=TextAreaElementRenderer;2
taglib.description=TextAreaElementRenderer;2
tag.description=TextAreaElementRenderer;2
welcome-file-list.welcome-file=TextAreaElementRenderer;2
//listener.listener-class=TextAreaElementRenderer;2

session-config.session-timeout=SessionConfigElementRenderer
context.is-running=CheckBooleanElementRenderer
context.protocol=ProtocolCheckBoxElementRenderer

tcp-server.port=NumberElementRenderer;65535
tcp-server.min-handlers=NumberElementRenderer
tcp-server.max-handlers=NumberElementRenderer
tcp-server.max-keepalives=NumberElementRenderer
tcp-server.queue=NumberElementRenderer
tcp-server.so-timeout=TimeElementRenderer
tcp-server.handler-timeout=TimeElementRenderer
tcp-server.allow-hosts=TextAreaElementRenderer;2
tcp-server.deny-hosts=TextAreaElementRenderer;2

ssl-server.port=NumberElementRenderer;65535
ssl-server.min-handlers=NumberElementRenderer
ssl-server.max-handlers=NumberElementRenderer
ssl-server.max-keepalives=NumberElementRenderer
ssl-server.queue=NumberElementRenderer
ssl-server.so-timeout=TimeElementRenderer
ssl-server.handler-timeout=TimeElementRenderer
ssl-server.allow-hosts=TextAreaElementRenderer;2
ssl-server.deny-hosts=TextAreaElementRenderer;2
ssl-server.is-client-authentication-needed=CheckBooleanElementRenderer

manager.port=NumberElementRenderer;65535
manager.password=PasswordElementRenderer

container-info.port=NumberElementRenderer;65535

context.container=ContainersCheckBoxElementRenderer;container

right.permission=PermissionCheckBoxElementRenderer
right.group-name=FixValuesElementRenderer;group
right.user-name=FixValuesElementRenderer;user
user.password=PasswordElementRenderer
user.parent-group=MultiListRenderer;group
group.parent-group=MultiListRenderer;group

web-resource-collection.url-pattern=TableRenderer
web-resource-collection.http-method=TableRenderer
web-app-users.role.member=TableRenderer
auth-constraint.role-name=TableRenderer;FixValuesElementRenderer;role

resource-ref.res-auth=FixArrayElementRenderer;APPLICATION;CONTAINER
user-data-constraint.transport-guarantee=FixArrayElementRenderer;NONE;INTEGRAL;CONFIDENTIAL
login-config.auth-method=AuthMethodElementRenderer
ejb-ref.ejb-ref-type=FixArrayElementRenderer;ENTITY;SESSION

servlet-mapping.servlet-name=FixValuesElementRenderer;servlet
filter-mapping.servlet-name=FixValuesElementRenderer;servlet
filter-mapping.filter-name=FixValuesElementRenderer;filter
security-role-ref.role-link=FixValuesElementRenderer;role

taglib.tlib-version=FixArrayElementRenderer;1.2;1.1;1.0
taglib.jsp-version=FixArrayElementRenderer;_;1.2;1.1;1.0
tag.body-content=FixArrayElementRenderer;_;tagdependent;JSP;empty
variable.declare=CheckBooleanElementRenderer
variable.scope=FixArrayElementRenderer;_;NESTED;AT_BEGIN;AT_END
attribute.required=CheckBooleanElementRenderer
attribute.rtexprvalue=CheckBooleanElementRenderer

securityConfig.roles.role=TableRenderer
securityConfig.resources.resource.permissions.role=FixValuesElementRenderer;security_role
securityConfig.users.user.role=TableRenderer;FixValuesElementRenderer;security_role
permissions.permission=FixArrayElementRenderer;read;write

