/* Generated by Together */

package com.azoft.nusuth.gui;

/**
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since Nusuth1.0
 */
public interface StatusLineWriter {

    void setStatusString(String status);

    void clearStatusString();
}
