package com.azoft.nusuth.core;/* Generated by VDGG */

import java.io.*;

/**This class realizes the servlets chunked input stream.
 * It is used when the Chunked Transfer Coding is used.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class ChunkedServletInputStream extends HttpNusuthServletInputStream {
    private int currentChunkSize = 0;
    private int currentChunkPosition = 0;
    private boolean closed = false;


    /**Constructor.
     * @param stream the servlet input stream.
     * @param headers object of the MimeHeaders class type , that contains standard internet message headers.
     * @exception IOException
     */
    public ChunkedServletInputStream(InputStream stream) {
        super(stream);
    }


    /**
     * @return the number of bytes that remains until the end of this shunk or 0 if the input stream is closed.
     */
    public int available() throws IOException {
        if (closed) {
            return 0;
        }
        return currentChunkSize - currentChunkPosition + stream.available();
    }


    public void cleanup() {
        super.cleanup();
        currentChunkSize = 0;
        currentChunkPosition = 0;
        closed = false;
    }


    /**This method closes this servlet input stream.
     */
    public void close() throws IOException {
        byte[] tmp = new byte[512];
        while (currentChunkSize > 0 && read(tmp) >= 0) ;
        currentChunkSize = 0;
        closed = true;
    }


    public void init(InputStream stream) {
        super.init(stream);
        try {
            readNextChunkSize();
        } catch (IOException ioex) {
            currentChunkSize = 0;
        }
    }


    /**This method reads the next byte from the input stream.
     * @return the next byte from the input stream, -1 if the input stream is closed or the current chunk size is zero.
     * @exception is thrown if any error occures while readng from the input stream.
     */
    public int read() throws IOException {
        if (closed || currentChunkSize == 0) {
            return -1;
        }
        if (currentChunkPosition >= currentChunkSize) {
            readNextChunkSize();
        }
        if (currentChunkSize == 0) {
            return -1;
        }
        currentChunkPosition++;
        return stream.read();
    }


    /**This method filles the given buffer with the bytes from the input stream.
     * @param buf the buffer that will be filled by this method.
     * @return number of bytes that were placed to the given buffer or -1 if  the input stream is closed or the current chunk size is zero.
     * @exception IOException is thrown in the same cases as for the @see ChunkedServletInputStream.read(byte[] buf, int offset, int len) method.
     */
    public int read(byte[] buf) throws IOException {
        return read(buf, 0, buf.length);
    }


    /**This method reads the given number of bytes and puts them to the given buffer.
     * @param buf buffer where the bytes from the input stream will be placed.
     * @param offset ????????????????
     * @param len the number of byted that will be placed to the given buffer from the input stream.
     * @return number of byted that were read from the input stream or -1 if the input stream is closed or if the current chunk size is zero.
     * @exception IOException is thrown if any error occures while reading from the input stream.
     * @exception NullPointerException is thrown if the target buffer is null.
     */
    public int read(byte[] buf, int offset, int len) throws IOException {
        if (buf == null) {
            throw new NullPointerException("Target buffer is null");
        }
        if (closed || currentChunkSize == 0) {
            return -1;
        }
        if (currentChunkPosition >= currentChunkSize) {
            readNextChunkSize();
        }
        if (currentChunkSize == 0) {
            return -1;
        }
        int readed = 0;
        if (len > currentChunkSize - currentChunkPosition) {
            int off = offset;
            int toRead = currentChunkSize - currentChunkPosition;
            int tmp;
            do {
                tmp = stream.read(buf, off, toRead);
                if (tmp <= 0) {
                    return readed > 0 ? readed : tmp;
                }
                if (tmp < toRead) {
                    currentChunkPosition += tmp;
                    return readed + tmp;
                } else {
                    readed += tmp;
                    off += tmp;
                    currentChunkPosition += tmp;
                    if (currentChunkPosition == currentChunkSize)
                        readNextChunkSize();
                    toRead = currentChunkSize > (len - readed) ? (len - readed) : currentChunkSize;
                }
            } while (toRead > 0);
        } else {
            readed = stream.read(buf, offset, len);
            if (readed > 0) {
                currentChunkPosition += readed;
            }
        }
        return readed;
    }


    /**This method reads the chunk size from the input stream, if the input stream is closed then doing nothing.
     * @exception IOException if the unexpected end of stream was met or if there was a bad chunk size or there was a negative size of chunk.
     */
    private void readNextChunkSize() throws IOException {
        if (closed) {
            return;
        }
        int cur;
        int prev;
        //StrBuffer sb = new StrBuffer();
        cur = stream.read();
        if (cur == 13) {
            stream.read();
            cur = stream.read();
        }
        prev = cur;
        boolean cont = true;
        int nextChunkSize = 0;
        int val = -1;
        while (cur >= 0 && !(cur == 10 && prev == 13)) {
            if (cont) {
                //sb.append((char) cur);
                if (cur >= '0' && cur <= '9')
                    val = cur - '0';
                else if (cur >= 'a' && cur <= 'f')
                    val = cur - 'a' + 10;
                else if (cur >= 'A' && cur <= 'F')
                    val = cur - 'A' + 10;
                if (val > -1)
                    nextChunkSize = (nextChunkSize << 4) + val;
                else if (cur != ' ' && cur != 13)
                    throw new IOException("Bad chunk size");
                val = -1;
            }
            prev = cur;
            cur = stream.read();
        }
        if (cur < 0) {
            throw new EOFException("Unexpected end of stream");
        }
        /*int len = -1;
            len=nextChunkSize;
            try {
                len = Integer.parseInt(sb.toString(), 16);
            } catch (NumberFormatException nfe) {
                throw new IOException("Bad chunk size: " + sb.toString());
            }
            if (nextChunkSize < 0) {
                throw new IOException("Negative size of chunk");
            }
        */
        currentChunkSize = nextChunkSize;
        currentChunkPosition = 0;
        if (nextChunkSize == 0) {
            stream.read();
            stream.read();
        }
    }


    /**This method skipes the given number of bytes in the input stream.
     * @param n the number of bytes that will be skiped while reading from the input stream.
     * @return the number of skipped bytes, 0 if the the input stream is closed or if the end of chunk was arrived.
     * @exception IOException is thrown if any error occures while skiping the given number of bytes in the input stream.
     */
    public long skip(long n) throws IOException {
        if (!closed && (currentChunkSize > currentChunkPosition)) {
            long skipped = stream.skip(n > currentChunkSize - currentChunkPosition ? currentChunkSize - currentChunkPosition : n);
            currentChunkPosition += skipped;
            return skipped;
        }
        return 0;
    }
}