/* Generated by JBird Engine */
package com.azoft.nusuth.core;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;

import com.azoft.nusuth.util.*;

import java.io.*;
import java.util.*;

public class DirServlet extends com.azoft.nusuth.jsp.NusuthJspPage {

    private static byte[] _jsp_template0;
    private static byte[] _jsp_template1;
    private static byte[] _jsp_template2;

    private String cutString(String s) {
        if (s.length() == 0) {
            return s;
        }
        if (s.endsWith("/")) {
            return cutString(s.substring(0, s.length() - 1));
        } else {
            return s.substring(0, s.lastIndexOf("/"));
        }
    }

    private static byte[] _jsp_template3;
    private static byte[] _jsp_template4;
    private static byte[] _jsp_template5;
    private static byte[] _jsp_template6;
    private static byte[] _jsp_template7;
    private static byte[] _jsp_template8;
    private static byte[] _jsp_template9;
    private static byte[] _jsp_template10;
    private static byte[] _jsp_template11;
    private static byte[] _jsp_template12;
    private static byte[] _jsp_template13;
    private static byte[] _jsp_template14;
    private static byte[] _jsp_template15;
    private static byte[] _jsp_template16;
    private static byte[] _jsp_template17;
    private static byte[] _jsp_template18;
    private static byte[] _jsp_template19;
    private static byte[] _jsp_template20;
    private static byte[] _jsp_template21;

    static {
        try {
            _jsp_template0 = "<html>\r\n<head>\r\n<title>Directory listing</title>\r\n</head>\r\n<body>\r\n".getBytes("ISO8859_1");
            _jsp_template1 = "\r\n".getBytes("ISO8859_1");
            _jsp_template2 = "\r\n".getBytes("ISO8859_1");
            _jsp_template3 = "\r\n<H2>Directory listing for ".getBytes("ISO8859_1");
            _jsp_template4 = " </H2><BR><BR>\r\n<TABLE WIDTH=80%>\r\n<TH></TH>\r\n<TH ALIGN=\"LEFT\">Name</TH>\r\n<TH ALIGN=\"LEFT\">Size</TH>\r\n<TH ALIGN=\"LEFT\">Date</TH>\r\n<TR><TD>Fold".getBytes("ISO8859_1");
            _jsp_template5 = "ers:</TD><TD></TD><TD></TD><TD></TD></TR>\r\n".getBytes("ISO8859_1");
            _jsp_template6 = "\r\n  <TR><TD></TD><TD><A HREF=\"".getBytes("ISO8859_1");
            _jsp_template7 = "\"> .. </A> </TD><TD></TD></TR>\r\n".getBytes("ISO8859_1");
            _jsp_template8 = "\r\n  <TR>\r\n  <TD></TD><TD><A HREF=\"".getBytes("ISO8859_1");
            _jsp_template9 = "\"> ".getBytes("ISO8859_1");
            _jsp_template10 = "  </A> </TD>\r\n  <TD></TD>\r\n  ".getBytes("ISO8859_1");
            _jsp_template11 = "\r\n  <TD> ".getBytes("ISO8859_1");
            _jsp_template12 = " </TD>\r\n  </TR>\r\n".getBytes("ISO8859_1");
            _jsp_template13 = "\r\n<TR><TD>Files:</TD><TD></TD><TD></TD><TD></TD></TR>\r\n".getBytes("ISO8859_1");
            _jsp_template14 = "\r\n  <TR>\r\n  <TD></TD><TD><A HREF=\"".getBytes("ISO8859_1");
            _jsp_template15 = "\"> ".getBytes("ISO8859_1");
            _jsp_template16 = " </A> </TD>\r\n  ".getBytes("ISO8859_1");
            _jsp_template17 = "\r\n  <TD> ".getBytes("ISO8859_1");
            _jsp_template18 = " </TD>\r\n  ".getBytes("ISO8859_1");
            _jsp_template19 = "\r\n  <TD>  ".getBytes("ISO8859_1");
            _jsp_template20 = "   </TD>\r\n  </TR>\r\n".getBytes("ISO8859_1");
            _jsp_template21 = "\r\n</TABLE>\r\n</body>\r\n</html>".getBytes("ISO8859_1");
        } catch (java.io.UnsupportedEncodingException _jsp_uee) {
        }
    }

    public void _jspService(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, java.io.IOException {
        response.setContentType("text/html");
        javax.servlet.jsp.PageContext pageContext = javax.servlet.jsp.JspFactory.getDefaultFactory().getPageContext(this, request, response, null, true, 8192, true);
        Object page = this;
        javax.servlet.jsp.JspWriter out = pageContext.getOut();
        javax.servlet.ServletContext application = pageContext.getServletContext();
        javax.servlet.ServletConfig config = pageContext.getServletConfig();
        javax.servlet.http.HttpSession session = pageContext.getSession();

        com.azoft.nusuth.jsp.NusuthJspWriter _jsp_jbirdWriter = (com.azoft.nusuth.jsp.NusuthJspWriter) out;
        _jsp_jbirdWriter.setEncoding("ISO8859_1");

        try {

            _jsp_jbirdWriter.rawWrite(_jsp_template0);

            _jsp_jbirdWriter.rawWrite(_jsp_template1);

            String docBase = (String) request.getAttribute("docBase");
            String uri = (String) request.getAttribute("uri");
            String fileString = (String) request.getAttribute("file");
            File file = new File(fileString);
            File[] files = file.listFiles();
            LinkedList realFiles = new LinkedList();
            LinkedList dirs = new LinkedList();
            for (int i = 0; i < files.length; i++) {
                if (files[i].isDirectory()) {
                    dirs.add(files[i]);
                } else {
                    realFiles.add(files[i]);
                }
            }


            _jsp_jbirdWriter.rawWrite(_jsp_template2);

            _jsp_jbirdWriter.rawWrite(_jsp_template3);
            out.print(uri);

            _jsp_jbirdWriter.rawWrite(_jsp_template4);

            _jsp_jbirdWriter.rawWrite(_jsp_template5);

            if (!cutString(uri).equals("")) {

                _jsp_jbirdWriter.rawWrite(_jsp_template6);
                out.print(cutString(uri));

                _jsp_jbirdWriter.rawWrite(_jsp_template7);

            }
            for (int i = 0; i < dirs.size(); i++) {

                _jsp_jbirdWriter.rawWrite(_jsp_template8);
                out.print(uri + (uri.endsWith("/") ? "" : "/") + ((File) dirs.get(i)).getName());

                _jsp_jbirdWriter.rawWrite(_jsp_template9);
                out.print(((File) dirs.get(i)).getName());

                _jsp_jbirdWriter.rawWrite(_jsp_template10);

                HttpDate httpDate = new HttpDate();

                _jsp_jbirdWriter.rawWrite(_jsp_template11);
                out.print(new String(httpDate.convert(((File) dirs.get(i)).lastModified()), 0, 16));

                _jsp_jbirdWriter.rawWrite(_jsp_template12);

            }

            _jsp_jbirdWriter.rawWrite(_jsp_template13);

            for (int i = 0; i < realFiles.size(); i++) {

                _jsp_jbirdWriter.rawWrite(_jsp_template14);
                out.print(uri + (uri.endsWith("/") ? "" : "/") + ((File) realFiles.get(i)).getName());

                _jsp_jbirdWriter.rawWrite(_jsp_template15);
                out.print(((File) realFiles.get(i)).getName());

                _jsp_jbirdWriter.rawWrite(_jsp_template16);

                long fileSize = ((File) realFiles.get(i)).length();
                String size;
                if (fileSize < 1000)
                    size = fileSize + "b";
                else if (fileSize < 1000000) {
                    size = String.valueOf((double) fileSize / 1024);
                    if (size.length() > 5) {
                        size = size.substring(0, 5) + "Kb";
                    } else {
                        size = size + "Kb";
                    }
                } else {
                    size = String.valueOf((double) fileSize / 1048576);
                    if (size.length() > 5) {
                        size = size.substring(0, 5) + "Mb";
                    } else {
                        size = size + "Mb";
                    }
                }

                _jsp_jbirdWriter.rawWrite(_jsp_template17);
                out.print(size);

                _jsp_jbirdWriter.rawWrite(_jsp_template18);

                HttpDate httpDate = new HttpDate();

                _jsp_jbirdWriter.rawWrite(_jsp_template19);
                out.print(new String(httpDate.convert(((File) realFiles.get(i)).lastModified()), 0, 16));

                _jsp_jbirdWriter.rawWrite(_jsp_template20);

            }

            _jsp_jbirdWriter.rawWrite(_jsp_template21);

        } catch (Exception ex) {
            pageContext.handlePageException(ex);
        } finally {
            out.flush();
            javax.servlet.jsp.JspFactory.getDefaultFactory().releasePageContext(pageContext);
        }
    }
}