/* Generated by VDGG */

package com.azoft.nusuth.core;

import com.azoft.nusuth.container.InvocationCacheElement;


public class FileInvocationCacheElement extends InvocationCacheElement {

    public byte[] fileContent;
    public long fileLastModified;
    public long fileLastCheck;
    public String contentType;

}
