/* Generated by VDGG */

package com.azoft.nusuth.core;

import com.azoft.nusuth.util.LogCategoryProxy;

import java.io.*;

//import com.azoft.nusuth.util.Logger;

/**
 * This class realize the servlet input stream with the fixed length.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class FixedLengthServletInputStream extends HttpNusuthServletInputStream {

    private int length;
    private int currentPos;
    private boolean closed;

    private org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.core");
    private LogCategoryProxy catProxy = LogCategoryProxy.getInstance("com.azoft.nusuth.core");

    /**Constructor.
     * @param stream the servlet input stream
     * @param length the servlet input stream length.
     */
    public FixedLengthServletInputStream(InputStream stream) {
        super(stream);
    }


    public void init(InputStream stream, int length) {
        super.init(stream);
        this.length = length;
        currentPos = 0;
        closed = false;
    }


    /**This method reads the next simbol from the input stream.
     * @return the next byte from the input stream, -1 if the stream is closed or if we read all bytes from the stream, limited by the fixed length.
     * @exception IOException is thrown if any error occures while reading from the input stream.
     */
    public int read() throws IOException {
        if (closed) {
            return -1;
        }
        if (currentPos <= length) {
            currentPos++;
        }
        return currentPos > length ? -1 : stream.read();
        /*    if (currentPos > length) {
              Logger.log("End of stream: "+length+" bytes readed", 1);
              return -1;
            } else {
              byte[] tmp = new byte[1];
              int res = stream.read();
              if (res == -1) {
                Logger.log("Stream "+stream.toString()+" return -1 !!!!", 1);
              }
              tmp[0] = (byte)res;
              Logger.log(tmp, 1);
              return res;
            }*/
    }


    /**This method reads the given number of simbols to the given buffer.
     * @param buf the buffer where this method will write bytes from input stream.
     * @param offset ?????????????
     * @param len the number of bytes this method will write to the given buffer from the input stream.
     * @return the number of bytes that were wrote to the given buffer, returnes -1 if the input stream is closed or if we read all bytes from the stream, limited by the fixed length. .
     * @exception IOException is thrown if any error occures while reading from the input stream.
     * @exception NullPointerException is thrown if the given buffer is null.
     */
    public int read(byte[] buf, int offset, int len) throws IOException {
        if (buf == null) {
            throw new NullPointerException("Target buffer is null");
        }
        if (closed) {
            return -1;
        }
        if (currentPos >= length) {
            return -1;
        }
        int tmp = 0;
        tmp = stream.read(buf, offset, (len + currentPos > length) ? length - currentPos : len);
        if (tmp >= 0) {
            currentPos += tmp;
        }
        return tmp;
    }


    /**This method filles the given bufer with the next bytes from input stream.
     * @param buf the buffer this method will fill.
     * @return the number of bytes that were placed in the given buffer.
     * @exception IOException is thrown if any error occures while reading bytes from the input stream.
     */
    public int read(byte[] buf) throws IOException {
        return read(buf, 0, buf.length);
    }


    /**This method skipes the given number of bytes in the input stream.
     * @param n the number of bytes that will be skiped while reading from the input stream.
     * @return the number of skipped bytes, 0 if the the input stream is closed.
     * @exception IOException is thrown if any error occures while skipping the given number of bytes in the input stream.
     */
    public long skip(long n) throws IOException {
        if (closed) {
            return 0;
        }
        long skipped = stream.skip(n > length - currentPos ? length - currentPos : n);
        currentPos += skipped;
        return skipped;
    }


    /**
     * @return the number of bytes that can be read without blocking the applications work, 0 if the input stream is closed.
     * @exception IOException is thrown in the same cases as for the @see java.io.InputStream.available() method.
     */
    public int available() throws IOException {
        if (currentPos >= length) {
            return 0;
        }
        int really = stream.available();
        return really < length - currentPos ? really : length - currentPos;
    }


    /**This method closes the servlet input stream.
     * @exception IOException is thrown in the same cases as for the skip method of this class or if any error occures while reading the input strem.
     */
    public void close() throws IOException {
        if (skip(length - currentPos) < length - currentPos) {
            byte[] tmp = new byte[length - currentPos];
            int readed = 0;
            do {
                readed = read(tmp);
            } while (readed >= 0 && currentPos < length);
            currentPos = length;
        }
        closed = true;
    }


    public void cleanup() {
        if (stream != null) {
            try {
                close();
            } catch (IOException e) {
                if (catProxy.isDebugEnabled()) {
                    cat.debug("Cannot close fixed stream while cleaning up", e);
                }
            }
        }
        super.cleanup();
        currentPos = 0;
        closed = false;
    }
}