/* Generated by VDGG */

package com.azoft.nusuth.core;

/**This interface is implemented by the @see HttpDistributorRequestAdapter and @see HttpNusuthResponse
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public interface FlushListener {

    /**This method is called on Flush.
     */
    public void onFlush() throws java.io.IOException;
}

