/* Generated by VDGG */

package com.azoft.nusuth.core;

import com.azoft.nusuth.util.StrBuffer;
import com.azoft.nusuth.util.ByteBuffer;

public class HttpRequestLine {

    public StrBuffer method = new StrBuffer(8);
    public StrBuffer uri = new StrBuffer(64);
    public ByteBuffer queryString = new ByteBuffer(32);
    public StrBuffer protocol = new StrBuffer(8);

    public HttpRequestLine() {
    }

    public void clear() {
        method.clear();
        uri.clear();
        queryString.clear();
        protocol.clear();
    }


}
