/* Generated by VDGG */

package com.azoft.nusuth.core;

import java.io.*;

import com.azoft.nusuth.util.*;

/**
 *This class realizes the servlet input stream for the HTTP request.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class HttpNusuthServletInputStream extends NusuthServletInputStream {
    private final static int BUFFER_SIZE = 2048;
    private final static int METHOD_LENGTH = 8;
    private final static int URI_LENGTH = 64;
    private final static int QUERY_LENGTH = 32;
    private final static int PROTOCOL_LENGTH = 8;
    private final static int HEADER_LENGTH = 64;
    private final static int METHOD_EXPANSION_LIMIT = 2;
    private final static int URI_EXPANSION_LIMIT = 5;
    private final static int QUERY_EXPANSION_LIMIT = 6;
    private final static int PROTOCOL_EXPANSION_LIMIT = 1;
    private final static int HEADER_NAME_EXPANSION_LIMIT = 5;
    private final static int HEADER_VALUE_EXPANSION_LIMIT = 6;
    private int methodExp;
    private int uriExp;
    private int queryExp;
    private int protocolExp;
    private int headerNameExp;
    private int headerValueExp;
    private byte[] buffer = new byte[BUFFER_SIZE];
    private int endpos = 0;
    private int curpos = 0;
    private boolean eof = false;
    private boolean closed = false;
    private char[] methodBuf = new char[METHOD_LENGTH];
    private int methodPos = 0;
    private char[] uriBuf = new char[URI_LENGTH];
    private int uriPos = 0;
    private byte[] queryBuf = new byte[QUERY_LENGTH];
    private int queryPos = 0;
    private char[] protocolBuf = new char[PROTOCOL_LENGTH];
    private int protocolPos = 0;
    private char[] headerBuf = new char[HEADER_LENGTH];
    private int headerPos = 0;
    private org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.core");
    private LogCategoryProxy catProxy = LogCategoryProxy.getInstance("com.azoft.nusuth.core");

    private char c;
    private boolean rname;

    /**
     *Constructor.
     * @param stream the servlet input stream.
     */
    public HttpNusuthServletInputStream(InputStream stream) {
        super(stream);
    }
    //XXX ????????????

    /**
     *This method reads //XXX ????????????
     * @param name //XXX ????????????
     * @param value //XXX ????????????
     * @exception IOException is thrown if any error occures while reading from the input stream.
     */
    public boolean readHeader(NusuthHeader header) throws IOException {
        rname = true;
        headerPos = 0;
        if (curpos >= endpos) {
            fillBuffer();
        }
        headerNameExp = 0;
        headerValueExp = 0;
        while (!eof) {
            c = (char) buffer[curpos++];
            switch (c) {
                case '\n':
                    if (!rname && headerPos > 0) {
                        header.addValueChars(headerBuf, 0, headerPos);
                    }
                    return !rname;
                case '\r':
                    break;
                case ':':
                    if (rname) {
                        rname = false;
                        header.addNameChars(headerBuf, 0, headerPos);
                        headerPos = 0;
                    } else {
                        if (headerPos >= headerBuf.length) {
                            if (headerValueExp == HEADER_VALUE_EXPANSION_LIMIT) throw new IOException("Too long header value");
                            headerBuf = extendBuffer(headerBuf);
                            headerValueExp++;
                        }
                        headerBuf[headerPos++] = c;
                    }
                    break;
                case ' ':
                    if (!rname && headerPos > 0) {
                        if (headerPos >= headerBuf.length) {
                            if (headerValueExp == HEADER_VALUE_EXPANSION_LIMIT) throw new IOException("Too long header value");
                            headerBuf = extendBuffer(headerBuf);
                            headerValueExp++;
                        }
                        headerBuf[headerPos++] = c;
                    }
                    break;
                default:
                    if (headerPos >= headerBuf.length) {
                        if (rname) {
                            if (headerNameExp == HEADER_NAME_EXPANSION_LIMIT) throw new IOException("Too long header name");
                            headerNameExp++;
                        } else {
                            if (headerValueExp == HEADER_VALUE_EXPANSION_LIMIT) throw new IOException("Too long header value");
                            headerValueExp++;
                        }
                        headerBuf = extendBuffer(headerBuf);
                    }
                    headerBuf[headerPos++] = c;
                    break;
            }
            if (curpos >= endpos) {
                fillBuffer();
            }
        }
        throw new IOException("Cannot find header end");
    }

    public void readRequestLine(HttpRequestLine requestLine) throws IOException {
        byte spacenum = 0;
        boolean hasQuery = false;
        if (curpos >= endpos) {
            fillBuffer();
        }
        methodExp = 0;
        uriExp = 0;
        queryExp = 0;
        protocolExp = 0;
        byte b;
        while (!eof) {
            b = buffer[curpos++];
            c = (char) b;
            switch (c) {
                case '\n':
                    if (methodPos == 0) {
                        break;
                    }
                    requestLine.method.append(methodBuf, 0, methodPos);
                    requestLine.uri.append(uriBuf, 0, uriPos);
                    if (hasQuery) {
                        requestLine.queryString.append(queryBuf, 0, queryPos);
                    }
                    requestLine.protocol.append(protocolBuf, 0, protocolPos);
                    return;
                case '?':
                    if (spacenum == 1 && !hasQuery) {
                        hasQuery = true;
                    } else {
                        switch (spacenum) {
                            case 0:
                                if (methodPos >= methodBuf.length) {
                                    if (methodExp == METHOD_EXPANSION_LIMIT) throw new IOException("Too long method");
                                    methodBuf = extendBuffer(methodBuf);
                                    methodExp++;
                                }
                                methodBuf[methodPos++] = c;
                                break;
                            case 1:
                                if (hasQuery) {
                                    if (queryPos >= queryBuf.length) {
                                        if (queryExp == QUERY_EXPANSION_LIMIT) throw new IOException("Too long query string");
                                        queryBuf = extendBuffer(queryBuf);
                                        queryExp++;
                                    }
                                    queryBuf[queryPos++] = b;
                                } else {
                                    if (uriPos >= uriBuf.length) {
                                        if (uriExp == URI_EXPANSION_LIMIT) throw new IOException("Too long URI");
                                        uriBuf = extendBuffer(uriBuf);
                                        uriExp++;
                                    }
                                    uriBuf[uriPos++] = c;
                                }
                                break;
                            case 2:
                                if (protocolPos >= protocolBuf.length) {
                                    if (protocolExp == PROTOCOL_EXPANSION_LIMIT) throw new IOException("Invalid protocol");
                                    protocolBuf = extendBuffer(protocolBuf);
                                    protocolExp++;
                                }
                                protocolBuf[protocolPos++] = c;
                                break;
                            default:
                                throw new IOException("Wrong request line");
                        }
                    }
                    break;
                case ' ':
                    spacenum++;
                    if (spacenum > 2) throw new IOException("Too many spaces detected");
                    break;
                case '\r':
                    break;
                default:
                    switch (spacenum) {
                        case 0:
                            if (methodPos >= methodBuf.length) {
                                if (methodExp == METHOD_EXPANSION_LIMIT) throw new IOException("Too long method");
                                methodBuf = extendBuffer(methodBuf);
                                methodExp++;
                            }
                            methodBuf[methodPos++] = c;
                            break;
                        case 1:
                            if (hasQuery) {
                                if (queryPos >= queryBuf.length) {
                                    if (queryExp == QUERY_EXPANSION_LIMIT) throw new IOException("Too long query string");
                                    queryBuf = extendBuffer(queryBuf);
                                    queryExp++;
                                }
                                queryBuf[queryPos++] = b;
                            } else {
                                if (uriPos >= uriBuf.length) {
                                    if (uriExp == URI_EXPANSION_LIMIT) throw new IOException("Too long URI");
                                    uriBuf = extendBuffer(uriBuf);
                                    uriExp++;
                                }
                                uriBuf[uriPos++] = c;
                            }
                            break;
                        case 2:
                            if (protocolPos >= protocolBuf.length) {
                                if (protocolExp == PROTOCOL_EXPANSION_LIMIT) throw new IOException("Invalid protocol");
                                protocolBuf = extendBuffer(protocolBuf);
                                protocolExp++;
                            }
                            protocolBuf[protocolPos++] = c;
                            break;
                        default:
                            throw new IOException("Wrong request line");
                    }
                    break;
            }
            if (curpos >= endpos) {
                fillBuffer();
            }
        }
        throw new IOException("Cannot find end of request line");
    }

    private void fillBuffer() throws IOException {
        int avail = stream.available();
        int b = -1;
        if (avail <= 0) {
            b = stream.read();
            if (b == -1) {
                eof = true;
                // Logger.log("End of stream reached", 1);
                cat.debug("End of stream reached");
                return;
            }
            avail = stream.available();
        }
        int len = 0;
        if (b == -1) {
            if (avail <= 0) {
                throw new IOException("Internal error in HttpNusuthServletInputStream!");
            }
            if (avail > BUFFER_SIZE) {
                len = stream.read(buffer);
            } else {
                len = stream.read(buffer, 0, avail);
            }
            curpos = 0;
            endpos = len;
        } else {
            buffer[0] = (byte) b;
            if (avail <= 0) {
                curpos = 0;
                endpos = 1;
            } else {
                len = stream.read(buffer, 1, avail > BUFFER_SIZE - 1 ? BUFFER_SIZE - 1 : avail);
                curpos = 0;
                endpos = len + 1;
            }
        }
        if (catProxy.isDebugEnabled()) {
            cat.debug(new String(buffer, 0, endpos));
        }
    }

    public int read() throws IOException {
        if (curpos >= endpos) {
            fillBuffer();
        }
        if (eof) {
            //     Logger.log("Read in buffered stream: EOF!!!", 1);
            return -1;
        } else {
            return ((int) buffer[curpos++]) & 0xff;
        }
    }

    public int read(byte[] buf) throws IOException {
        return read(buf, 0, buf.length);
    }

    public int read(byte[] buf, int off, int len) throws IOException {
        if (curpos >= endpos) {
            fillBuffer();
        }
        if (eof) {
            return -1;
        } else {
            if (len > endpos - curpos) {
                System.arraycopy(buffer, curpos, buf, off, endpos - curpos);
                int readed = endpos - curpos;
                curpos = endpos;
                return readed;
            } else {
                System.arraycopy(buffer, curpos, buf, off, len);
                curpos += len;
                return len;
            }
        }
    }

    public void close() throws IOException {
        curpos = 0;
        endpos = 0;
        closed = true;
        super.close();
    }

    public void cleanup() {
        super.cleanup();
        endpos = 0;
        curpos = 0;
        eof = false;
        closed = false;
        partialCleanup();
    }

    public void partialCleanup() {
        methodPos = 0;
        if (methodBuf.length != METHOD_LENGTH) {
            methodBuf = new char[METHOD_LENGTH];
        }
        uriPos = 0;
        if (uriBuf.length != URI_LENGTH) {
            uriBuf = new char[URI_LENGTH];
        }
        queryPos = 0;
        if (queryBuf.length != QUERY_LENGTH) {
            queryBuf = new byte[QUERY_LENGTH];
        }
        protocolPos = 0;
        if (protocolBuf.length > PROTOCOL_LENGTH) {
            protocolBuf = new char[PROTOCOL_LENGTH];
        }
        headerPos = 0;
        if (headerBuf.length > HEADER_LENGTH) {
            headerBuf = new char[HEADER_LENGTH];
        }
    }

    private char[] extendBuffer(char[] buf) {
        char[] tmp = new char[buf.length * 2];
        System.arraycopy(buf, 0, tmp, 0, buf.length);
        return tmp;
    }

    private byte[] extendBuffer(byte[] buf) {
        byte[] tmp = new byte[buf.length * 2];
        System.arraycopy(buf, 0, tmp, 0, buf.length);
        return tmp;
    }

    public int available() throws IOException {
        return endpos - curpos + stream.available();
    }

    public int readLine(StrBuffer line) throws IOException {
        if (curpos >= endpos) {
            fillBuffer();
        }
        while (!eof) {
            c = (char) buffer[curpos++];
            line.append(c);
            if (c == '\n') {
                return curpos;
            }
            if (curpos >= endpos) {
                fillBuffer();
            }
        }
        throw new IOException("Cannot find end of line");
    }
}
