/* Generated by VDGG */

package com.azoft.nusuth.core;

import javax.servlet.ServletInputStream;
import java.io.*;

//import com.azoft.nusuth.util.Logger;

/**This class realizes the servlet input stream that contains request data.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public class NusuthServletInputStream extends ServletInputStream {
    protected InputStream stream = null;

    /**Constructor.
     * @param stream the servlet input stream.
     */
    public NusuthServletInputStream(InputStream stream) {
        this.stream = stream;
    }

    /**
     * @return next byte(symbol) from the input stream.
     * @exception IOException is thrown if any error occures while reading the input stream.
     */
    public int read() throws IOException {
/*    if (curSym >= lastSym) {
      curSym = 0;
      readLineBuffer();
    }
//    System.out.print(buf[cur]);
    return curSym >= lastSym ? -1 : lineBuffer[curSym++];*/
        return stream.read();
    }

    public void init(InputStream stream) {
        this.stream = stream;
    }

    public void cleanup() {
        stream = null;
    }
}

