/* Generated by VDGG */

package com.azoft.nusuth.core;

import java.io.*;
import javax.servlet.*;

import com.azoft.nusuth.util.*;

/**This class realizes the servlet output stream where the response data
 * is writing.
 * Handles the chunked transfer encoding.
 * @author vdgg, skilz
 * @version 1.14
 * @since Nusuth1.0
 */
public class NusuthServletOutputStream extends ServletOutputStream {
    private BufferedServletOutputStream stream;
    private final static int DEFAULT_BUFFER_SIZE = 8192;
    private byte[] buffer = new byte[DEFAULT_BUFFER_SIZE];
    private int inbuffer = 0;
    private FlushListener listener = null;
    private boolean commited = false;
    private boolean closed = false;
    private boolean chunked = false;
    private boolean sendBody = true;
    private final static byte[] CRLF = {13, 10};
    private final static byte[] LAST_CHUNK = {(byte) '0', 13, 10};
    private int temp;
    private int contentLength = -1;
    private int readyLength = 0;
    private boolean endWriting = false;
    private int counter;
    private byte[] forConv = new byte[8];
    private final static byte[] hexNum = {
        (byte) '0', (byte) '1', (byte) '2',
        (byte) '3', (byte) '4', (byte) '5',
        (byte) '6', (byte) '7', (byte) '8',
        (byte) '9', (byte) 'a', (byte) 'b',
        (byte) 'c', (byte) 'd', (byte) 'e',
        (byte) 'f',
    };
    private org.apache.log4j.Category cat
            = org.apache.log4j.Category.getInstance("com.azoft.nusuth.core");
    private LogCategoryProxy catProxy
            = LogCategoryProxy.getInstance("com.azoft.nusuth.core");
    private boolean strictWrite = false;
    private int transfered = 0;
    private boolean hasSendBody = false;
    private boolean hasBody = false;
    private boolean ignoreFlush = false;

    /**Constructor.
     * @param stream the output stream.
     */
    public NusuthServletOutputStream(OutputStream stream) {
        this.stream = new BufferedServletOutputStream();
        this.stream.init(stream);
        forConv[6] = 13;
        forConv[7] = 10;
        transfered = 0;
    }

    /**
     * Initialize this output stream.
     * @param stream OutputStream.
     */
    public void init(OutputStream stream) {
        transfered = 0;
        this.stream.init(stream);
        contentLength = -1;
        readyLength = 0;
        endWriting = false;
        sendBody = true;
        hasSendBody = false;
        hasBody = false;
    }

    public void setBodySend(boolean sendBody) {
        this.sendBody = sendBody;
    }

    /**This method writes number to the inner buffer.
     * @param i number that this method will write to the inner buffer.
     * @exception IOException is thrown if the stream is closed.
     */
    public void write(int i) throws IOException {
        if (strictWrite) {
            stream.write(i);
        } else if (sendBody) {
            hasBody = true;
            if (contentLength == 0) {
                flush();
                endWriting = true;
            }
            if (!endWriting) {
                if (inbuffer >= buffer.length) {
                    flush();
                }
                buffer[inbuffer++] = (byte) i;
                if (contentLength != -1 && ((++readyLength) == contentLength)) {
                    flush();
                    endWriting = true;
                }
            }
        } else {
            inbuffer++;
        }
    }

    /**This method binds the flush listener with the output stream.
     * @param listener the flush listener object.
     */
    public void setFlushListener(FlushListener listener) {
        this.listener = listener;
    }

    /**This method writes the array of byte values to the inner buffer.
     * @param b the array of byte values.
     * @exception IOException is thrown when the output stream is closed.
     */
    public void write(byte[] b) throws IOException {
        write(b, 0, b.length);
    }

    /**This method writes the given number of bytes from the given array to the
     * inner buffer.
     * @param b the array of byte values.
     * @param off //????????
     * @param len the number of bytes we want to write from the given array to
     * the inner buffer.
     * @exception IOException is thrown when the output stream is closed or the
     * given len parameter value is less than zero.
     */
    public void write(byte[] b, int off, int len) throws IOException {
        if (len < 0) {
            throw new IllegalArgumentException("Negative length");
        }
        if (strictWrite) {
            stream.write(b, off, len);
        } else if (sendBody) {
            hasBody = true;
            if (!endWriting) {
                if (contentLength == 0) {
                    flush();
                    endWriting = true;
                }
                boolean cont = true;
                if (contentLength != -1 && (readyLength + len > contentLength)) {
                    readyLength = contentLength;
                    len = contentLength - readyLength;
                    cont = false;
                } else if (contentLength != -1) {
                    readyLength = readyLength + (len > buffer.length - inbuffer
                            ? buffer.length - inbuffer : len);
                }
                if (inbuffer >= buffer.length) {
                    flush();
                }
                if (len < buffer.length - inbuffer) {
                    System.arraycopy(b, off, buffer, inbuffer, len);
                    inbuffer += len;
                } else {
                    int tow = buffer.length - inbuffer;
                    System.arraycopy(b, off, buffer, inbuffer, tow);
                    off += tow;
                    len -= tow;
                    inbuffer = buffer.length;
                    flush();
                    write(b, off, len);
                }
                if (!cont) {
                    flush();
                    endWriting = true;
                }
            }
        } else {
            if (len < buffer.length - inbuffer) {
                inbuffer += len;
            } else {
                int tow = buffer.length - inbuffer;
                off += tow;
                len -= tow;
                inbuffer = buffer.length;
                flush();
                write(b, off, len);
            }
        }
    }

    /**This method writes all data from the inner buffer to the outpit stream
     * and calles it's flush method.
     * @exception IOException is thrown if the output stream is closed.
     */
    public void flush() throws IOException {
        if (ignoreFlush) {
            return;
        }
        if (closed) {
            cat.debug("Cannot flush - stream closed");
            throw new IOException("Stream closed");
        }
        if (listener != null && !commited) {
            try {
                listenerFlush();
            } catch (IOException ioex) {
                commited = true;
                throw ioex;
            }
        }
        internalFlush();
        stream.flush();
    }

    /**This method gets the inner buffer size.
     * @return the inner buffer size.
     */
    public int getBufferSize() {
        return buffer.length;
    }

    /**This method sets the inner buffer size.
     * @param size the new buffer size.
     */
    public void setBufferSize(int size) {
        if (size < buffer.length) {
            return;
        }
        if (size % 512 != 0) {
            size = (size / 512 + 1) * 512;
        }
        byte[] tbuf = new byte[size];
        System.arraycopy(buffer, 0, tbuf, 0, inbuffer);
        buffer = tbuf;
    }

    /**This method sets the inner buffer infill indicator to zero.
     * Cleans the innre buffer.
     */
    public void clearBuffer() {
        inbuffer = 0;
        hasBody = false;
    }

    /**
     * @return True if the stream is commited, otherwise False.
     */
    public boolean isCommited() {
        return commited;
    }

    /**This method calles the flush method of this class and closes this
     * NusuthServletOutputStream class object.
     * @exception IOException is thrown if any error occures while writing to the
     * output stream.
     */
    public void close() throws IOException {
        if (closed) {
            cat.debug("Cannot flush - stream closed");
            throw new IOException("Stream closed");
        }
        if (listener != null && !commited) {
            try {
                listenerFlush();
            } catch (IOException ioex) {
                commited = true;
                throw ioex;
            }
        }
        internalFlush();
        if (sendBody) {
            if (isChunked()) {
                //Logger.log("0", -1);
                stream.write(LAST_CHUNK);
                stream.write(CRLF);
            }
        }
        stream.flush();
        closed = true;
    }

    /**This method calles the onFlush() method of the flush listener and writes data from
     * the inner buffer to the output stream.//XXX ???????????????????
     * @exception IOException is thrown if any error occures while writing to the output stream.
     */
    protected void listenerFlush() throws IOException {
/*    if (inbuffer > 0) {
      byte[] tmpbuf = new byte[inbuffer];
      System.arraycopy(buffer, 0, tmpbuf, 0, inbuffer);
      inbuffer = 0;
      listener.onFlush();
      //Logger.log(buffer, 0, inbuffer, -1);//XXX??????????????????? The inbuffer value is 0 !!!!!!!
      if (catProxy.isDebugEnabled()) {
        cat.debug(new String(buffer, 0, inbuffer));
      }
      stream.write(buffer, 0, inbuffer);//XXX??????????????????? The inbuffer value is 0 !!!!!!!
      System.arraycopy(tmpbuf, 0, buffer, 0, tmpbuf.length);
      inbuffer = tmpbuf.length;
    } else {
      listener.onFlush();
      //Logger.log(buffer, 0, inbuffer, -1); //XXX??????????????????? The inbuffer value is <= 0 !!!!!!!
      if (catProxy.isDebugEnabled()) {
        cat.debug(new String(buffer, 0, inbuffer));
      }
      stream.write(buffer, 0, inbuffer); //XXX??????????????????? The inbuffer value is <= 0 !!!!!!!
      inbuffer = 0; //XXX??????????????????? The inbuffer value is <= 0 !!!!!!!
    }*/
        strictWrite = true;
        try {
            listener.onFlush();
        } catch (IOException t) {
            throw t;
        } finally {
            strictWrite = false;
        }
        commited = true;
    }

    /**This method writes data from the inner buffer to the output stream.
     * Calles the flush method of the output stream.
     * @exception IOException is thrown if any error occures while writing to the
     * output stream.
     */
    protected void internalFlush() throws IOException {
        if (inbuffer == 0) {
            return;
        }
        if (sendBody) {
            if (inbuffer > 0 && isChunked()) {
                temp = inbuffer;
                counter = 6;
                while (temp > 0) {
                    forConv[--counter] = hexNum[temp % 16];
                    temp /= 16;
                }
                stream.write(forConv, counter, 8 - counter);
                stream.write(buffer, 0, inbuffer);
                stream.write(CRLF);
            } else {
                stream.write(buffer, 0, inbuffer);
            }
        }
        if (inbuffer > 0) {
            hasSendBody = true;
        }
        transfered = transfered + inbuffer;
        inbuffer = 0;
        hasBody = false;
    }

    /**
     * This method return true if this stream has any data in buffer or
     * any data was write to <i>stream</i>
     */
    public boolean hasBody() {
        return (hasSendBody || hasBody);
    }

    /**
     * @return the number of bytes in the inner buffer.
     */
    public int getBytesInBuffer() {
        return inbuffer;
    }

    /**
     * @return True if the chunked transfer coding is used, otherwise False.
     */
    public boolean isChunked() {
        return chunked;
    }

    /**This mehtod sets that the chunked transfer coding is used.
     * @param chunked True if the chunked transfer coding is used, otherwise False.
     */
    public void setChunked(boolean chunked) {
        if (!commited) {
            this.chunked = chunked;
        }
    }

    /**
     * Cleaning up stream
     */
    public void cleanup() {
        stream.cleanup();
        inbuffer = 0;
        listener = null;
        commited = false;
        closed = false;
        chunked = false;
        if (buffer.length != DEFAULT_BUFFER_SIZE) {
            buffer = new byte[DEFAULT_BUFFER_SIZE];
        }
        contentLength = -1;
        readyLength = 0;
        endWriting = false;
        ignoreFlush = false;
    }

    public int getNumberOfBytesTransfered() {
        return (stream != null) ? transfered : 0;
    }


    public void setContentLength(int len) {
        contentLength = len;
    }

    protected void ignoreFlush() {
        ignoreFlush = true;
    }

}

