/* Generated by VDGG */

package com.azoft.nusuth.core;

import java.io.*;
import java.util.*;
import java.util.jar.JarFile;
import java.util.jar.Manifest;
import java.util.jar.JarEntry;
import java.util.zip.*;
import java.net.URL;
import java.net.MalformedURLException;
import javax.servlet.Servlet;

//import com.azoft.nusuth.util.Logger;

/**This class is used to hold pathes for directories with the web application
 * classes and libs. It's also used to load class data, and instantiate
 * classses.
 * @author vdgg, skilz
 * @version 1.16
 * @since Nusuth1.0
 */
public class ServletLoader extends ClassLoader {
    private List classPathes = new ArrayList();
    private Hashtable loadedClasses = new Hashtable();
    private static String[] blackList = {"java.",
                                         "javax.servlet.",
                                         "javax.naming.",
                                         "javax.sql.",
                                         "javax.transaction.",
                                         "tyrex.",
                                         "com.azoft.nusuth."};
    private static String[] whiteList = {"com.azoft.nusuth.jndi.java.JavaContext",
                                         "com.azoft.nusuth.core.NusuthJdbcDataSource",
                                         "com.azoft.nusuth.jdbc.pool.driver.DriverDataSource"};

    private Hashtable openedArcs = new Hashtable();
    private String onlyClassName = null;
    private org.apache.log4j.Category cat = org.apache.log4j.Category.getInstance("com.azoft.nusuth.core");
    private Hashtable mainAttributes = new Hashtable();
    private Hashtable entryAttributes = new Hashtable();
    private List manifestResolvedJars = new LinkedList();

    /**This is the simple construtor of the ServletLoader class.
     */
    protected ServletLoader() {
        super();
    }

    protected ServletLoader(ClassLoader parent) {
        super(parent);
    }

    /**
     * @return the Iterator object that contains the class paths that were added before.
     */
    public Iterator getClassPathes() {
        return classPathes.iterator();
    }

    /**This method adds the new class path.
     * @param the class path.
     */
    public void addClassPath(String classPath) {
        if (!classPathes.contains(classPath)) {
            classPathes.add(classPath);
        }
        //System.out.println("Added classpath: " + classPath);
    }

    /**This method removes the given class path.
     * @param the class path name.
     */
    protected void removeClassPath(String classPath) {
        classPathes.remove(classPath);
    }

    /** This method finds and loads class with the given name.
     * @param className the class name.
     * @return the object of the Class type created for the class with the given name.
     * @exception ClassNotFoundException is thrown if there is no class with the given name.
     */
    protected synchronized Class findClass(String className) throws ClassNotFoundException {
        Class cl = (Class) loadedClasses.get(className);
        if (cl != null) {
            return cl;
        }
        for (int i = 0; i < blackList.length; i++) {
            if (className.startsWith(blackList[i])) {
                boolean isInWhiteList = false;
                for (int j = 0; j < whiteList.length; j++) {
                    if (className.startsWith(whiteList[j])) {
                        isInWhiteList = true;
                        break;
                    }
                }
                if (!isInWhiteList) {
                    return findSystemClass(className);
                }
            }
        }
        String searchPath = className.replace('.', '/');
        searchPath += ".class";
        byte[] loaded = loadClassData(searchPath);
        if (loaded == null) {
            if (getParent() != null) {
                cl = getParent().loadClass(className);
            }
            if (cl == null) {
                cl = findSystemClass(className);
            }
        } else {
            try {
                cl = defineClass(className, loaded, 0, loaded.length);
                loadedClasses.put(className, cl);
            } catch (Throwable t) {
                cat.error("Cannot find class " + className, t);
                t.printStackTrace();
                throw new ClassNotFoundException(className);
            }
        }
        if (cl == null) {
            throw new ClassNotFoundException("Class " + className + " not found");
        }
        return cl;
    }

    /**This method servlet with the given name.
     * @param className the servlet class name.
     * @return servlet class.
     * @exception ClassNotFoundException is thrown if there is no class with the given name.
     * @exception IllegalAccessException is thrown in the case of illegal access. //XXX ?????????
     * @exception InstantiationException is thrown if it is impossible to instantiate this class.
     */
    public Servlet loadServlet(String className) throws ClassNotFoundException, IllegalAccessException,
            InstantiationException {
        return (Servlet) loadClass(className).newInstance();
    }

    public synchronized Class loadClass(String className, boolean resolve) throws ClassNotFoundException {
//        System.out.println(className);
        if (onlyClassName != null && getParent() != null && !className.startsWith(onlyClassName)) {
            return getParent().loadClass(className);
        }
        Class result = findClass(className);
        if (resolve) {
            resolveClass(result);
        }
        return result;
    }

    /**
     * @param name class name.
     * @return object of the InputStream class associated with the loaded class(with the given name)data.
     */
    public InputStream getResourceAsStream(String name) {
        //    byte[] loaded = loadClassData(name);
        //    return (loaded == null)? null: new ByteArrayInputStream(loaded);
        try {
            URL resourceUrl = getResource(name);
            return resourceUrl == null ? null : resourceUrl.openStream();
        } catch (IOException e) {
        }
        return null;
    }

    /**
     * @param className class name.
     * @return loaded class data or null if any error occures.
     */
    private byte[] loadClassData(String className) {
        //    System.out.println("Load class "+className);
        String searchPath = className.replace('\\', '/');
        //    System.out.println("Load class search path "+searchPath);
        URL classFileUrl = findResource(searchPath);
        if (classFileUrl == null) {
            ClassLoader parent = getParent();
            if (parent != null) {
                if (parent.getResource(searchPath) != null)
                    classFileUrl = parent.getResource(searchPath);
            }
        }
        if (classFileUrl == null) {
            return null;
        }

        try {
            InputStream istream = classFileUrl.openStream();
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buf = new byte[2048];
            int count = 0;
            while ((count = istream.read(buf, 0, 2048)) != -1) {
                out.write(buf, 0, count);
            }
            out.flush();
            byte[] classBytes = out.toByteArray();
            istream.close();
            out.close();
            return classBytes;
        } catch (IOException ioex) {
            cat.error("Error read", ioex);
            return null;
        }
    }

    public URL findResource(String name) {
        Enumeration enum = findResources(name);
        return (enum.hasMoreElements() ? (URL) enum.nextElement() : null);
    }

    public URL getResource(String name) {
        ClassLoader parent = getParent();
        if (parent != null) {
            if (parent.getResource(name) != null)
                return parent.getResource(name);
        }
        return findResource(name);
    }

    public Enumeration findResources(String name) {
        Vector result = new Vector();
        String searchPath = name.replace('\\', '/');
        String fpath;
        String classPath;
        ZipFile classArc = null;
        ZipEntry classEntry;
        Iterator iterator = getClassPathes();
        while (iterator.hasNext()) {
            classPath = (String) iterator.next();
            if (classPath.endsWith(".jar") || classPath.endsWith(".zip")) {
                try {
                    classArc = null;
                    if (openedArcs.get(classPath) == null) {
                        classArc = classPath.endsWith(".jar") ? new JarFile(classPath) : new ZipFile(classPath);
                        openedArcs.put(classPath, classArc);
                    }
                    if (classArc == null) {
                        classArc = (ZipFile) openedArcs.get(classPath);
                    }
                    classEntry = classArc.getEntry(searchPath);
                    if (classEntry != null) {
                        try {
                            String protocol = "jar:file:" + (classPath.startsWith("/") ? "" : "/") + classPath + "!/" + classEntry.getName();
//******************************************************************************
                            if (classPath.endsWith(".jar")
                                    && !manifestResolvedJars.contains(classPath)) {
                                JarFile jarFile = new JarFile(classPath);
                                JarEntry manifestEntry
                                        = jarFile.getJarEntry(JarFile.MANIFEST_NAME);
                                if (manifestEntry != null) {
                                    InputStream is
                                            = jarFile.getInputStream(manifestEntry);
                                    BufferedReader reader
                                            = new BufferedReader(new InputStreamReader(is));
                                    mainAttributes.clear();
                                    String line = null;
                                    while (((line = reader.readLine()) != null
                                            && line.length() != 0) && !line.startsWith("Name")) {
                                        int sep = line.indexOf(':');
                                        if (sep != -1) {
                                            mainAttributes.put(line.substring(0, sep).trim(),
                                                    line.substring(sep + 1,
                                                            line.length()).trim());
                                        }
                                    }
                                    while (line != null) {
                                        line = definePackage(mainAttributes, classPath,
                                                reader, line);
                                    }
                                    manifestResolvedJars.add(classPath);
                                }
                            }
//******************************************************************************
                            result.add(new URL(protocol.replace('\\', '/')));
                        } catch (MalformedURLException e) {
                            e.printStackTrace();
                        }
                    }
                } catch (IOException ex) {
                    cat.error("Error read from archive", ex);
                }
            } else {
                fpath = classPath + File.separator + searchPath;
                File f = (new File(fpath));
                if (f.isFile()) {
                    try {
                        result.add(new URL((f.getAbsolutePath().startsWith("/") ? "file:" : "file:/") + f.getAbsolutePath()));
                    } catch (MalformedURLException e) {
                    }
                }
            }
        }
        return result.elements();
    }

    private String definePackage(Hashtable mainAttributes,
                                 String jarFileName,
                                 BufferedReader reader, String prevLine)
            throws IOException {
        String line = null;
        entryAttributes.clear();
        if (prevLine != null && prevLine.trim().length() > 0) {
            if (prevLine.trim().startsWith("Name")) {
                int sep = prevLine.indexOf(':');
                if (sep != -1) {
                    entryAttributes.put(prevLine.substring(0, sep).trim(),
                            prevLine.substring(sep + 1,
                                    prevLine.length()).trim());
                }
            }
        }
        while ((line = reader.readLine()) != null
                && line.length() != 0) {
            int sep = line.indexOf(':');
            if (sep != -1) {
                entryAttributes.put(line.substring(0, sep).trim(),
                        line.substring(sep + 1,
                                line.length()).trim());
            }
        }
        if (line == null && entryAttributes.size() == 0) {
            return null;
        }
        String name = (String) entryAttributes.get("Name");
        if (name == null) {
            return null;
        }
        if (name.endsWith("/")) {
            name = name.substring(0, name.length() - 1).replace('/', '.');
        }
        String specTitle = entryAttributes.get("Specification-Title") != null
                ? (String) entryAttributes.get("Specification-Title")
                : (String) mainAttributes.get("Specification-Title");
        String specVersion = entryAttributes.get("Specification-Version") != null
                ? (String) entryAttributes.get("Specification-Version")
                : (String) mainAttributes.get("Specification-Version");
        String specVendor = entryAttributes.get("Specification-Vendor") != null
                ? (String) entryAttributes.get("Specification-Vendor")
                : (String) mainAttributes.get("Specification-Vendor");
        String implTitle = entryAttributes.get("Implementation-Title") != null
                ? (String) entryAttributes.get("Implementation-Title")
                : (String) mainAttributes.get("Implementation-Title");
        String implVersion = entryAttributes.get("Implementation-Version") != null
                ? (String) entryAttributes.get("Implementation-Version")
                : (String) mainAttributes.get("Implementation-Version");
        String implVendor = entryAttributes.get("Implementation-Vendor") != null
                ? (String) entryAttributes.get("Implementation-Vendor")
                : (String) mainAttributes.get("Implementation-Vendor");
        URL sealBase = null;
        if (entryAttributes.get("Sealed") == null
                && mainAttributes.get("Sealed") == null) {
        } else {
            boolean sealed
                    = entryAttributes.get("Sealed") != null
                    ? ((String) entryAttributes.get("Sealed")).equalsIgnoreCase("true")
                    : ((String) mainAttributes.get("Sealed")).equalsIgnoreCase("true");
            if (sealed) {
                sealBase = new URL("file:///" + jarFileName);
            }
        }
        if (!name.endsWith(".class") && getPackage(name) == null) {
            definePackage(name, specTitle, specVersion, specVendor,
                    implTitle, implVersion, implVendor, sealBase);
        }
        return line;
    }

    public static ServletLoader createLoader(ServletLoader parent) {
        ServletLoader res = new ServletLoader(parent);
        return res;
    }

    protected void close() {
        Enumeration arcKeys = openedArcs.keys();
        String cp;
        ZipFile arc;
        while (arcKeys.hasMoreElements()) {
            cp = (String) arcKeys.nextElement();
            arc = (ZipFile) openedArcs.get(cp);
            try {
                arc.close();
            } catch (Exception ex) {
                //Logger.log(ex, 1);
                cat.error("Cannot close archive", ex);
            }
        }
    }

    public void defineOnlyClass(String className) {
        onlyClassName = className;
    }
}

