/* Generated by VDGG */

package com.azoft.nusuth.core;

import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpServletRequest;

/**This interface is implemented by the NusuthResponse abstract class.
 * @author VDGG (vdgg@azoft.com)
 * @version 1.0
 * @since 1.0
 */
public interface SessionCreationListener {

    /**In the HTTPJBirdResponse class this method saves session ID
     * (if the new session was created for this request) in the
     * response object.
     * @param session created session.
     */
    void sessionCreated(HttpSession session, NusuthRequest request);
}

